In [28]:
import pandas as pd
from linearmodels.panel import PanelOLS
from linearmodels.panel import RandomEffects
from linearmodels.panel import compare
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import statsmodels.formula.api as smf
from statsmodels.stats.diagnostic import acorr_ljungbox
from scipy.stats import chi2
from pathlib import Path
import statsmodels.api as sm
import numpy as np
from scipy.stats import chi2

In [29]:
# 데이터 불러오기
df = pd.read_csv("/Volumes/ORICO/Climate risk/CBRE_NOAA 2007-2024.csv")

df.head()

/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/384946503.py:2: DtypeWarning: Columns (4,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/Volumes/ORICO/Climate risk/CBRE_NOAA 2007-2024.csv")

,Year of Data,PropertyID,City,State,Zip,YearOpened,Rooms,Occupancy,ADR,RevPar,...,Fire_events,Tropical_events,Other_events,Meteorological_damage,Hydrological_damage,Climatological_damage,Geophysical_damage,Fire_damage,Tropical_damage,Other_damage
0,2007,101,Atlanta,GA,30326,1974.0,230,75.2%,$122.98,$92.45,...,7.0,2.0,0.0,134151100.0,327000.0,505000000.0,0.0,21701000.0,0.0,0.0
1,2007,111,Atlanta,GA,30344,1973.0,378,67.0%,$98.28,$65.86,...,7.0,2.0,0.0,134151100.0,327000.0,505000000.0,0.0,21701000.0,0.0,0.0
2,2007,118,Arlington,VA,22202,1972.0,280,73.2%,$131.86,$96.55,...,2.0,0.0,0.0,3436000.0,154000.0,17355000.0,0.0,85000.0,0.0,0.0
3,2007,123,Gaithersburg,MD,20879,1971.0,300,63.3%,$93.31,$59.10,...,0.0,0.0,0.0,349000.0,11000.0,5000.0,0.0,0.0,0.0,0.0
4,2007,124,Denver,CO,80207,1973.0,561,78.5%,$81.04,$63.65,...,7.0,0.0,0.0,5425750.0,3502000.0,20000.0,50000.0,771000.0,0.0,0.0

In [30]:
print(df.dtypes)

Year of Data               int64
PropertyID                 int64
City                      object
State                     object
Zip                       object
                          ...
Climatological_damage    float64
Geophysical_damage       float64
Fire_damage              float64
Tropical_damage          float64
Other_damage             float64
Length: 199, dtype: object

In [31]:
# ChainSegment 간단히 그룹화
def simplify_chain(segment):
    if segment in ['Luxury', 'Upper Upscale']:
        return 'High-End'
    elif segment in ['Upscale', 'Upper Midscale']:
        return 'Mid-Range'
    elif segment in ['Midscale', 'Economy']:
        return 'Budget'

df['ChainGroup'] = df['ChainSegment'].apply(simplify_chain)

# ChainGroup: Mid-Range를 reference
df['ChainGroup'] = pd.Categorical(df['ChainGroup'],
                                  categories=['Mid-Range', 'High-End', 'Budget'],
                                  ordered=False)


# 새 그룹으로 더미 생성
dummies = pd.get_dummies(df['ChainGroup'], drop_first=True)
df = pd.concat([df, dummies], axis=1)

In [32]:
print(df['ChainSegment'].value_counts())
print(df['ChainGroup'].value_counts())

ChainSegment
Upscale           34062
Upper Midscale    23092
Upper Upscale     17481
Economy           11576
Luxury             5180
Midscale           4744
Name: count, dtype: int64
ChainGroup
Mid-Range    57154
High-End     22661
Budget       16320
Name: count, dtype: int64

In [33]:
# noaa_region9 정리 및 카테고리화
df["noaa_region9"] = df["noaa_region9"].astype(str).str.strip()
df.loc[df["noaa_region9"].isin(["", "NaN", "nan", "None"]), "noaa_region9"] = np.nan

conus_regions = [
    "Northeast","Southeast","South","Ohio Valley","Upper Midwest",
    "Northern Rockies & Plains","Southwest","Northwest","West"
]

# 기준범주(reference) 자동 선택: CONUS 중 최빈 → 없으면 전체 최빈 → 없으면 'West'
mode_conus = df.loc[df["noaa_region9"].isin(conus_regions), "noaa_region9"].mode(dropna=True)
if not mode_conus.empty:
    baseline = mode_conus.iloc[0]
else:
    mode_all = df["noaa_region9"].mode(dropna=True)
    baseline = mode_all.iloc[0] if not mode_all.empty else "West"

cats = [baseline] + sorted([c for c in df["noaa_region9"].dropna().unique() if c != baseline])
df["noaa_region9"] = pd.Categorical(df["noaa_region9"], categories=cats, ordered=False)

print("Reference(기준) region =", baseline)

# 3) (선택) 원-핫 더미 만들기 (drop_first=True) → 회귀 X행렬로 직접 쓰고 싶을 때
noaa_dummies = pd.get_dummies(df["noaa_region9"], prefix="noaa", drop_first=True)


df = pd.concat([df, noaa_dummies], axis=1)


print(noaa_dummies.columns)
print(df.shape)
print(df[['noaa_region9'] + list(noaa_dummies.columns)].head())

Reference(기준) region = Southeast
Index(['noaa_Midwest', 'noaa_Northeast', 'noaa_Northern Plains',
       'noaa_Northwest', 'noaa_Pacific', 'noaa_South', 'noaa_Southwest',
       'noaa_West'],
      dtype='object')
(96358, 210)
  noaa_region9  noaa_Midwest  noaa_Northeast  noaa_Northern Plains  \
0    Southeast         False           False                 False
1    Southeast         False           False                 False
2    Southeast         False           False                 False
3    Northeast         False            True                 False
4    Southwest         False           False                 False

   noaa_Northwest  noaa_Pacific  noaa_South  noaa_Southwest  noaa_West
0           False         False       False           False      False
1           False         False       False           False      False
2           False         False       False           False      False
3           False         False       False           False      False
4           False         False       False            True      False

In [34]:
def clean_numeric(s):
    s = s.astype(str)
    s = s.str.replace(",", "", regex=False)
    s = s.str.replace("$", "", regex=False)
    s = s.str.strip()
    s = s.replace(["", "nan", "-", "None"], np.nan)
    return pd.to_numeric(s, errors="coerce")


# 🔹 CBRE 주요 재무변수 클린
cols_to_clean = [
    'ITTotalExpense','ITSandW','ITSystemExpenseOperDept','ITTotalOtherExpense',
    'ITTotalLabor','ITCostofServicePhone','ITCostofServiceInternet',
    'ITSystemExpenseUndistribDept','TotalLabor','MaintTotalExp','UtilTotalExp',
    'Insurance','RevPar','ADR','GrossOperatingProfit','EBITDA',
    'TotalHotelRevenue','TotalSAndW','TotalBenefits','SandMTotalExpense',
    'MktingTotalExp','MktingAdvertising','TotalMgmtFee','BaseMgmtFee',
    'IncentMgmtFee','FandBTotalRevenue','PropertyTax',
    
    # ✅ 추가됨
    'Available',   # for Goppar
    'YearOpened'   # age 계산 안정화용 (있으면)
]

for c in cols_to_clean:
    if c in df.columns:
        df[c] = clean_numeric(df[c])



# 🔹 Derived metrics
df['Goppar'] = df['GrossOperatingProfit'] / df['Available']
df['F&BRatio'] = df['FandBTotalRevenue'] / df['TotalHotelRevenue']
df['ITService'] = df['ITCostofServicePhone'] + df['ITCostofServiceInternet']
df['ITSystem'] = df['ITSystemExpenseOperDept'] + df['ITSystemExpenseUndistribDept']

# 🔹 age
df['age'] = df['Year of Data'] - pd.to_numeric(df['YearOpened'], errors="coerce")


# 🔹 NOAA 피해/건수 클린
noaa_cols = [
    'Meteorological_events','Meteorological_damage','Hydrological_events',
    'Hydrological_damage','Climatological_events','Climatological_damage',
    'Geophysical_events','Geophysical_damage','Fire_events','Fire_damage',
    'Tropical_events','Tropical_damage','Other_events','Other_damage'
]

for c in noaa_cols:
    if c in df.columns:
        df[c] = clean_numeric(df[c])

In [35]:
#로그 및 Asinh

#log 
df['ITTotalExpense_log'] = np.log1p(df["ITTotalExpense"])
df['ITTotalLabor_log'] = np.log1p(df["ITTotalLabor"])
df['ITService_log'] = np.log1p(df["ITService"])
df['ITSystem_log'] = np.log1p(df["ITSystem"])
df['TotalLabor_log'] = np.log1p(df["TotalLabor"])
df['ITTotalLabor_log'] = np.log1p(df["ITTotalLabor"])

df['MaintTotalExp_log'] = np.log1p(df["MaintTotalExp"])
df['UtilTotalExp_log'] = np.log1p(df["UtilTotalExp"])
df['Insurance_log'] = np.log1p(df["Insurance"])
df['RevPar_log'] = np.log1p(df["RevPar"])
df['PropertyTax_log'] = np.log1p(df["PropertyTax"])
df['SandMTotalExpense_log'] = np.log1p(df["SandMTotalExpense"])
df['MktingTotalExp_log'] = np.log1p(df["MktingTotalExp"])
df['TotalMgmtFee_log'] = np.log1p(df["TotalMgmtFee"])

In [36]:
#기후리스크 건수와 피해액 합수 변수 생성


df['Meteorological_events_log'] = np.log1p(df["Meteorological_events"])
df['Meteorological_damage_log'] = np.log1p(df["Meteorological_damage"])
df['Hydrological_events_log'] = np.log1p(df["Hydrological_events"])
df['Hydrological_damage_log'] = np.log1p(df["Hydrological_damage"])
df['Climatological_events_log'] = np.log1p(df["Climatological_events"])
df['Climatological_damage_log'] = np.log1p(df["Climatological_damage"])
df['Geophysical_events_log'] = np.log1p(df["Geophysical_events"])
df['Geophysical_damage_log'] = np.log1p(df["Geophysical_damage"])
df['Fire_events_log'] = np.log1p(df["Fire_events"])
df['Fire_damage_log'] = np.log1p(df["Fire_damage"])
df['Tropical_events_log'] = np.log1p(df["Tropical_events"])
df['Tropical_damage_log'] = np.log1p(df["Tropical_damage"])
df['Other_events_log'] = np.log1p(df["Other_events"])
df['Other_damage_log'] = np.log1p(df["Other_damage"])
#df['ZipClimate_Meteorological_events_log'] = np.log1p(df["ZipClimate_Meteorological_events"])
#df['ZipClimate_Meteorological_damage_log'] = np.log1p(df["ZipClimate_Meteorological_damage"])
#df['ZipClimate_Hydrological_events_log'] = np.log1p(df["ZipClimate_Hydrological_events"])
#df['ZipClimate_Hydrological_damage_log'] = np.log1p(df["ZipClimate_Hydrological_damage"])



# 결합형

df["Meteorological_risk_log"] = (
    df["Meteorological_events_log"] + df["Meteorological_damage_log"]
) / 2

df["Hydrological_risk_log"] = (
    df["Hydrological_events_log"] + df["Hydrological_damage_log"]
) / 2

df["Climatological_risk_log"] = (
    df["Climatological_events_log"] + df["Climatological_damage_log"]
) / 2

df["Geophysical_risk_log"] = (
    df["Geophysical_events_log"] + df["Geophysical_damage_log"]
) / 2

df["Fire_risk_log"] = (
    df["Fire_events_log"] + df["Fire_damage_log"]
) / 2

df["Tropical_risk_log"] = (
    df["Tropical_events_log"] + df["Tropical_damage_log"]
) / 2

df["Other_risk_log"] = (
    df["Other_events_log"] + df["Other_damage_log"]
) / 2

#df["Zip_Meteorological_risk_log"] = (
#    df["ZipClimate_Meteorological_events_log"] + df["ZipClimate_Meteorological_damage_log"]
#) / 2

#df["Zip_Hydrological_risk_log"] = (
#    df["ZipClimate_Hydrological_events_log"] + df["ZipClimate_Hydrological_damage_log"]
#) / 2

In [37]:
df.head()

,Year of Data,PropertyID,City,State,Zip,YearOpened,Rooms,Occupancy,ADR,RevPar,...,Tropical_damage_log,Other_events_log,Other_damage_log,Meteorological_risk_log,Hydrological_risk_log,Climatological_risk_log,Geophysical_risk_log,Fire_risk_log,Tropical_risk_log,Other_risk_log
0,2007,101,Atlanta,GA,30326,1974.0,230,75.2%,122.98,92.45,...,0.0,0.0,0.0,12.265794,7.547807,11.609061,0.000000,9.486155,0.549306,0.0
1,2007,111,Atlanta,GA,30344,1973.0,378,67.0%,98.28,65.86,...,0.0,0.0,0.0,12.265794,7.547807,11.609061,0.000000,9.486155,0.549306,0.0
2,2007,118,Arlington,VA,22202,1972.0,280,73.2%,131.86,96.55,...,0.0,0.0,0.0,10.291604,7.540104,10.290707,0.000000,6.224515,0.000000,0.0
3,2007,123,Gaithersburg,MD,20879,1971.0,300,63.3%,93.31,59.10,...,0.0,0.0,0.0,8.830335,5.851818,6.173017,0.000000,0.000000,0.000000,0.0
4,2007,124,Denver,CO,80207,1973.0,561,78.5%,81.04,63.65,...,0.0,0.0,0.0,10.723419,9.391209,6.599687,6.103046,7.817443,0.000000,0.0

In [11]:
df = df.set_index(['PropertyID', 'Year of Data'])

In [38]:
df = df.sort_values(by=['PropertyID', 'Year of Data'])

# Lag 원 변수 생성
df['lag_ITTotalExpense'] = df.groupby('PropertyID')['ITTotalExpense'].shift(1)
df['lag_TotalLabor'] = df.groupby('PropertyID')['TotalLabor'].shift(1)
df['lag_ITTotalLabor'] = df.groupby('PropertyID')['ITTotalLabor'].shift(1)
df['lag_ITService'] = df.groupby('PropertyID')['ITService'].shift(1)
df['lag_ITSystem'] = df.groupby('PropertyID')['ITSystem'].shift(1)

df['lag_MaintTotalExp'] = df.groupby('PropertyID')['MaintTotalExp'].shift(1)
df['lag_UtilTotalExp'] = df.groupby('PropertyID')['UtilTotalExp'].shift(1)
df['lag_Insurance'] = df.groupby('PropertyID')['Insurance'].shift(1)
df['lag_SandMTotalExpense'] = df.groupby('PropertyID')['SandMTotalExpense'].shift(1)
df['lag_MktingTotalExp'] = df.groupby('PropertyID')['MktingTotalExp'].shift(1)

df['lag_TotalMgmtFee'] = df.groupby('PropertyID')['TotalMgmtFee'].shift(1)
df['lag_PropertyTax'] = df.groupby('PropertyID')['PropertyTax'].shift(1)
df['lag_Rooms'] = df.groupby('PropertyID')['Rooms'].shift(1)
df['lag_age'] = df.groupby('PropertyID')['age'].shift(1)
df['lag_MktingTotalExp'] = df.groupby('PropertyID')['MktingTotalExp'].shift(1)

df["lag_Meteorological_risk_log"] = df.groupby('PropertyID')['Meteorological_risk_log'].shift(1)
df["lag_Hydrological_risk_log"] = df.groupby('PropertyID')['Hydrological_risk_log'].shift(1)
df["lag_Climatological_risk_log"] = df.groupby('PropertyID')['Climatological_risk_log'].shift(1)
df["lag_Geophysical_risk_log"] = df.groupby('PropertyID')['Geophysical_risk_log'].shift(1)
df["lag_Fire_risk_log"] = df.groupby('PropertyID')['Fire_risk_log'].shift(1)
df["lag_Tropical_risk_log"] = df.groupby('PropertyID')['Tropical_risk_log'].shift(1)
df["lag_Other_risk_log"] = df.groupby('PropertyID')['Other_risk_log'].shift(1)
#df["lag_Zip_Meteorological_risk_log"] = df.groupby('PropertyID')['Zip_Meteorological_risk_log'].shift(1)
#df["lag_Zip_Hydrological_risk_log"] = df.groupby('PropertyID')['Zip_Hydrological_risk_log'].shift(1)

#df['lag_ITTotalOtherExpense'] = df.groupby('PropertyID')['ITTotalOtherExpense'].shift(1)'

/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3213558728.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITService'] = df.groupby('PropertyID')['ITService'].shift(1)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3213558728.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITSystem'] = df.groupby('PropertyID')['ITSystem'].shift(1)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3213558728.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_MaintTotalExp'] = df.groupby('PropertyID')['MaintTotalExp'].shift(1)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3213558728.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_UtilTotalExp'] = df.groupby('PropertyID')['UtilTotalExp'].shift(1)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3213558728.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_Insurance'] = df.groupby('PropertyID')['Insurance'].shift(1)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3213558728.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_SandMTotalExpense'] = df.groupby('PropertyID')['SandMTotalExpense'].shift(1)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3213558728.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_MktingTotalExp'] = df.groupby('PropertyID')['MktingTotalExp'].shift(1)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3213558728.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_TotalMgmtFee'] = df.groupby('PropertyID')['TotalMgmtFee'].shift(1)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3213558728.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_PropertyTax'] = df.groupby('PropertyID')['PropertyTax'].shift(1)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3213558728.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_Rooms'] = df.groupby('PropertyID')['Rooms'].shift(1)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3213558728.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_age'] = df.groupby('PropertyID')['age'].shift(1)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3213558728.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["lag_Meteorological_risk_log"] = df.groupby('PropertyID')['Meteorological_risk_log'].shift(1)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3213558728.py:23: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["lag_Hydrological_risk_log"] = df.groupby('PropertyID')['Hydrological_risk_log'].shift(1)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3213558728.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["lag_Climatological_risk_log"] = df.groupby('PropertyID')['Climatological_risk_log'].shift(1)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3213558728.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["lag_Geophysical_risk_log"] = df.groupby('PropertyID')['Geophysical_risk_log'].shift(1)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3213558728.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["lag_Fire_risk_log"] = df.groupby('PropertyID')['Fire_risk_log'].shift(1)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3213558728.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["lag_Tropical_risk_log"] = df.groupby('PropertyID')['Tropical_risk_log'].shift(1)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3213558728.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["lag_Other_risk_log"] = df.groupby('PropertyID')['Other_risk_log'].shift(1)

In [39]:
#lag된 기후 리스크 교호항 생성

df['lag_ITxMeteo_risk'] = df['lag_ITTotalExpense'] * df["lag_Meteorological_risk_log"]
df['lag_ITxHydro_risk'] = df['lag_ITTotalExpense'] * df["lag_Hydrological_risk_log"]
df['lag_ITxClimato_risk'] = df['lag_ITTotalExpense'] * df["lag_Climatological_risk_log"]
df['lag_ITxGeophy_risk'] = df['lag_ITTotalExpense'] * df["lag_Geophysical_risk_log"]
df['lag_ITxFire_risk'] = df['lag_ITTotalExpense'] * df["lag_Fire_risk_log"]
df['lag_ITxTropi_risk'] = df['lag_ITTotalExpense'] * df["lag_Tropical_risk_log"]
df['lag_ITxOther_risk'] = df['lag_ITTotalExpense'] * df["lag_Other_risk_log"]
df['lag_ITLaborxMeteo_risk'] = df['lag_ITTotalLabor'] * df["lag_Meteorological_risk_log"]
df['lag_ITLaborxHydro_risk'] = df['lag_ITTotalLabor'] * df["lag_Hydrological_risk_log"]
df['lag_ITLaborxClimato_risk'] = df['lag_ITTotalLabor'] * df["lag_Climatological_risk_log"]
df['lag_ITLaborxGeophy_risk'] = df['lag_ITTotalLabor'] * df["lag_Geophysical_risk_log"]
df['lag_ITLaborxFire_risk'] = df['lag_ITTotalLabor'] * df["lag_Fire_risk_log"]
df['lag_ITLaborxTropi_risk'] = df['lag_ITTotalLabor'] * df["lag_Tropical_risk_log"]
df['lag_ITLaborxOther_risk'] = df['lag_ITTotalLabor'] * df["lag_Other_risk_log"]
df['lag_ITServxMeteo_risk'] = df['lag_ITService'] * df["lag_Meteorological_risk_log"]
df['lag_ITServxHydro_risk'] = df['lag_ITService'] * df["lag_Hydrological_risk_log"]
df['lag_ITServxClimato_risk'] = df['lag_ITService'] * df["lag_Climatological_risk_log"]
df['lag_ITServxGeophy_risk'] = df['lag_ITService'] * df["lag_Geophysical_risk_log"]
df['lag_ITServxFire_risk'] = df['lag_ITService'] * df["lag_Fire_risk_log"]
df['lag_ITServxTropi_risk'] = df['lag_ITService'] * df["lag_Tropical_risk_log"]
df['lag_ITServxOther_risk'] = df['lag_ITService'] * df["lag_Other_risk_log"]
df['lag_ITSysxMeteo_risk'] = df['lag_ITSystem'] * df["lag_Meteorological_risk_log"]
df['lag_ITSysxHydro_risk'] = df['lag_ITSystem'] * df["lag_Hydrological_risk_log"]
df['lag_ITSysxClimato_risk'] = df['lag_ITSystem'] * df["lag_Climatological_risk_log"]
df['lag_ITSysxGeophy_risk'] = df['lag_ITSystem'] * df["lag_Geophysical_risk_log"]
df['lag_ITSysxFire_risk'] = df['lag_ITSystem'] * df["lag_Fire_risk_log"]
df['lag_ITSysxTropi_risk'] = df['lag_ITSystem'] * df["lag_Tropical_risk_log"]
df['lag_ITSysxOther_risk'] = df['lag_ITSystem'] * df["lag_Other_risk_log"]
df['lag_LaborxMeteo_risk'] = df['lag_TotalLabor'] * df["lag_Meteorological_risk_log"]
df['lag_LaborxHydro_risk'] = df['lag_TotalLabor'] * df["lag_Hydrological_risk_log"]
df['lag_LaborxClimato_risk'] = df['lag_TotalLabor'] * df["lag_Climatological_risk_log"]
df['lag_LaborxGeophy_risk'] = df['lag_TotalLabor'] * df["lag_Geophysical_risk_log"]
df['lag_LaborxFire_risk'] = df['lag_TotalLabor'] * df["lag_Fire_risk_log"]
df['lag_LaborxTropi_risk'] = df['lag_TotalLabor'] * df["lag_Tropical_risk_log"]
df['lag_LaborxOther_risk'] = df['lag_TotalLabor'] * df["lag_Other_risk_log"]

/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITxMeteo_risk'] = df['lag_ITTotalExpense'] * df["lag_Meteorological_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITxHydro_risk'] = df['lag_ITTotalExpense'] * df["lag_Hydrological_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITxClimato_risk'] = df['lag_ITTotalExpense'] * df["lag_Climatological_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITxGeophy_risk'] = df['lag_ITTotalExpense'] * df["lag_Geophysical_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITxFire_risk'] = df['lag_ITTotalExpense'] * df["lag_Fire_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITxTropi_risk'] = df['lag_ITTotalExpense'] * df["lag_Tropical_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITxOther_risk'] = df['lag_ITTotalExpense'] * df["lag_Other_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITLaborxMeteo_risk'] = df['lag_ITTotalLabor'] * df["lag_Meteorological_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITLaborxHydro_risk'] = df['lag_ITTotalLabor'] * df["lag_Hydrological_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITLaborxClimato_risk'] = df['lag_ITTotalLabor'] * df["lag_Climatological_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITLaborxGeophy_risk'] = df['lag_ITTotalLabor'] * df["lag_Geophysical_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITLaborxFire_risk'] = df['lag_ITTotalLabor'] * df["lag_Fire_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITLaborxTropi_risk'] = df['lag_ITTotalLabor'] * df["lag_Tropical_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:16: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITLaborxOther_risk'] = df['lag_ITTotalLabor'] * df["lag_Other_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITServxMeteo_risk'] = df['lag_ITService'] * df["lag_Meteorological_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:18: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITServxHydro_risk'] = df['lag_ITService'] * df["lag_Hydrological_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:19: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITServxClimato_risk'] = df['lag_ITService'] * df["lag_Climatological_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITServxGeophy_risk'] = df['lag_ITService'] * df["lag_Geophysical_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITServxFire_risk'] = df['lag_ITService'] * df["lag_Fire_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITServxTropi_risk'] = df['lag_ITService'] * df["lag_Tropical_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:23: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITServxOther_risk'] = df['lag_ITService'] * df["lag_Other_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:24: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITSysxMeteo_risk'] = df['lag_ITSystem'] * df["lag_Meteorological_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:25: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITSysxHydro_risk'] = df['lag_ITSystem'] * df["lag_Hydrological_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITSysxClimato_risk'] = df['lag_ITSystem'] * df["lag_Climatological_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:27: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITSysxGeophy_risk'] = df['lag_ITSystem'] * df["lag_Geophysical_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:28: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITSysxFire_risk'] = df['lag_ITSystem'] * df["lag_Fire_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:29: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITSysxTropi_risk'] = df['lag_ITSystem'] * df["lag_Tropical_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:30: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_ITSysxOther_risk'] = df['lag_ITSystem'] * df["lag_Other_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:31: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_LaborxMeteo_risk'] = df['lag_TotalLabor'] * df["lag_Meteorological_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:32: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_LaborxHydro_risk'] = df['lag_TotalLabor'] * df["lag_Hydrological_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:33: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_LaborxClimato_risk'] = df['lag_TotalLabor'] * df["lag_Climatological_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:34: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_LaborxGeophy_risk'] = df['lag_TotalLabor'] * df["lag_Geophysical_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_LaborxFire_risk'] = df['lag_TotalLabor'] * df["lag_Fire_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:36: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_LaborxTropi_risk'] = df['lag_TotalLabor'] * df["lag_Tropical_risk_log"]
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/3982829646.py:37: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['lag_LaborxOther_risk'] = df['lag_TotalLabor'] * df["lag_Other_risk_log"]

In [40]:
df.head()

,Year of Data,PropertyID,City,State,Zip,YearOpened,Rooms,Occupancy,ADR,RevPar,...,lag_ITSysxFire_risk,lag_ITSysxTropi_risk,lag_ITSysxOther_risk,lag_LaborxMeteo_risk,lag_LaborxHydro_risk,lag_LaborxClimato_risk,lag_LaborxGeophy_risk,lag_LaborxFire_risk,lag_LaborxTropi_risk,lag_LaborxOther_risk
0,2007,101,Atlanta,GA,30326,1974.0,230,75.2%,122.98,92.45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8729,2009,101,Atlanta,GA,30326,1974.0,230,64.7%,106.11,68.68,...,NaN,NaN,NaN,3.893285e+07,2.395749e+07,3.684831e+07,0.0,3.011000e+07,1.743552e+06,0.000000e+00
12498,2010,101,Atlanta,GA,30326,1974.0,230,72.0%,102.70,73.91,...,NaN,NaN,NaN,3.389268e+07,3.148290e+07,0.000000e+00,0.0,2.151131e+07,9.930896e+05,1.188453e+07
16957,2011,101,Atlanta,GA,30326.0,1974.0,230,68.3%,105.49,72.06,...,NaN,NaN,NaN,3.384558e+07,2.518296e+07,3.688204e+06,0.0,2.089158e+07,0.000000e+00,2.659406e+06
22005,2012,101,Atlanta,GA,30326,1974.0,230,73.7%,111.47,82.18,...,NaN,NaN,NaN,3.570600e+07,2.089779e+07,3.122713e+07,0.0,2.600394e+07,1.013100e+06,2.352345e+06

In [18]:
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler


# ===========================================================
# ✅ MixedLM with PCA-based Tropical Risk
#  - Risk = PCA1(log1p(events), log1p(damage))
#  - Risk_z = z-score of PCA score
#  - IT: within/between decomposition (z-scored)
#  - Interactions: IT_within×Risk_z, IT_mean_hotel×Risk_z
#  - FE: ChainSegment, Region9, Year
#  - RE: (1) Random intercept  (2) Random intercept + random slope(IT_within)
# ===========================================================

# ------------------------------
# 0) 안전한 reset_index (ID가 index였을 수 있음)
# ------------------------------
df = df.reset_index()

# ------------------------------
# 1) 변수 설정 / rename
# ------------------------------
ID     = "PropertyID"
REGION = "noaa_region9"
SEG    = "ChainSegment"

if "Year of Data" in df.columns and "Year" not in df.columns:
    df = df.rename(columns={"Year of Data": "Year"})
YEAR = "Year"

Y  = "RevPar_log"
IT = "ITTotalExpense"



# 1️⃣ log return 생성
df["RevPar_return"] = df.groupby(ID)["RevPar_log"].diff()

# 2️⃣ 5년 rolling std
df["RevPar_vol_5y"] = (
    df.groupby(ID)["RevPar_return"]
      .rolling(window=5, min_periods=3)
      .std()
      .reset_index(level=0, drop=True)
)

# PCA 구성에 사용할 원천 변수(원래 이미 만들어둔 log 변수 사용)
EV_LOG = "Tropical_events_log"
DMG_LOG = "Tropical_damage_log"

CONTROLS = [
    "TotalLabor","MaintTotalExp","UtilTotalExp",
    "Insurance","SandMTotalExpense","MktingTotalExp",
    "TotalMgmtFee","PropertyTax","Rooms","age"
]

# ------------------------------
# 2) 변환 함수 (money vars)
# ------------------------------
def safe_transform(series, use_asinh_if_negative=True):
    s = pd.to_numeric(series, errors="coerce")
    if use_asinh_if_negative and (s.dropna() < 0).any():
        return np.arcsinh(s)
    else:
        return np.log1p(s.clip(lower=0))

money_vars = [
    IT,
    "TotalLabor","MaintTotalExp","UtilTotalExp","Insurance",
    "SandMTotalExpense","MktingTotalExp","TotalMgmtFee",
    "PropertyTax","Rooms"
]

for col in money_vars:
    if col in df.columns and f"tr_{col}" not in df.columns:
        df[f"tr_{col}"] = safe_transform(df[col], use_asinh_if_negative=True)

IT_term = f"tr_{IT}"

# controls term 구성 (age는 그대로)
CONTROLS_term = []
for c in CONTROLS:
    if c == "age":
        CONTROLS_term.append("age")
    elif c in money_vars:
        CONTROLS_term.append(f"tr_{c}")
    else:
        CONTROLS_term.append(c)

# ------------------------------
# 3) 분석용 컬럼 구성 (PCA용 변수 포함)
# ------------------------------
base_cols = [Y, ID, REGION, SEG, YEAR, IT_term, EV_LOG, DMG_LOG] + CONTROLS_term
d = df[base_cols].dropna().copy()

# Year는 int 유지
d[YEAR] = pd.to_numeric(d[YEAR], errors="coerce")
d = d.dropna(subset=[YEAR])
d[YEAR] = d[YEAR].astype(int)

# 카테고리
d[SEG] = d[SEG].astype("category")
d[REGION] = d[REGION].astype("category")

# ------------------------------
# 4) PCA Risk 생성 (샘플 d에서 학습 → d에 부여)
#    - 표준화 후 PCA 추천 (둘의 스케일/분산 차이를 제거)
# ------------------------------
X = d[[EV_LOG, DMG_LOG]].values
X_std = StandardScaler(with_mean=True, with_std=True).fit_transform(X)

pca = PCA(n_components=1, random_state=0)
risk_pca = pca.fit_transform(X_std).ravel()

# 방향성(부호) 정리: 해석 편의를 위해 "events+damage 증가" 방향이 +가 되도록
# (PC는 부호가 임의라서 고정해주는 게 논문에 유리)
if np.corrcoef(risk_pca, d[EV_LOG].values)[0,1] < 0:
    risk_pca = -risk_pca
    pca.components_ = -pca.components_

d["Risk_pca"] = risk_pca

# Risk_z (z-score)
d["Risk_z"] = (d["Risk_pca"] - d["Risk_pca"].mean()) / d["Risk_pca"].std(ddof=0)

print("PCA weights (events, damage):", pca.components_)
print("Explained variance ratio:", pca.explained_variance_ratio_)

# ------------------------------
# 5) IT within / between 분해 + z-score
# ------------------------------
d["IT_mean_hotel"] = d.groupby(ID)[IT_term].transform("mean")
d["IT_within"] = d[IT_term] - d["IT_mean_hotel"]

for col in ["IT_mean_hotel", "IT_within"]:
    d[col] = (d[col] - d[col].mean()) / d[col].std(ddof=0)

# ------------------------------
# 6) Interaction (within/between 각각)
# ------------------------------
d["ITw_x_R"] = d["IT_within"] * d["Risk_z"]
d["ITb_x_R"] = d["IT_mean_hotel"] * d["Risk_z"]

# ------------------------------
# 7) controls 표준화 (age 제외) - 선택(권장)
# ------------------------------
z_cols = [c for c in CONTROLS_term if c != "age"]
for col in z_cols:
    if col in d.columns:
        sd = d[col].std(ddof=0)
        if sd > 0:
            d[col] = (d[col] - d[col].mean()) / sd

# ------------------------------
# 8) MixedLM 식 정의 (FE 포함)
# ------------------------------
rhs_terms = [
    "IT_within",
    "IT_mean_hotel",
    "Risk_z",
    "ITw_x_R",
    "ITb_x_R"
] + CONTROLS_term + [f"C({SEG})", f"C({REGION})", f"C({YEAR})"]

rhs = " + ".join(rhs_terms)

# ------------------------------
# 9) Step 1: Random Intercept
# ------------------------------
m1 = smf.mixedlm(
    f"{Y} ~ {rhs}",
    data=d,
    groups=d[ID],
    re_formula="1"
)
res1 = m1.fit(method="lbfgs", reml=True)
print(res1.summary())

# ------------------------------
# 10) Step 2: Random Intercept + Random Slope (IT_within)
# ------------------------------
m2 = smf.mixedlm(
    f"{Y} ~ {rhs}",
    data=d,
    groups=d[ID],
    re_formula="1 + IT_within"
)

try:
    res2 = m2.fit(method="lbfgs", reml=True)
except Exception as e1:
    print("LBFGS failed, trying Powell. Error:", e1)
    res2 = m2.fit(method="powell", reml=True)

print(res2.summary())

print("\nModel Comparison:")
print(f"  Log-Likelihood (RI)    : {res1.llf:.2f}")
print(f"  Log-Likelihood (RI+RS) : {res2.llf:.2f}")

PCA weights (events, damage): [[0.70710678 0.70710678]]
Explained variance ratio: [0.96242549]
                     Mixed Linear Model Regression Results
===============================================================================
Model:                     MixedLM        Dependent Variable:        RevPar_log
No. Observations:          70867          Method:                    REML
No. Groups:                10228          Scale:                     0.0162
Min. group size:           1              Log-Likelihood:            30044.1006
Max. group size:           18             Converged:                 Yes
Mean group size:           6.9
-------------------------------------------------------------------------------
                                   Coef.  Std.Err.    z     P>|z| [0.025 0.975]
-------------------------------------------------------------------------------
Intercept                           4.505    0.012  383.107 0.000  4.482  4.528
C(ChainSegment)[T.Luxury]           0.069    0.012    5.648 0.000  0.045  0.093
C(ChainSegment)[T.Midscale]         0.016    0.011    1.425 0.154 -0.006  0.037
C(ChainSegment)[T.Upper Midscale]   0.026    0.011    2.459 0.014  0.005  0.047
C(ChainSegment)[T.Upper Upscale]    0.035    0.011    3.115 0.002  0.013  0.058
C(ChainSegment)[T.Upscale]          0.049    0.011    4.525 0.000  0.028  0.070
C(noaa_region9)[T.Midwest]         -0.084    0.008  -10.459 0.000 -0.100 -0.068
C(noaa_region9)[T.Northeast]        0.055    0.008    7.076 0.000  0.040  0.070
C(noaa_region9)[T.Northern Plains] -0.098    0.018   -5.570 0.000 -0.132 -0.064
C(noaa_region9)[T.Northwest]        0.006    0.013    0.461 0.645 -0.020  0.032
C(noaa_region9)[T.Pacific]          0.230    0.023   10.043 0.000  0.185  0.275
C(noaa_region9)[T.South]           -0.026    0.008   -3.203 0.001 -0.042 -0.010
C(noaa_region9)[T.Southwest]       -0.025    0.011   -2.394 0.017 -0.046 -0.005
C(noaa_region9)[T.West]             0.109    0.009   12.225 0.000  0.092  0.127
C(Year)[T.2008]                    -0.016    0.004   -4.364 0.000 -0.023 -0.009
C(Year)[T.2009]                    -0.095    0.004  -25.004 0.000 -0.102 -0.087
C(Year)[T.2010]                    -0.064    0.004  -18.224 0.000 -0.071 -0.057
C(Year)[T.2011]                    -0.038    0.003  -11.215 0.000 -0.044 -0.031
C(Year)[T.2012]                    -0.011    0.003   -3.326 0.001 -0.018 -0.005
C(Year)[T.2013]                     0.023    0.003    6.839 0.000  0.017  0.030
C(Year)[T.2014]                     0.025    0.004    7.080 0.000  0.018  0.032
C(Year)[T.2015]                     0.014    0.003    4.021 0.000  0.007  0.021
C(Year)[T.2016]                     0.010    0.004    2.920 0.003  0.003  0.017
C(Year)[T.2017]                     0.009    0.004    2.612 0.009  0.002  0.016
C(Year)[T.2018]                    -0.007    0.004   -2.023 0.043 -0.015 -0.000
C(Year)[T.2019]                    -0.022    0.004   -5.899 0.000 -0.030 -0.015
C(Year)[T.2020]                    -0.339    0.004  -84.176 0.000 -0.346 -0.331
C(Year)[T.2021]                    -0.090    0.004  -23.308 0.000 -0.098 -0.083
C(Year)[T.2022]                    -0.013    0.004   -3.368 0.001 -0.021 -0.006
C(Year)[T.2023]                    -0.014    0.004   -3.446 0.001 -0.022 -0.006
C(Year)[T.2024]                    -0.016    0.004   -3.812 0.000 -0.024 -0.008
IT_within                           0.008    0.001   13.888 0.000  0.007  0.010
IT_mean_hotel                      -0.015    0.004   -4.050 0.000 -0.023 -0.008
Risk_z                              0.004    0.001    5.163 0.000  0.003  0.006
ITw_x_R                             0.003    0.001    4.622 0.000  0.001  0.004
ITb_x_R                            -0.004    0.001   -5.654 0.000 -0.006 -0.003
tr_TotalLabor                       0.322    0.005   62.921 0.000  0.312  0.332
tr_MaintTotalExp                   -0.011    0.003   -3.392 0.001 -0.018 -0.005
tr_UtilTotalExp                     0.009    0.002    3.957 0.000  0.004  0.013
tr_Insurance                       -0.006    0.001   -5.300 0.000 -0.009 -0.004
tr_SandMTotalExpense                0.331    0.003  119.777 0.000  0.326  0.337
tr_MktingTotalExp                  -0.028    0.002  -16.854 0.000 -0.032 -0.025
tr_TotalMgmtFee                     0.217    0.002  126.373 0.000  0.214  0.221
tr_PropertyTax                      0.001    0.001    1.256 0.209 -0.001  0.003
tr_Rooms                           -0.533    0.004 -136.355 0.000 -0.541 -0.526
age                                -0.002    0.000  -13.563 0.000 -0.002 -0.001
Group Var                           0.059    0.009
===============================================================================

/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)

                     Mixed Linear Model Regression Results
===============================================================================
Model:                     MixedLM        Dependent Variable:        RevPar_log
No. Observations:          70867          Method:                    REML
No. Groups:                10228          Scale:                     0.0141
Min. group size:           1              Log-Likelihood:            31321.6405
Max. group size:           18             Converged:                 Yes
Mean group size:           6.9
-------------------------------------------------------------------------------
                                   Coef.  Std.Err.    z     P>|z| [0.025 0.975]
-------------------------------------------------------------------------------
Intercept                           4.512    0.012  388.452 0.000  4.490  4.535
C(ChainSegment)[T.Luxury]           0.063    0.012    5.218 0.000  0.040  0.087
C(ChainSegment)[T.Midscale]         0.015    0.011    1.373 0.170 -0.006  0.036
C(ChainSegment)[T.Upper Midscale]   0.018    0.010    1.723 0.085 -0.002  0.038
C(ChainSegment)[T.Upper Upscale]    0.039    0.011    3.448 0.001  0.017  0.061
C(ChainSegment)[T.Upscale]          0.050    0.011    4.705 0.000  0.029  0.070
C(noaa_region9)[T.Midwest]         -0.087    0.008  -10.809 0.000 -0.103 -0.071
C(noaa_region9)[T.Northeast]        0.051    0.008    6.499 0.000  0.035  0.066
C(noaa_region9)[T.Northern Plains] -0.101    0.018   -5.756 0.000 -0.136 -0.067
C(noaa_region9)[T.Northwest]        0.004    0.013    0.324 0.746 -0.022  0.030
C(noaa_region9)[T.Pacific]          0.227    0.023    9.899 0.000  0.182  0.272
C(noaa_region9)[T.South]           -0.033    0.008   -4.007 0.000 -0.049 -0.017
C(noaa_region9)[T.Southwest]       -0.027    0.011   -2.571 0.010 -0.048 -0.006
C(noaa_region9)[T.West]             0.109    0.009   12.229 0.000  0.092  0.127
C(Year)[T.2008]                    -0.018    0.003   -5.271 0.000 -0.025 -0.012
C(Year)[T.2009]                    -0.093    0.004  -25.561 0.000 -0.100 -0.086
C(Year)[T.2010]                    -0.066    0.003  -19.330 0.000 -0.072 -0.059
C(Year)[T.2011]                    -0.039    0.003  -12.068 0.000 -0.046 -0.033
C(Year)[T.2012]                    -0.011    0.003   -3.347 0.001 -0.017 -0.005
C(Year)[T.2013]                     0.024    0.003    7.194 0.000  0.018  0.031
C(Year)[T.2014]                     0.022    0.003    6.344 0.000  0.015  0.029
C(Year)[T.2015]                     0.007    0.003    1.997 0.046  0.000  0.014
C(Year)[T.2016]                     0.004    0.003    1.081 0.280 -0.003  0.011
C(Year)[T.2017]                     0.004    0.004    1.088 0.277 -0.003  0.011
C(Year)[T.2018]                    -0.013    0.004   -3.493 0.000 -0.020 -0.006
C(Year)[T.2019]                    -0.024    0.004   -6.533 0.000 -0.032 -0.017
C(Year)[T.2020]                    -0.336    0.004  -84.183 0.000 -0.343 -0.328
C(Year)[T.2021]                    -0.090    0.004  -23.308 0.000 -0.097 -0.082
C(Year)[T.2022]                    -0.015    0.004   -3.950 0.000 -0.023 -0.008
C(Year)[T.2023]                    -0.018    0.004   -4.465 0.000 -0.026 -0.010
C(Year)[T.2024]                    -0.021    0.004   -4.947 0.000 -0.029 -0.013
IT_within                           0.010    0.001    9.105 0.000  0.008  0.012
IT_mean_hotel                      -0.010    0.004   -2.524 0.012 -0.017 -0.002
Risk_z                              0.003    0.001    4.096 0.000  0.002  0.005
ITw_x_R                             0.002    0.001    2.705 0.007  0.001  0.003
ITb_x_R                            -0.005    0.001   -7.625 0.000 -0.007 -0.004
tr_TotalLabor                       0.322    0.005   62.519 0.000  0.312  0.332
tr_MaintTotalExp                   -0.012    0.003   -3.608 0.000 -0.019 -0.006
tr_UtilTotalExp                     0.008    0.002    3.731 0.000  0.004  0.013
tr_Insurance                       -0.005    0.001   -4.495 0.000 -0.008 -0.003
tr_SandMTotalExpense                0.327    0.003  116.831 0.000  0.322  0.333
tr_MktingTotalExp                  -0.027    0.002  -16.027 0.000 -0.031 -0.024
tr_TotalMgmtFee                     0.224    0.002  128.546 0.000  0.221  0.228
tr_PropertyTax                      0.000    0.001    0.578 0.563 -0.001  0.002
tr_Rooms                           -0.539    0.004 -135.741 0.000 -0.546 -0.531
age                                -0.002    0.000  -13.614 0.000 -0.002 -0.001
Group Var                           0.060    0.009
Group x IT_within Cov              -0.003    0.003
IT_within Var                       0.003    0.001
===============================================================================


Model Comparison:
  Log-Likelihood (RI)    : 30044.10
  Log-Likelihood (RI+RS) : 31321.64

In [37]:
#PCA INDEXING FOR TROPICAL RISK

# ===========================================================
# ✅ MixedLM with PCA-based Tropical Risk
#  - Risk = PCA1(log1p(events), log1p(damage))
#  - Risk_z = z-score of PCA score
#  - IT: within/between decomposition (z-scored)
#  - Interactions: IT_within×Risk_z, IT_mean_hotel×Risk_z
#  - FE: ChainSegment, Region9, Year
#  - RE: (1) Random intercept  (2) Random intercept + random slope(IT_within)
# ===========================================================

# ------------------------------
# 0) 안전한 reset_index (ID가 index였을 수 있음)
# ------------------------------
df = df.reset_index()

# ------------------------------
# 1) 변수 설정 / rename
# ------------------------------
ID     = "PropertyID"
REGION = "noaa_region9"
SEG    = "ChainSegment"

if "Year of Data" in df.columns and "Year" not in df.columns:
    df = df.rename(columns={"Year of Data": "Year"})
YEAR = "Year"

Y  = "RevPar_log"
IT = "ITTotalExpense"

# PCA 구성에 사용할 원천 변수(원래 이미 만들어둔 log 변수 사용)
EV_LOG = "Tropical_events_log"
DMG_LOG = "Tropical_damage_log"

CONTROLS = [
    "TotalLabor","MaintTotalExp","UtilTotalExp",
    "Insurance","SandMTotalExpense","MktingTotalExp",
    "TotalMgmtFee","PropertyTax","Rooms","age"
]

# ------------------------------
# 2) 변환 함수 (money vars)
# ------------------------------
def safe_transform(series, use_asinh_if_negative=True):
    s = pd.to_numeric(series, errors="coerce")
    if use_asinh_if_negative and (s.dropna() < 0).any():
        return np.arcsinh(s)
    else:
        return np.log1p(s.clip(lower=0))

money_vars = [
    IT,
    "TotalLabor","MaintTotalExp","UtilTotalExp","Insurance",
    "SandMTotalExpense","MktingTotalExp","TotalMgmtFee",
    "PropertyTax","Rooms"
]

for col in money_vars:
    if col in df.columns and f"tr_{col}" not in df.columns:
        df[f"tr_{col}"] = safe_transform(df[col], use_asinh_if_negative=True)

IT_term = f"tr_{IT}"

# controls term 구성 (age는 그대로)
CONTROLS_term = []
for c in CONTROLS:
    if c == "age":
        CONTROLS_term.append("age")
    elif c in money_vars:
        CONTROLS_term.append(f"tr_{c}")
    else:
        CONTROLS_term.append(c)

# ------------------------------
# 3) 분석용 컬럼 구성 (PCA용 변수 포함)
# ------------------------------
base_cols = [Y, ID, REGION, SEG, YEAR, IT_term, EV_LOG, DMG_LOG] + CONTROLS_term
d = df[base_cols].dropna().copy()

# Year는 int 유지
d[YEAR] = pd.to_numeric(d[YEAR], errors="coerce")
d = d.dropna(subset=[YEAR])
d[YEAR] = d[YEAR].astype(int)

# 카테고리
d[SEG] = d[SEG].astype("category")
d[REGION] = d[REGION].astype("category")

# ------------------------------
# 4) PCA Risk 생성 (샘플 d에서 학습 → d에 부여)
#    - 표준화 후 PCA 추천 (둘의 스케일/분산 차이를 제거)
# ------------------------------
X = d[[EV_LOG, DMG_LOG]].values
X_std = StandardScaler(with_mean=True, with_std=True).fit_transform(X)

pca = PCA(n_components=1, random_state=0)
risk_pca = pca.fit_transform(X_std).ravel()

# 방향성(부호) 정리: 해석 편의를 위해 "events+damage 증가" 방향이 +가 되도록
# (PC는 부호가 임의라서 고정해주는 게 논문에 유리)
if np.corrcoef(risk_pca, d[EV_LOG].values)[0,1] < 0:
    risk_pca = -risk_pca
    pca.components_ = -pca.components_

d["Risk_pca"] = risk_pca

# Risk_z (z-score)
d["Risk_z"] = (d["Risk_pca"] - d["Risk_pca"].mean()) / d["Risk_pca"].std(ddof=0)

print("PCA weights (events, damage):", pca.components_)
print("Explained variance ratio:", pca.explained_variance_ratio_)

# ------------------------------
# 5) IT within / between 분해 + z-score
# ------------------------------
d["IT_mean_hotel"] = d.groupby(ID)[IT_term].transform("mean")
d["IT_within"] = d[IT_term] - d["IT_mean_hotel"]

for col in ["IT_mean_hotel", "IT_within"]:
    d[col] = (d[col] - d[col].mean()) / d[col].std(ddof=0)

# ------------------------------
# 6) Interaction (within/between 각각)
# ------------------------------
d["ITw_x_R"] = d["IT_within"] * d["Risk_z"]
d["ITb_x_R"] = d["IT_mean_hotel"] * d["Risk_z"]

# ------------------------------
# 7) controls 표준화 (age 제외) - 선택(권장)
# ------------------------------
z_cols = [c for c in CONTROLS_term if c != "age"]
for col in z_cols:
    if col in d.columns:
        sd = d[col].std(ddof=0)
        if sd > 0:
            d[col] = (d[col] - d[col].mean()) / sd

# ------------------------------
# 8) MixedLM 식 정의 (FE 포함)
# ------------------------------
rhs_terms = [
    "IT_within",
    "IT_mean_hotel",
    "Risk_z",
    "ITw_x_R",
    "ITb_x_R"
] + CONTROLS_term + [f"C({SEG})", f"C({REGION})", f"C({YEAR})"]

rhs = " + ".join(rhs_terms)

# ------------------------------
# 9) Step 1: Random Intercept
# ------------------------------
m1 = smf.mixedlm(
    f"{Y} ~ {rhs}",
    data=d,
    groups=d[ID],
    re_formula="1"
)
res1 = m1.fit(method="lbfgs", reml=True)
print(res1.summary())

# ------------------------------
# 10) Step 2: Random Intercept + Random Slope (IT_within)
# ------------------------------
m2 = smf.mixedlm(
    f"{Y} ~ {rhs}",
    data=d,
    groups=d[ID],
    re_formula="1 + IT_within"
)

try:
    res2 = m2.fit(method="lbfgs", reml=True)
except Exception as e1:
    print("LBFGS failed, trying Powell. Error:", e1)
    res2 = m2.fit(method="powell", reml=True)

print(res2.summary())

print("\nModel Comparison:")
print(f"  Log-Likelihood (RI)    : {res1.llf:.2f}")
print(f"  Log-Likelihood (RI+RS) : {res2.llf:.2f}")

# ===========================================================
# ✅ Nakagawa R² (prediction-based, random slope 안전 버전)
# ===========================================================

def mixedlm_r2_pred(res):
    """
    Prediction-based Nakagawa R²
    Works for random intercept + random slope models
    """
    m = res.model

    # Fixed effect fitted values (Xβ)
    yhat_fix = m.exog @ res.fe_params.values

    # Full fitted values (Xβ + Zu)
    yhat_full = np.asarray(res.fittedvalues)

    # Random effect contribution (Zu)
    Zu = yhat_full - yhat_fix

    # Variance components
    var_fix   = np.var(yhat_fix, ddof=1)
    var_re    = np.var(Zu, ddof=1)
    var_resid = res.scale

    denom = var_fix + var_re + var_resid

    R2_marginal   = var_fix / denom
    R2_conditional = (var_fix + var_re) / denom

    return {
        "R2_marginal": R2_marginal,
        "R2_conditional": R2_conditional,
        "var_fixed": var_fix,
        "var_random": var_re,
        "var_residual": var_resid
    }

print("\n--- R² (Nakagawa, prediction-based) ---")

r2_res1 = mixedlm_r2_pred(res1)
print("\nRandom Intercept Model:")
for k, v in r2_res1.items():
    print(f"{k}: {v:.4f}")

r2_res2 = mixedlm_r2_pred(res2)
print("\nRandom Intercept + Random Slope Model:")
for k, v in r2_res2.items():
    print(f"{k}: {v:.4f}")

PCA weights (events, damage): [[0.70710678 0.70710678]]
Explained variance ratio: [0.96242549]
                     Mixed Linear Model Regression Results
===============================================================================
Model:                     MixedLM        Dependent Variable:        RevPar_log
No. Observations:          70867          Method:                    REML
No. Groups:                10228          Scale:                     0.0162
Min. group size:           1              Log-Likelihood:            30044.1006
Max. group size:           18             Converged:                 Yes
Mean group size:           6.9
-------------------------------------------------------------------------------
                                   Coef.  Std.Err.    z     P>|z| [0.025 0.975]
-------------------------------------------------------------------------------
Intercept                           4.505    0.012  383.107 0.000  4.482  4.528
C(ChainSegment)[T.Luxury]           0.069    0.012    5.648 0.000  0.045  0.093
C(ChainSegment)[T.Midscale]         0.016    0.011    1.425 0.154 -0.006  0.037
C(ChainSegment)[T.Upper Midscale]   0.026    0.011    2.459 0.014  0.005  0.047
C(ChainSegment)[T.Upper Upscale]    0.035    0.011    3.115 0.002  0.013  0.058
C(ChainSegment)[T.Upscale]          0.049    0.011    4.525 0.000  0.028  0.070
C(noaa_region9)[T.Midwest]         -0.084    0.008  -10.459 0.000 -0.100 -0.068
C(noaa_region9)[T.Northeast]        0.055    0.008    7.076 0.000  0.040  0.070
C(noaa_region9)[T.Northern Plains] -0.098    0.018   -5.570 0.000 -0.132 -0.064
C(noaa_region9)[T.Northwest]        0.006    0.013    0.461 0.645 -0.020  0.032
C(noaa_region9)[T.Pacific]          0.230    0.023   10.043 0.000  0.185  0.275
C(noaa_region9)[T.South]           -0.026    0.008   -3.203 0.001 -0.042 -0.010
C(noaa_region9)[T.Southwest]       -0.025    0.011   -2.394 0.017 -0.046 -0.005
C(noaa_region9)[T.West]             0.109    0.009   12.225 0.000  0.092  0.127
C(Year)[T.2008]                    -0.016    0.004   -4.364 0.000 -0.023 -0.009
C(Year)[T.2009]                    -0.095    0.004  -25.004 0.000 -0.102 -0.087
C(Year)[T.2010]                    -0.064    0.004  -18.224 0.000 -0.071 -0.057
C(Year)[T.2011]                    -0.038    0.003  -11.215 0.000 -0.044 -0.031
C(Year)[T.2012]                    -0.011    0.003   -3.326 0.001 -0.018 -0.005
C(Year)[T.2013]                     0.023    0.003    6.839 0.000  0.017  0.030
C(Year)[T.2014]                     0.025    0.004    7.080 0.000  0.018  0.032
C(Year)[T.2015]                     0.014    0.003    4.021 0.000  0.007  0.021
C(Year)[T.2016]                     0.010    0.004    2.920 0.003  0.003  0.017
C(Year)[T.2017]                     0.009    0.004    2.612 0.009  0.002  0.016
C(Year)[T.2018]                    -0.007    0.004   -2.023 0.043 -0.015 -0.000
C(Year)[T.2019]                    -0.022    0.004   -5.899 0.000 -0.030 -0.015
C(Year)[T.2020]                    -0.339    0.004  -84.176 0.000 -0.346 -0.331
C(Year)[T.2021]                    -0.090    0.004  -23.308 0.000 -0.098 -0.083
C(Year)[T.2022]                    -0.013    0.004   -3.368 0.001 -0.021 -0.006
C(Year)[T.2023]                    -0.014    0.004   -3.446 0.001 -0.022 -0.006
C(Year)[T.2024]                    -0.016    0.004   -3.812 0.000 -0.024 -0.008
IT_within                           0.008    0.001   13.888 0.000  0.007  0.010
IT_mean_hotel                      -0.015    0.004   -4.050 0.000 -0.023 -0.008
Risk_z                              0.004    0.001    5.163 0.000  0.003  0.006
ITw_x_R                             0.003    0.001    4.622 0.000  0.001  0.004
ITb_x_R                            -0.004    0.001   -5.654 0.000 -0.006 -0.003
tr_TotalLabor                       0.322    0.005   62.921 0.000  0.312  0.332
tr_MaintTotalExp                   -0.011    0.003   -3.392 0.001 -0.018 -0.005
tr_UtilTotalExp                     0.009    0.002    3.957 0.000  0.004  0.013
tr_Insurance                       -0.006    0.001   -5.300 0.000 -0.009 -0.004
tr_SandMTotalExpense                0.331    0.003  119.777 0.000  0.326  0.337
tr_MktingTotalExp                  -0.028    0.002  -16.854 0.000 -0.032 -0.025
tr_TotalMgmtFee                     0.217    0.002  126.373 0.000  0.214  0.221
tr_PropertyTax                      0.001    0.001    1.256 0.209 -0.001  0.003
tr_Rooms                           -0.533    0.004 -136.355 0.000 -0.541 -0.526
age                                -0.002    0.000  -13.563 0.000 -0.002 -0.001
Group Var                           0.059    0.009
===============================================================================

/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)

                     Mixed Linear Model Regression Results
===============================================================================
Model:                     MixedLM        Dependent Variable:        RevPar_log
No. Observations:          70867          Method:                    REML
No. Groups:                10228          Scale:                     0.0141
Min. group size:           1              Log-Likelihood:            31321.6405
Max. group size:           18             Converged:                 Yes
Mean group size:           6.9
-------------------------------------------------------------------------------
                                   Coef.  Std.Err.    z     P>|z| [0.025 0.975]
-------------------------------------------------------------------------------
Intercept                           4.512    0.012  388.452 0.000  4.490  4.535
C(ChainSegment)[T.Luxury]           0.063    0.012    5.218 0.000  0.040  0.087
C(ChainSegment)[T.Midscale]         0.015    0.011    1.373 0.170 -0.006  0.036
C(ChainSegment)[T.Upper Midscale]   0.018    0.010    1.723 0.085 -0.002  0.038
C(ChainSegment)[T.Upper Upscale]    0.039    0.011    3.448 0.001  0.017  0.061
C(ChainSegment)[T.Upscale]          0.050    0.011    4.705 0.000  0.029  0.070
C(noaa_region9)[T.Midwest]         -0.087    0.008  -10.809 0.000 -0.103 -0.071
C(noaa_region9)[T.Northeast]        0.051    0.008    6.499 0.000  0.035  0.066
C(noaa_region9)[T.Northern Plains] -0.101    0.018   -5.756 0.000 -0.136 -0.067
C(noaa_region9)[T.Northwest]        0.004    0.013    0.324 0.746 -0.022  0.030
C(noaa_region9)[T.Pacific]          0.227    0.023    9.899 0.000  0.182  0.272
C(noaa_region9)[T.South]           -0.033    0.008   -4.007 0.000 -0.049 -0.017
C(noaa_region9)[T.Southwest]       -0.027    0.011   -2.571 0.010 -0.048 -0.006
C(noaa_region9)[T.West]             0.109    0.009   12.229 0.000  0.092  0.127
C(Year)[T.2008]                    -0.018    0.003   -5.271 0.000 -0.025 -0.012
C(Year)[T.2009]                    -0.093    0.004  -25.561 0.000 -0.100 -0.086
C(Year)[T.2010]                    -0.066    0.003  -19.330 0.000 -0.072 -0.059
C(Year)[T.2011]                    -0.039    0.003  -12.068 0.000 -0.046 -0.033
C(Year)[T.2012]                    -0.011    0.003   -3.347 0.001 -0.017 -0.005
C(Year)[T.2013]                     0.024    0.003    7.194 0.000  0.018  0.031
C(Year)[T.2014]                     0.022    0.003    6.344 0.000  0.015  0.029
C(Year)[T.2015]                     0.007    0.003    1.997 0.046  0.000  0.014
C(Year)[T.2016]                     0.004    0.003    1.081 0.280 -0.003  0.011
C(Year)[T.2017]                     0.004    0.004    1.088 0.277 -0.003  0.011
C(Year)[T.2018]                    -0.013    0.004   -3.493 0.000 -0.020 -0.006
C(Year)[T.2019]                    -0.024    0.004   -6.533 0.000 -0.032 -0.017
C(Year)[T.2020]                    -0.336    0.004  -84.183 0.000 -0.343 -0.328
C(Year)[T.2021]                    -0.090    0.004  -23.308 0.000 -0.097 -0.082
C(Year)[T.2022]                    -0.015    0.004   -3.950 0.000 -0.023 -0.008
C(Year)[T.2023]                    -0.018    0.004   -4.465 0.000 -0.026 -0.010
C(Year)[T.2024]                    -0.021    0.004   -4.947 0.000 -0.029 -0.013
IT_within                           0.010    0.001    9.105 0.000  0.008  0.012
IT_mean_hotel                      -0.010    0.004   -2.524 0.012 -0.017 -0.002
Risk_z                              0.003    0.001    4.096 0.000  0.002  0.005
ITw_x_R                             0.002    0.001    2.705 0.007  0.001  0.003
ITb_x_R                            -0.005    0.001   -7.625 0.000 -0.007 -0.004
tr_TotalLabor                       0.322    0.005   62.519 0.000  0.312  0.332
tr_MaintTotalExp                   -0.012    0.003   -3.608 0.000 -0.019 -0.006
tr_UtilTotalExp                     0.008    0.002    3.731 0.000  0.004  0.013
tr_Insurance                       -0.005    0.001   -4.495 0.000 -0.008 -0.003
tr_SandMTotalExpense                0.327    0.003  116.831 0.000  0.322  0.333
tr_MktingTotalExp                  -0.027    0.002  -16.027 0.000 -0.031 -0.024
tr_TotalMgmtFee                     0.224    0.002  128.546 0.000  0.221  0.228
tr_PropertyTax                      0.000    0.001    0.578 0.563 -0.001  0.002
tr_Rooms                           -0.539    0.004 -135.741 0.000 -0.546 -0.531
age                                -0.002    0.000  -13.614 0.000 -0.002 -0.001
Group Var                           0.060    0.009
Group x IT_within Cov              -0.003    0.003
IT_within Var                       0.003    0.001
===============================================================================


Model Comparison:
  Log-Likelihood (RI)    : 30044.10
  Log-Likelihood (RI+RS) : 31321.64

--- R² (Nakagawa, prediction-based) ---

Random Intercept Model:
R2_marginal: 0.8266
R2_conditional: 0.9448
var_fixed: 0.2432
var_random: 0.0348
var_residual: 0.0162

Random Intercept + Random Slope Model:
R2_marginal: 0.8303
R2_conditional: 0.9527
var_fixed: 0.2481
var_random: 0.0366
var_residual: 0.0141

In [43]:
#PCA INDEXING FOR FIRE RISK

# ===========================================================
# ✅ MixedLM with PCA-based Tropical Risk
#  - Risk = PCA1(log1p(events), log1p(damage))
#  - Risk_z = z-score of PCA score
#  - IT: within/between decomposition (z-scored)
#  - Interactions: IT_within×Risk_z, IT_mean_hotel×Risk_z
#  - FE: ChainSegment, Region9, Year
#  - RE: (1) Random intercept  (2) Random intercept + random slope(IT_within)
# ===========================================================

# ------------------------------
# 0) 안전한 reset_index (ID가 index였을 수 있음)
# ------------------------------
# Safe reset (한 번만)
df = df.reset_index(drop=True)

# ------------------------------
# 1) 변수 설정 / rename
# ------------------------------
ID     = "PropertyID"
REGION = "noaa_region9"
SEG    = "ChainSegment"

if "Year of Data" in df.columns and "Year" not in df.columns:
    df = df.rename(columns={"Year of Data": "Year"})
YEAR = "Year"

Y  = "RevPar_log"
IT = "ITTotalExpense"

# PCA 구성에 사용할 원천 변수(원래 이미 만들어둔 log 변수 사용)
EV_LOG = "Fire_events_log"
DMG_LOG = "Fire_damage_log"

CONTROLS = [
    "TotalLabor","MaintTotalExp","UtilTotalExp",
    "Insurance","SandMTotalExpense","MktingTotalExp",
    "TotalMgmtFee","PropertyTax","Rooms","age"
]

# ------------------------------
# 2) 변환 함수 (money vars)
# ------------------------------
def safe_transform(series, use_asinh_if_negative=True):
    s = pd.to_numeric(series, errors="coerce")
    if use_asinh_if_negative and (s.dropna() < 0).any():
        return np.arcsinh(s)
    else:
        return np.log1p(s.clip(lower=0))

money_vars = [
    IT,
    "TotalLabor","MaintTotalExp","UtilTotalExp","Insurance",
    "SandMTotalExpense","MktingTotalExp","TotalMgmtFee",
    "PropertyTax","Rooms"
]

for col in money_vars:
    if col in df.columns and f"tr_{col}" not in df.columns:
        df[f"tr_{col}"] = safe_transform(df[col], use_asinh_if_negative=True)

IT_term = f"tr_{IT}"

# controls term 구성 (age는 그대로)
CONTROLS_term = []
for c in CONTROLS:
    if c == "age":
        CONTROLS_term.append("age")
    elif c in money_vars:
        CONTROLS_term.append(f"tr_{c}")
    else:
        CONTROLS_term.append(c)

# ------------------------------
# 3) 분석용 컬럼 구성 (PCA용 변수 포함)
# ------------------------------
base_cols = [Y, ID, REGION, SEG, YEAR, IT_term, EV_LOG, DMG_LOG] + CONTROLS_term
d = df[base_cols].dropna().copy()

# Year는 int 유지
d[YEAR] = pd.to_numeric(d[YEAR], errors="coerce")
d = d.dropna(subset=[YEAR])
d[YEAR] = d[YEAR].astype(int)

# 카테고리
d[SEG] = d[SEG].astype("category")
d[REGION] = d[REGION].astype("category")

# ------------------------------
# 4) PCA Risk 생성 (샘플 d에서 학습 → d에 부여)
#    - 표준화 후 PCA 추천 (둘의 스케일/분산 차이를 제거)
# ------------------------------
X = d[[EV_LOG, DMG_LOG]].values
X_std = StandardScaler(with_mean=True, with_std=True).fit_transform(X)

pca = PCA(n_components=1, random_state=0)
risk_pca = pca.fit_transform(X_std).ravel()

# 방향성(부호) 정리: 해석 편의를 위해 "events+damage 증가" 방향이 +가 되도록
# (PC는 부호가 임의라서 고정해주는 게 논문에 유리)
if np.corrcoef(risk_pca, d[EV_LOG].values)[0,1] < 0:
    risk_pca = -risk_pca
    pca.components_ = -pca.components_

d["Risk_pca"] = risk_pca

# Risk_z (z-score)
d["Risk_z"] = (d["Risk_pca"] - d["Risk_pca"].mean()) / d["Risk_pca"].std(ddof=0)

print("PCA weights (events, damage):", pca.components_)
print("Explained variance ratio:", pca.explained_variance_ratio_)

# ------------------------------
# 5) IT within / between 분해 + z-score
# ------------------------------
d["IT_mean_hotel"] = d.groupby(ID)[IT_term].transform("mean")
d["IT_within"] = d[IT_term] - d["IT_mean_hotel"]

for col in ["IT_mean_hotel", "IT_within"]:
    d[col] = (d[col] - d[col].mean()) / d[col].std(ddof=0)

# ------------------------------
# 6) Interaction (within/between 각각)
# ------------------------------
d["ITw_x_R"] = d["IT_within"] * d["Risk_z"]
d["ITb_x_R"] = d["IT_mean_hotel"] * d["Risk_z"]

# ------------------------------
# 7) controls 표준화 (age 제외) - 선택(권장)
# ------------------------------
z_cols = [c for c in CONTROLS_term if c != "age"]
for col in z_cols:
    if col in d.columns:
        sd = d[col].std(ddof=0)
        if sd > 0:
            d[col] = (d[col] - d[col].mean()) / sd

# ------------------------------
# 8) MixedLM 식 정의 (FE 포함)
# ------------------------------
rhs_terms = [
    "IT_within",
    "IT_mean_hotel",
    "Risk_z",
    "ITw_x_R",
    "ITb_x_R"
] + CONTROLS_term + [f"C({SEG})", f"C({REGION})", f"C({YEAR})"]

rhs = " + ".join(rhs_terms)

# ------------------------------
# 9) Step 1: Random Intercept
# ------------------------------
m1 = smf.mixedlm(
    f"{Y} ~ {rhs}",
    data=d,
    groups=d[ID],
    re_formula="1"
)
res1 = m1.fit(method="lbfgs", reml=True)
print(res1.summary())

# ------------------------------
# 10) Step 2: Random Intercept + Random Slope (IT_within)
# ------------------------------
m2 = smf.mixedlm(
    f"{Y} ~ {rhs}",
    data=d,
    groups=d[ID],
    re_formula="1 + IT_within"
)

try:
    res2 = m2.fit(method="lbfgs", reml=True)
except Exception as e1:
    print("LBFGS failed, trying Powell. Error:", e1)
    res2 = m2.fit(method="powell", reml=True)

print(res2.summary())

print("\nModel Comparison:")
print(f"  Log-Likelihood (RI)    : {res1.llf:.2f}")
print(f"  Log-Likelihood (RI+RS) : {res2.llf:.2f}")

# ===========================================================
# ✅ Nakagawa R² (prediction-based, random slope 안전 버전)
# ===========================================================

def mixedlm_r2_pred(res):
    """
    Prediction-based Nakagawa R²
    Works for random intercept + random slope models
    """
    m = res.model

    # Fixed effect fitted values (Xβ)
    yhat_fix = m.exog @ res.fe_params.values

    # Full fitted values (Xβ + Zu)
    yhat_full = np.asarray(res.fittedvalues)

    # Random effect contribution (Zu)
    Zu = yhat_full - yhat_fix

    # Variance components
    var_fix   = np.var(yhat_fix, ddof=1)
    var_re    = np.var(Zu, ddof=1)
    var_resid = res.scale

    denom = var_fix + var_re + var_resid

    R2_marginal   = var_fix / denom
    R2_conditional = (var_fix + var_re) / denom

    return {
        "R2_marginal": R2_marginal,
        "R2_conditional": R2_conditional,
        "var_fixed": var_fix,
        "var_random": var_re,
        "var_residual": var_resid
    }

print("\n--- R² (Nakagawa, prediction-based) ---")

r2_res1 = mixedlm_r2_pred(res1)
print("\nRandom Intercept Model:")
for k, v in r2_res1.items():
    print(f"{k}: {v:.4f}")

r2_res2 = mixedlm_r2_pred(res2)
print("\nRandom Intercept + Random Slope Model:")
for k, v in r2_res2.items():
    print(f"{k}: {v:.4f}")

PCA weights (events, damage): [[0.70710678 0.70710678]]
Explained variance ratio: [0.912226]
                     Mixed Linear Model Regression Results
===============================================================================
Model:                     MixedLM        Dependent Variable:        RevPar_log
No. Observations:          70867          Method:                    REML
No. Groups:                10228          Scale:                     0.0162
Min. group size:           1              Log-Likelihood:            30032.4067
Max. group size:           18             Converged:                 Yes
Mean group size:           6.9
-------------------------------------------------------------------------------
                                   Coef.  Std.Err.    z     P>|z| [0.025 0.975]
-------------------------------------------------------------------------------
Intercept                           4.508    0.012  383.739 0.000  4.485  4.531
C(ChainSegment)[T.Luxury]           0.070    0.012    5.752 0.000  0.046  0.094
C(ChainSegment)[T.Midscale]         0.018    0.011    1.613 0.107 -0.004  0.039
C(ChainSegment)[T.Upper Midscale]   0.028    0.011    2.663 0.008  0.007  0.049
C(ChainSegment)[T.Upper Upscale]    0.037    0.011    3.220 0.001  0.014  0.059
C(ChainSegment)[T.Upscale]          0.050    0.011    4.691 0.000  0.029  0.071
C(noaa_region9)[T.Midwest]         -0.089    0.008  -11.213 0.000 -0.105 -0.074
C(noaa_region9)[T.Northeast]        0.050    0.008    6.420 0.000  0.034  0.065
C(noaa_region9)[T.Northern Plains] -0.104    0.018   -5.926 0.000 -0.138 -0.070
C(noaa_region9)[T.Northwest]       -0.001    0.013   -0.084 0.933 -0.027  0.025
C(noaa_region9)[T.Pacific]          0.225    0.023    9.821 0.000  0.180  0.270
C(noaa_region9)[T.South]           -0.030    0.008   -3.625 0.000 -0.047 -0.014
C(noaa_region9)[T.Southwest]       -0.032    0.011   -3.055 0.002 -0.053 -0.012
C(noaa_region9)[T.West]             0.103    0.009   11.457 0.000  0.086  0.121
C(Year)[T.2008]                    -0.014    0.004   -3.781 0.000 -0.021 -0.007
C(Year)[T.2009]                    -0.095    0.004  -25.227 0.000 -0.103 -0.088
C(Year)[T.2010]                    -0.065    0.004  -18.305 0.000 -0.071 -0.058
C(Year)[T.2011]                    -0.038    0.003  -11.330 0.000 -0.045 -0.032
C(Year)[T.2012]                    -0.012    0.003   -3.479 0.001 -0.018 -0.005
C(Year)[T.2013]                     0.022    0.003    6.508 0.000  0.016  0.029
C(Year)[T.2014]                     0.024    0.004    6.654 0.000  0.017  0.031
C(Year)[T.2015]                     0.013    0.004    3.665 0.000  0.006  0.020
C(Year)[T.2016]                     0.010    0.004    2.959 0.003  0.004  0.017
C(Year)[T.2017]                     0.011    0.004    3.011 0.003  0.004  0.018
C(Year)[T.2018]                    -0.008    0.004   -2.215 0.027 -0.015 -0.001
C(Year)[T.2019]                    -0.023    0.004   -6.010 0.000 -0.030 -0.015
C(Year)[T.2020]                    -0.335    0.004  -84.069 0.000 -0.343 -0.327
C(Year)[T.2021]                    -0.089    0.004  -22.981 0.000 -0.097 -0.081
C(Year)[T.2022]                    -0.014    0.004   -3.563 0.000 -0.022 -0.006
C(Year)[T.2023]                    -0.013    0.004   -3.293 0.001 -0.021 -0.005
C(Year)[T.2024]                    -0.015    0.004   -3.470 0.001 -0.023 -0.006
IT_within                           0.008    0.001   13.944 0.000  0.007  0.010
IT_mean_hotel                      -0.015    0.004   -3.993 0.000 -0.023 -0.008
Risk_z                              0.001    0.001    0.692 0.489 -0.001  0.003
ITw_x_R                             0.002    0.000    4.396 0.000  0.001  0.003
ITb_x_R                            -0.007    0.001   -7.009 0.000 -0.009 -0.005
tr_TotalLabor                       0.321    0.005   62.787 0.000  0.311  0.331
tr_MaintTotalExp                   -0.011    0.003   -3.345 0.001 -0.018 -0.005
tr_UtilTotalExp                     0.008    0.002    3.734 0.000  0.004  0.012
tr_Insurance                       -0.006    0.001   -5.133 0.000 -0.009 -0.004
tr_SandMTotalExpense                0.332    0.003  119.934 0.000  0.326  0.337
tr_MktingTotalExp                  -0.028    0.002  -16.777 0.000 -0.032 -0.025
tr_TotalMgmtFee                     0.218    0.002  126.933 0.000  0.215  0.221
tr_PropertyTax                      0.001    0.001    1.142 0.254 -0.001  0.003
tr_Rooms                           -0.533    0.004 -136.292 0.000 -0.541 -0.526
age                                -0.002    0.000  -13.658 0.000 -0.002 -0.001
Group Var                           0.059    0.009
===============================================================================

/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)

                     Mixed Linear Model Regression Results
===============================================================================
Model:                     MixedLM        Dependent Variable:        RevPar_log
No. Observations:          70867          Method:                    REML
No. Groups:                10228          Scale:                     0.0141
Min. group size:           1              Log-Likelihood:            31310.5614
Max. group size:           18             Converged:                 Yes
Mean group size:           6.9
-------------------------------------------------------------------------------
                                   Coef.  Std.Err.    z     P>|z| [0.025 0.975]
-------------------------------------------------------------------------------
Intercept                           4.515    0.012  388.856 0.000  4.492  4.538
C(ChainSegment)[T.Luxury]           0.065    0.012    5.325 0.000  0.041  0.089
C(ChainSegment)[T.Midscale]         0.017    0.011    1.558 0.119 -0.004  0.038
C(ChainSegment)[T.Upper Midscale]   0.020    0.010    1.911 0.056 -0.001  0.040
C(ChainSegment)[T.Upper Upscale]    0.040    0.011    3.534 0.000  0.018  0.062
C(ChainSegment)[T.Upscale]          0.051    0.011    4.853 0.000  0.031  0.072
C(noaa_region9)[T.Midwest]         -0.092    0.008  -11.511 0.000 -0.108 -0.076
C(noaa_region9)[T.Northeast]        0.046    0.008    5.899 0.000  0.031  0.061
C(noaa_region9)[T.Northern Plains] -0.107    0.018   -6.116 0.000 -0.142 -0.073
C(noaa_region9)[T.Northwest]       -0.003    0.013   -0.205 0.838 -0.029  0.023
C(noaa_region9)[T.Pacific]          0.222    0.023    9.677 0.000  0.177  0.267
C(noaa_region9)[T.South]           -0.037    0.008   -4.401 0.000 -0.053 -0.020
C(noaa_region9)[T.Southwest]       -0.034    0.011   -3.208 0.001 -0.055 -0.013
C(noaa_region9)[T.West]             0.103    0.009   11.429 0.000  0.086  0.121
C(Year)[T.2008]                    -0.016    0.003   -4.760 0.000 -0.023 -0.010
C(Year)[T.2009]                    -0.093    0.004  -25.744 0.000 -0.100 -0.086
C(Year)[T.2010]                    -0.066    0.003  -19.417 0.000 -0.073 -0.059
C(Year)[T.2011]                    -0.040    0.003  -12.110 0.000 -0.046 -0.033
C(Year)[T.2012]                    -0.011    0.003   -3.300 0.001 -0.017 -0.004
C(Year)[T.2013]                     0.023    0.003    6.953 0.000  0.017  0.030
C(Year)[T.2014]                     0.021    0.003    6.068 0.000  0.014  0.028
C(Year)[T.2015]                     0.006    0.003    1.777 0.076 -0.001  0.013
C(Year)[T.2016]                     0.004    0.004    1.156 0.248 -0.003  0.011
C(Year)[T.2017]                     0.005    0.004    1.510 0.131 -0.002  0.012
C(Year)[T.2018]                    -0.013    0.004   -3.556 0.000 -0.020 -0.006
C(Year)[T.2019]                    -0.025    0.004   -6.563 0.000 -0.032 -0.017
C(Year)[T.2020]                    -0.333    0.004  -84.208 0.000 -0.340 -0.325
C(Year)[T.2021]                    -0.088    0.004  -22.985 0.000 -0.096 -0.081
C(Year)[T.2022]                    -0.016    0.004   -4.060 0.000 -0.024 -0.008
C(Year)[T.2023]                    -0.017    0.004   -4.327 0.000 -0.025 -0.010
C(Year)[T.2024]                    -0.020    0.004   -4.664 0.000 -0.028 -0.011
IT_within                           0.010    0.001    9.145 0.000  0.008  0.012
IT_mean_hotel                      -0.010    0.004   -2.613 0.009 -0.018 -0.003
Risk_z                              0.000    0.001    0.097 0.923 -0.002  0.002
ITw_x_R                             0.003    0.001    3.618 0.000  0.001  0.004
ITb_x_R                            -0.007    0.001   -7.294 0.000 -0.009 -0.005
tr_TotalLabor                       0.322    0.005   62.527 0.000  0.312  0.332
tr_MaintTotalExp                   -0.012    0.003   -3.610 0.000 -0.019 -0.006
tr_UtilTotalExp                     0.008    0.002    3.750 0.000  0.004  0.013
tr_Insurance                       -0.005    0.001   -4.429 0.000 -0.008 -0.003
tr_SandMTotalExpense                0.328    0.003  116.861 0.000  0.322  0.333
tr_MktingTotalExp                  -0.027    0.002  -15.825 0.000 -0.030 -0.024
tr_TotalMgmtFee                     0.225    0.002  128.896 0.000  0.221  0.228
tr_PropertyTax                      0.000    0.001    0.488 0.626 -0.001  0.002
tr_Rooms                           -0.539    0.004 -135.676 0.000 -0.546 -0.531
age                                -0.002    0.000  -13.765 0.000 -0.002 -0.001
Group Var                           0.060    0.009
Group x IT_within Cov              -0.003    0.003
IT_within Var                       0.003    0.001
===============================================================================


Model Comparison:
  Log-Likelihood (RI)    : 30032.41
  Log-Likelihood (RI+RS) : 31310.56

--- R² (Nakagawa, prediction-based) ---

Random Intercept Model:
R2_marginal: 0.8270
R2_conditional: 0.9447
var_fixed: 0.2430
var_random: 0.0346
var_residual: 0.0162

Random Intercept + Random Slope Model:
R2_marginal: 0.8307
R2_conditional: 0.9526
var_fixed: 0.2478
var_random: 0.0364
var_residual: 0.0141

In [45]:
#3 IT variables - PCA risk, Tropical

# ------------------------------
# Utility: prediction-based Nakagawa R²
# ------------------------------
def mixedlm_r2_pred(res):
    m = res.model
    yhat_fix = m.exog @ res.fe_params.values
    yhat_full = np.asarray(res.fittedvalues)
    Zu = yhat_full - yhat_fix

    var_fix = np.var(yhat_fix, ddof=1)
    var_re  = np.var(Zu, ddof=1)
    var_res = res.scale

    denom = var_fix + var_re + var_res
    return {
        "R2_marginal": var_fix / denom,
        "R2_conditional": (var_fix + var_re) / denom,
        "var_fixed": var_fix,
        "var_random": var_re,
        "var_residual": var_res,
    }

# ------------------------------
# Utility: AR(1) by group
# ------------------------------
def ar1_by_property(data, id_col, year_col, resid):
    tmp = data[[id_col, year_col]].copy()
    tmp["resid"] = resid

    def ar1_group(g):
        g = g.sort_values(year_col)
        if len(g) > 2:
            return g["resid"].autocorr(lag=1)
        return np.nan

    return tmp.groupby(id_col).apply(ar1_group)

# ===========================================================
# 0) Safe: reset_index는 drop=True (중복 level_0 방지)
# ===========================================================
df = df.copy()
df = df.reset_index(drop=True)

# ===========================================================
# 1) 변수 설정 (너 환경에 맞춰 이미 정의돼있다고 가정)
# ===========================================================
# 필수: 아래 변수들은 이미 너 노트북에 정의돼 있어야 함
# Y, ID, REGION, SEG, YEAR, CONTROLS_term
# 예시:
# Y="RevPar_log"; ID="PropertyID"; REGION="noaa_region9"; SEG="ChainSegment"; YEAR="Year"

# IT log 변수
IT_LAB = "ITTotalLabor_log"
IT_SER = "ITService_log"
IT_SYS = "ITSystem_log"

# PCA risk source
EV_LOG  = "Tropical_events_log"
DMG_LOG = "Tropical_damage_log"

# -----------------------------------------------------------
# 2) 분석 샘플 구축 (PCA risk 포함)
# -----------------------------------------------------------
base_cols = [Y, ID, REGION, SEG, YEAR, IT_LAB, IT_SER, IT_SYS, EV_LOG, DMG_LOG] + CONTROLS_term
d2 = df[base_cols].dropna().copy()

d2[YEAR] = pd.to_numeric(d2[YEAR], errors="coerce")
d2 = d2.dropna(subset=[YEAR])
d2[YEAR] = d2[YEAR].astype(int)

d2[SEG] = d2[SEG].astype("category")
d2[REGION] = d2[REGION].astype("category")

# -----------------------------------------------------------
# 3) PCA Risk 생성 (표준화 후 PCA + 부호 고정)
# -----------------------------------------------------------
X = d2[[EV_LOG, DMG_LOG]].values
X_std = StandardScaler(with_mean=True, with_std=True).fit_transform(X)

pca = PCA(n_components=1, random_state=0)
risk_pca = pca.fit_transform(X_std).ravel()

if np.corrcoef(risk_pca, d2[EV_LOG].values)[0, 1] < 0:
    risk_pca = -risk_pca
    pca.components_ = -pca.components_

d2["Risk_pca"] = risk_pca
d2["Risk_z"] = (d2["Risk_pca"] - d2["Risk_pca"].mean()) / d2["Risk_pca"].std(ddof=0)

print("PCA weights (events, damage):", pca.components_)
print("Explained variance ratio:", pca.explained_variance_ratio_)

# -----------------------------------------------------------
# 4) IT within/between 분해 + z-score
# -----------------------------------------------------------
def decompose_it(data, var, group=ID):
    data[f"{var}_mean_hotel"] = data.groupby(group)[var].transform("mean")
    data[f"{var}_within"] = data[var] - data[f"{var}_mean_hotel"]
    for col in [f"{var}_mean_hotel", f"{var}_within"]:
        sd = data[col].std(ddof=0)
        if sd > 0:
            data[col] = (data[col] - data[col].mean()) / sd
    return data

for it_var in [IT_LAB, IT_SER, IT_SYS]:
    d2 = decompose_it(d2, it_var)

# interactions
for it_var in [IT_LAB, IT_SER, IT_SYS]:
    d2[f"{it_var}_w_x_R"] = d2[f"{it_var}_within"] * d2["Risk_z"]
    d2[f"{it_var}_b_x_R"] = d2[f"{it_var}_mean_hotel"] * d2["Risk_z"]

# controls standardize (age 제외를 원하면 여기서 처리)
for col in [c for c in CONTROLS_term if c != "age"]:
    if col in d2.columns:
        sd = d2[col].std(ddof=0)
        if sd > 0:
            d2[col] = (d2[col] - d2[col].mean()) / sd

# -----------------------------------------------------------
# 5) Formula 구성
# -----------------------------------------------------------
rhs_terms = ["Risk_z"]
for it_var in [IT_LAB, IT_SER, IT_SYS]:
    rhs_terms += [
        f"{it_var}_within",
        f"{it_var}_mean_hotel",
        f"{it_var}_w_x_R",
        f"{it_var}_b_x_R",
    ]
rhs_terms += CONTROLS_term + [f"C({SEG})", f"C({REGION})", f"C({YEAR})"]
rhs = " + ".join(rhs_terms)
formula = f"{Y} ~ {rhs}"

# ===========================================================
# 6) 모델 적합: (A) REML for inference (B) ML for comparison
# ===========================================================

def fit_models(reml=True):
    # Model 1: Random Intercept
    m1 = smf.mixedlm(formula, data=d2, groups=d2[ID], re_formula="1")
    res1 = m1.fit(method="lbfgs", reml=reml)

    # Model 2: Random Intercept + Random Slope (IT labor within)
    slope_var = f"{IT_LAB}_within"
    m2 = smf.mixedlm(formula, data=d2, groups=d2[ID], re_formula=f"1 + {slope_var}")
    try:
        res2 = m2.fit(method="lbfgs", reml=reml)
    except Exception:
        res2 = m2.fit(method="powell", reml=reml)

    return res1, res2

# (A) REML results (계수 해석용)
res1_reml, res2_reml = fit_models(reml=True)
print("\n===== REML: Model 1 (RI) =====")
print(res1_reml.summary())
print("\n===== REML: Model 2 (RI+RS) =====")
print(res2_reml.summary())

# (B) ML results (모델 비교용)
res1_ml, res2_ml = fit_models(reml=False)

print("\n===== MODEL COMPARISON (ML) =====")
print(f"LogLik RI     : {res1_ml.llf:.2f}")
print(f"LogLik RI+RS  : {res2_ml.llf:.2f}")
print(f"AIC   RI      : {res1_ml.aic:.2f}")
print(f"AIC   RI+RS   : {res2_ml.aic:.2f}")

# Likelihood Ratio Test (approx)
lr = 2 * (res2_ml.llf - res1_ml.llf)
df_diff = len(res2_ml.params) - len(res1_ml.params)
p_lr = chi2.sf(lr, df=df_diff) if df_diff > 0 else np.nan
print(f"LRT statistic : {lr:.2f} (df={df_diff}), p={p_lr:.4g}")

# ===========================================================
# 7) Diagnostics: R² / AR(1) / Ljung-Box (REML 기준)
# ===========================================================
def diagnostics(label, res):
    print(f"\n--- Diagnostics: {label} ---")

    # R²
    r2 = mixedlm_r2_pred(res)
    print("R² (Nakagawa, pred-based):")
    print({k: round(v, 4) for k, v in r2.items()})

    # AR(1)
    ar1 = ar1_by_property(d2, ID, YEAR, res.resid)
    print("\nAR(1) by Property:")
    print(ar1.describe())

    # Ljung–Box (pooled)
    print("\nLjung–Box (pooled residuals):")
    lb = acorr_ljungbox(pd.Series(res.resid).dropna(), lags=[1,2,3,4], return_df=True)
    print(lb)

diagnostics("Model 1 (RI, REML)", res1_reml)
diagnostics("Model 2 (RI+RS, REML)", res2_reml)

PCA weights (events, damage): [[0.70710678 0.70710678]]
Explained variance ratio: [0.96580768]

/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)

===== REML: Model 1 (RI) =====
                    Mixed Linear Model Regression Results
==============================================================================
Model:                    MixedLM        Dependent Variable:        RevPar_log
No. Observations:         4695           Method:                    REML
No. Groups:               2262           Scale:                     0.0183
Min. group size:          1              Log-Likelihood:            54.9137
Max. group size:          10             Converged:                 Yes
Mean group size:          2.1
------------------------------------------------------------------------------
                                   Coef.  Std.Err.    z    P>|z| [0.025 0.975]
------------------------------------------------------------------------------
Intercept                           4.402    0.050  87.938 0.000  4.304  4.500
C(ChainSegment)[T.Luxury]           0.447    0.051   8.773 0.000  0.347  0.547
C(ChainSegment)[T.Midscale]         0.407    0.056   7.233 0.000  0.297  0.517
C(ChainSegment)[T.Upper Midscale]   0.273    0.046   5.892 0.000  0.182  0.364
C(ChainSegment)[T.Upper Upscale]    0.306    0.048   6.366 0.000  0.212  0.401
C(ChainSegment)[T.Upscale]          0.303    0.046   6.550 0.000  0.212  0.393
C(noaa_region9)[T.Midwest]         -0.111    0.025  -4.364 0.000 -0.161 -0.061
C(noaa_region9)[T.Northeast]        0.046    0.023   1.991 0.047  0.001  0.092
C(noaa_region9)[T.Northern Plains] -0.161    0.053  -3.060 0.002 -0.265 -0.058
C(noaa_region9)[T.Northwest]       -0.028    0.035  -0.803 0.422 -0.098  0.041
C(noaa_region9)[T.Pacific]          0.277    0.058   4.749 0.000  0.162  0.391
C(noaa_region9)[T.South]           -0.108    0.023  -4.770 0.000 -0.153 -0.064
C(noaa_region9)[T.Southwest]       -0.046    0.031  -1.483 0.138 -0.108  0.015
C(noaa_region9)[T.West]             0.116    0.026   4.511 0.000  0.065  0.166
C(Year)[T.2016]                     0.010    0.013   0.751 0.453 -0.016  0.035
C(Year)[T.2017]                     0.019    0.014   1.390 0.164 -0.008  0.046
C(Year)[T.2018]                     0.025    0.014   1.804 0.071 -0.002  0.052
C(Year)[T.2019]                     0.020    0.014   1.409 0.159 -0.008  0.048
C(Year)[T.2020]                    -0.356    0.018 -19.812 0.000 -0.392 -0.321
C(Year)[T.2021]                    -0.004    0.016  -0.281 0.779 -0.035  0.027
C(Year)[T.2022]                     0.044    0.015   2.993 0.003  0.015  0.072
C(Year)[T.2023]                     0.053    0.015   3.541 0.000  0.024  0.082
C(Year)[T.2024]                     0.046    0.016   2.996 0.003  0.016  0.077
Risk_z                              0.015    0.005   2.825 0.005  0.004  0.025
ITTotalLabor_log_within             0.010    0.002   4.585 0.000  0.006  0.014
ITTotalLabor_log_mean_hotel         0.067    0.010   6.859 0.000  0.048  0.087
ITTotalLabor_log_w_x_R             -0.004    0.002  -1.817 0.069 -0.008  0.000
ITTotalLabor_log_b_x_R              0.005    0.008   0.603 0.546 -0.011  0.020
ITService_log_within                0.002    0.002   0.894 0.371 -0.002  0.006
ITService_log_mean_hotel           -0.138    0.010 -14.409 0.000 -0.157 -0.119
ITService_log_w_x_R                 0.001    0.002   0.648 0.517 -0.003  0.005
ITService_log_b_x_R                -0.009    0.006  -1.435 0.151 -0.022  0.003
ITSystem_log_within                 0.006    0.002   2.675 0.007  0.002  0.010
ITSystem_log_mean_hotel            -0.085    0.014  -5.877 0.000 -0.113 -0.057
ITSystem_log_w_x_R                 -0.001    0.002  -0.674 0.500 -0.006  0.003
ITSystem_log_b_x_R                 -0.028    0.007  -3.856 0.000 -0.043 -0.014
tr_TotalLabor                       0.270    0.028   9.632 0.000  0.215  0.325
tr_MaintTotalExp                   -0.049    0.019  -2.543 0.011 -0.088 -0.011
tr_UtilTotalExp                    -0.034    0.010  -3.545 0.000 -0.053 -0.015
tr_Insurance                       -0.009    0.006  -1.394 0.163 -0.022  0.004
tr_SandMTotalExpense                0.299    0.017  17.796 0.000  0.266  0.332
tr_MktingTotalExp                  -0.016    0.012  -1.333 0.183 -0.040  0.008
tr_TotalMgmtFee                     0.344    0.010  33.463 0.000  0.324  0.364
tr_PropertyTax                     -0.001    0.006  -0.196 0.845 -0.012  0.010
tr_Rooms                           -0.427    0.012 -35.537 0.000 -0.451 -0.404
age                                -0.001    0.000  -2.808 0.005 -0.001 -0.000
Group Var                           0.092    0.039
==============================================================================


===== REML: Model 2 (RI+RS) =====
                     Mixed Linear Model Regression Results
===============================================================================
Model:                     MixedLM        Dependent Variable:        RevPar_log
No. Observations:          4695           Method:                    REML
No. Groups:                2262           Scale:                     0.0155
Min. group size:           1              Log-Likelihood:            76.3198
Max. group size:           10             Converged:                 Yes
Mean group size:           2.1
-------------------------------------------------------------------------------
                                    Coef.  Std.Err.    z    P>|z| [0.025 0.975]
-------------------------------------------------------------------------------
Intercept                            4.393    0.050  88.162 0.000  4.295  4.491
C(ChainSegment)[T.Luxury]            0.450    0.051   8.884 0.000  0.350  0.549
C(ChainSegment)[T.Midscale]          0.409    0.056   7.307 0.000  0.299  0.519
C(ChainSegment)[T.Upper Midscale]    0.275    0.046   5.949 0.000  0.185  0.366
C(ChainSegment)[T.Upper Upscale]     0.313    0.048   6.529 0.000  0.219  0.407
C(ChainSegment)[T.Upscale]           0.302    0.046   6.570 0.000  0.212  0.392
C(noaa_region9)[T.Midwest]          -0.111    0.026  -4.353 0.000 -0.161 -0.061
C(noaa_region9)[T.Northeast]         0.045    0.024   1.927 0.054 -0.001  0.091
C(noaa_region9)[T.Northern Plains]  -0.162    0.053  -3.083 0.002 -0.265 -0.059
C(noaa_region9)[T.Northwest]        -0.022    0.036  -0.622 0.534 -0.092  0.048
C(noaa_region9)[T.Pacific]           0.277    0.058   4.753 0.000  0.163  0.391
C(noaa_region9)[T.South]            -0.110    0.023  -4.865 0.000 -0.155 -0.066
C(noaa_region9)[T.Southwest]        -0.044    0.031  -1.405 0.160 -0.105  0.017
C(noaa_region9)[T.West]              0.119    0.026   4.635 0.000  0.069  0.169
C(Year)[T.2016]                      0.012    0.012   0.953 0.341 -0.012  0.036
C(Year)[T.2017]                      0.019    0.013   1.416 0.157 -0.007  0.045
C(Year)[T.2018]                      0.028    0.013   2.084 0.037  0.002  0.054
C(Year)[T.2019]                      0.022    0.014   1.599 0.110 -0.005  0.049
C(Year)[T.2020]                     -0.354    0.018 -20.022 0.000 -0.389 -0.319
C(Year)[T.2021]                      0.001    0.016   0.048 0.962 -0.030  0.031
C(Year)[T.2022]                      0.052    0.014   3.624 0.000  0.024  0.080
C(Year)[T.2023]                      0.061    0.015   4.138 0.000  0.032  0.090
C(Year)[T.2024]                      0.056    0.015   3.687 0.000  0.026  0.086
Risk_z                               0.015    0.005   2.906 0.004  0.005  0.025
ITTotalLabor_log_within              0.015    0.004   3.462 0.001  0.007  0.024
ITTotalLabor_log_mean_hotel          0.067    0.010   6.861 0.000  0.048  0.087
ITTotalLabor_log_w_x_R              -0.009    0.004  -2.412 0.016 -0.017 -0.002
ITTotalLabor_log_b_x_R               0.003    0.008   0.377 0.706 -0.012  0.018
ITService_log_within                -0.001    0.002  -0.274 0.784 -0.005  0.004
ITService_log_mean_hotel            -0.136    0.010 -14.244 0.000 -0.155 -0.118
ITService_log_w_x_R                  0.002    0.002   1.192 0.233 -0.002  0.006
ITService_log_b_x_R                 -0.008    0.006  -1.288 0.198 -0.020  0.004
ITSystem_log_within                  0.005    0.002   2.392 0.017  0.001  0.010
ITSystem_log_mean_hotel             -0.084    0.015  -5.816 0.000 -0.113 -0.056
ITSystem_log_w_x_R                  -0.001    0.002  -0.623 0.533 -0.005  0.003
ITSystem_log_b_x_R                  -0.027    0.007  -3.807 0.000 -0.041 -0.013
tr_TotalLabor                        0.257    0.028   9.129 0.000  0.202  0.313
tr_MaintTotalExp                    -0.047    0.019  -2.460 0.014 -0.085 -0.010
tr_UtilTotalExp                     -0.032    0.009  -3.510 0.000 -0.050 -0.014
tr_Insurance                        -0.011    0.006  -1.742 0.082 -0.023  0.001
tr_SandMTotalExpense                 0.288    0.017  16.972 0.000  0.254  0.321
tr_MktingTotalExp                   -0.009    0.012  -0.774 0.439 -0.033  0.014
tr_TotalMgmtFee                      0.351    0.010  34.010 0.000  0.331  0.371
tr_PropertyTax                       0.001    0.006   0.125 0.901 -0.011  0.012
tr_Rooms                            -0.425    0.012 -35.162 0.000 -0.449 -0.401
age                                 -0.001    0.000  -2.779 0.005 -0.001 -0.000
Group Var                            0.094    0.051
Group x ITTotalLabor_log_within Cov  0.002    0.014
ITTotalLabor_log_within Var          0.003    0.010
===============================================================================

/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)

===== MODEL COMPARISON (ML) =====
LogLik RI     : 228.27
LogLik RI+RS  : 249.00
AIC   RI      : -360.54
AIC   RI+RS   : -397.99
LRT statistic : 41.45 (df=2), p=9.972e-10

--- Diagnostics: Model 1 (RI, REML) ---
R² (Nakagawa, pred-based):
{'R2_marginal': np.float64(0.8038), 'R2_conditional': np.float64(0.9555), 'var_fixed': np.float64(0.3301), 'var_random': np.float64(0.0623), 'var_residual': np.float64(0.0183)}

AR(1) by Property:
count    550.000000
mean       0.054748
std        0.710077
min       -1.000000
25%       -0.523360
50%        0.111263
75%        0.755438
max        1.000000
dtype: float64

Ljung–Box (pooled residuals):
      lb_stat     lb_pvalue
1    8.846065  2.937215e-03
2  130.527331  4.532629e-29
3  201.388193  2.114498e-43
4  221.244727  1.011741e-46

--- Diagnostics: Model 2 (RI+RS, REML) ---
R² (Nakagawa, pred-based):
{'R2_marginal': np.float64(0.8031), 'R2_conditional': np.float64(0.962), 'var_fixed': np.float64(0.3288), 'var_random': np.float64(0.0651), 'var_residual': np.float64(0.0155)}

AR(1) by Property:
count    550.000000
mean       0.006674
std        0.710581
min       -1.000000
25%       -0.600750
50%        0.005505
75%        0.675674
max        1.000000
dtype: float64

Ljung–Box (pooled residuals):
      lb_stat     lb_pvalue
1   11.344953  7.565330e-04
2  136.738793  2.030244e-30
3  207.226129  1.157873e-44
4  227.339792  4.934474e-48

/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1334/554325656.py:44: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return tmp.groupby(id_col).apply(ar1_group)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1334/554325656.py:44: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return tmp.groupby(id_col).apply(ar1_group)

In [47]:
#3 IT variables - PCA risk, FIRE

# ------------------------------
# Utility: prediction-based Nakagawa R²
# ------------------------------
def mixedlm_r2_pred(res):
    m = res.model
    yhat_fix = m.exog @ res.fe_params.values
    yhat_full = np.asarray(res.fittedvalues)
    Zu = yhat_full - yhat_fix

    var_fix = np.var(yhat_fix, ddof=1)
    var_re  = np.var(Zu, ddof=1)
    var_res = res.scale

    denom = var_fix + var_re + var_res
    return {
        "R2_marginal": var_fix / denom,
        "R2_conditional": (var_fix + var_re) / denom,
        "var_fixed": var_fix,
        "var_random": var_re,
        "var_residual": var_res,
    }

# ------------------------------
# Utility: AR(1) by group
# ------------------------------
def ar1_by_property(data, id_col, year_col, resid):
    tmp = data[[id_col, year_col]].copy()
    tmp["resid"] = resid

    def ar1_group(g):
        g = g.sort_values(year_col)
        if len(g) > 2:
            return g["resid"].autocorr(lag=1)
        return np.nan

    return tmp.groupby(id_col).apply(ar1_group)

# ===========================================================
# 0) Safe: reset_index는 drop=True (중복 level_0 방지)
# ===========================================================
df = df.copy()
df = df.reset_index(drop=True)

# ===========================================================
# 1) 변수 설정 (너 환경에 맞춰 이미 정의돼있다고 가정)
# ===========================================================
# 필수: 아래 변수들은 이미 너 노트북에 정의돼 있어야 함
# Y, ID, REGION, SEG, YEAR, CONTROLS_term
# 예시:
# Y="RevPar_log"; ID="PropertyID"; REGION="noaa_region9"; SEG="ChainSegment"; YEAR="Year"

# IT log 변수
IT_LAB = "ITTotalLabor_log"
IT_SER = "ITService_log"
IT_SYS = "ITSystem_log"

# PCA risk source
EV_LOG  = "Fire_events_log"
DMG_LOG = "Fire_damage_log"

# -----------------------------------------------------------
# 2) 분석 샘플 구축 (PCA risk 포함)
# -----------------------------------------------------------
base_cols = [Y, ID, REGION, SEG, YEAR, IT_LAB, IT_SER, IT_SYS, EV_LOG, DMG_LOG] + CONTROLS_term
d2 = df[base_cols].dropna().copy()

d2[YEAR] = pd.to_numeric(d2[YEAR], errors="coerce")
d2 = d2.dropna(subset=[YEAR])
d2[YEAR] = d2[YEAR].astype(int)

d2[SEG] = d2[SEG].astype("category")
d2[REGION] = d2[REGION].astype("category")

# -----------------------------------------------------------
# 3) PCA Risk 생성 (표준화 후 PCA + 부호 고정)
# -----------------------------------------------------------
X = d2[[EV_LOG, DMG_LOG]].values
X_std = StandardScaler(with_mean=True, with_std=True).fit_transform(X)

pca = PCA(n_components=1, random_state=0)
risk_pca = pca.fit_transform(X_std).ravel()

if np.corrcoef(risk_pca, d2[EV_LOG].values)[0, 1] < 0:
    risk_pca = -risk_pca
    pca.components_ = -pca.components_

d2["Risk_pca"] = risk_pca
d2["Risk_z"] = (d2["Risk_pca"] - d2["Risk_pca"].mean()) / d2["Risk_pca"].std(ddof=0)

print("PCA weights (events, damage):", pca.components_)
print("Explained variance ratio:", pca.explained_variance_ratio_)

# -----------------------------------------------------------
# 4) IT within/between 분해 + z-score
# -----------------------------------------------------------
def decompose_it(data, var, group=ID):
    data[f"{var}_mean_hotel"] = data.groupby(group)[var].transform("mean")
    data[f"{var}_within"] = data[var] - data[f"{var}_mean_hotel"]
    for col in [f"{var}_mean_hotel", f"{var}_within"]:
        sd = data[col].std(ddof=0)
        if sd > 0:
            data[col] = (data[col] - data[col].mean()) / sd
    return data

for it_var in [IT_LAB, IT_SER, IT_SYS]:
    d2 = decompose_it(d2, it_var)

# interactions
for it_var in [IT_LAB, IT_SER, IT_SYS]:
    d2[f"{it_var}_w_x_R"] = d2[f"{it_var}_within"] * d2["Risk_z"]
    d2[f"{it_var}_b_x_R"] = d2[f"{it_var}_mean_hotel"] * d2["Risk_z"]

# controls standardize (age 제외를 원하면 여기서 처리)
for col in [c for c in CONTROLS_term if c != "age"]:
    if col in d2.columns:
        sd = d2[col].std(ddof=0)
        if sd > 0:
            d2[col] = (d2[col] - d2[col].mean()) / sd

# -----------------------------------------------------------
# 5) Formula 구성
# -----------------------------------------------------------
rhs_terms = ["Risk_z"]
for it_var in [IT_LAB, IT_SER, IT_SYS]:
    rhs_terms += [
        f"{it_var}_within",
        f"{it_var}_mean_hotel",
        f"{it_var}_w_x_R",
        f"{it_var}_b_x_R",
    ]
rhs_terms += CONTROLS_term + [f"C({SEG})", f"C({REGION})", f"C({YEAR})"]
rhs = " + ".join(rhs_terms)
formula = f"{Y} ~ {rhs}"

# ===========================================================
# 6) 모델 적합: (A) REML for inference (B) ML for comparison
# ===========================================================

def fit_models(reml=True):
    # Model 1: Random Intercept
    m1 = smf.mixedlm(formula, data=d2, groups=d2[ID], re_formula="1")
    res1 = m1.fit(method="lbfgs", reml=reml)

    # Model 2: Random Intercept + Random Slope (IT labor within)
    slope_var = f"{IT_LAB}_within"
    m2 = smf.mixedlm(formula, data=d2, groups=d2[ID], re_formula=f"1 + {slope_var}")
    try:
        res2 = m2.fit(method="lbfgs", reml=reml)
    except Exception:
        res2 = m2.fit(method="powell", reml=reml)

    return res1, res2

# (A) REML results (계수 해석용)
res1_reml, res2_reml = fit_models(reml=True)
print("\n===== REML: Model 1 (RI) =====")
print(res1_reml.summary())
print("\n===== REML: Model 2 (RI+RS) =====")
print(res2_reml.summary())

# (B) ML results (모델 비교용)
res1_ml, res2_ml = fit_models(reml=False)

print("\n===== MODEL COMPARISON (ML) =====")
print(f"LogLik RI     : {res1_ml.llf:.2f}")
print(f"LogLik RI+RS  : {res2_ml.llf:.2f}")
print(f"AIC   RI      : {res1_ml.aic:.2f}")
print(f"AIC   RI+RS   : {res2_ml.aic:.2f}")

# Likelihood Ratio Test (approx)
lr = 2 * (res2_ml.llf - res1_ml.llf)
df_diff = len(res2_ml.params) - len(res1_ml.params)
p_lr = chi2.sf(lr, df=df_diff) if df_diff > 0 else np.nan
print(f"LRT statistic : {lr:.2f} (df={df_diff}), p={p_lr:.4g}")

# ===========================================================
# 7) Diagnostics: R² / AR(1) / Ljung-Box (REML 기준)
# ===========================================================
def diagnostics(label, res):
    print(f"\n--- Diagnostics: {label} ---")

    # R²
    r2 = mixedlm_r2_pred(res)
    print("R² (Nakagawa, pred-based):")
    print({k: round(v, 4) for k, v in r2.items()})

    # AR(1)
    ar1 = ar1_by_property(d2, ID, YEAR, res.resid)
    print("\nAR(1) by Property:")
    print(ar1.describe())

    # Ljung–Box (pooled)
    print("\nLjung–Box (pooled residuals):")
    lb = acorr_ljungbox(pd.Series(res.resid).dropna(), lags=[1,2,3,4], return_df=True)
    print(lb)

diagnostics("Model 1 (RI, REML)", res1_reml)
diagnostics("Model 2 (RI+RS, REML)", res2_reml)

PCA weights (events, damage): [[0.70710678 0.70710678]]
Explained variance ratio: [0.91134629]

/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)

===== REML: Model 1 (RI) =====
                    Mixed Linear Model Regression Results
==============================================================================
Model:                    MixedLM        Dependent Variable:        RevPar_log
No. Observations:         4695           Method:                    REML
No. Groups:               2262           Scale:                     0.0182
Min. group size:          1              Log-Likelihood:            60.9630
Max. group size:          10             Converged:                 Yes
Mean group size:          2.1
------------------------------------------------------------------------------
                                   Coef.  Std.Err.    z    P>|z| [0.025 0.975]
------------------------------------------------------------------------------
Intercept                           4.408    0.050  88.651 0.000  4.311  4.506
C(ChainSegment)[T.Luxury]           0.458    0.051   9.012 0.000  0.358  0.557
C(ChainSegment)[T.Midscale]         0.434    0.056   7.752 0.000  0.324  0.544
C(ChainSegment)[T.Upper Midscale]   0.276    0.046   5.969 0.000  0.186  0.367
C(ChainSegment)[T.Upper Upscale]    0.316    0.048   6.597 0.000  0.222  0.410
C(ChainSegment)[T.Upscale]          0.309    0.046   6.715 0.000  0.219  0.399
C(noaa_region9)[T.Midwest]         -0.145    0.024  -6.115 0.000 -0.191 -0.098
C(noaa_region9)[T.Northeast]        0.030    0.023   1.336 0.182 -0.014  0.075
C(noaa_region9)[T.Northern Plains] -0.213    0.051  -4.127 0.000 -0.313 -0.112
C(noaa_region9)[T.Northwest]       -0.066    0.035  -1.885 0.059 -0.134  0.003
C(noaa_region9)[T.Pacific]          0.263    0.058   4.558 0.000  0.150  0.376
C(noaa_region9)[T.South]           -0.106    0.024  -4.364 0.000 -0.153 -0.058
C(noaa_region9)[T.Southwest]       -0.091    0.031  -2.902 0.004 -0.152 -0.029
C(noaa_region9)[T.West]             0.072    0.027   2.705 0.007  0.020  0.124
C(Year)[T.2016]                     0.010    0.013   0.763 0.445 -0.015  0.035
C(Year)[T.2017]                     0.022    0.014   1.646 0.100 -0.004  0.049
C(Year)[T.2018]                     0.028    0.014   2.011 0.044  0.001  0.055
C(Year)[T.2019]                     0.023    0.014   1.630 0.103 -0.005  0.051
C(Year)[T.2020]                    -0.337    0.017 -19.450 0.000 -0.371 -0.303
C(Year)[T.2021]                     0.005    0.016   0.330 0.741 -0.025  0.036
C(Year)[T.2022]                     0.045    0.014   3.077 0.002  0.016  0.073
C(Year)[T.2023]                     0.055    0.015   3.689 0.000  0.026  0.083
C(Year)[T.2024]                     0.044    0.015   2.882 0.004  0.014  0.074
Risk_z                              0.009    0.006   1.415 0.157 -0.003  0.020
ITTotalLabor_log_within             0.012    0.002   5.318 0.000  0.007  0.016
ITTotalLabor_log_mean_hotel         0.075    0.010   7.570 0.000  0.055  0.094
ITTotalLabor_log_w_x_R             -0.008    0.002  -3.850 0.000 -0.011 -0.004
ITTotalLabor_log_b_x_R             -0.012    0.008  -1.647 0.100 -0.027  0.002
ITService_log_within                0.002    0.002   1.072 0.284 -0.002  0.006
ITService_log_mean_hotel           -0.147    0.009 -15.854 0.000 -0.166 -0.129
ITService_log_w_x_R                -0.003    0.002  -1.363 0.173 -0.007  0.001
ITService_log_b_x_R                 0.051    0.007   7.093 0.000  0.037  0.065
ITSystem_log_within                 0.006    0.002   2.750 0.006  0.002  0.010
ITSystem_log_mean_hotel            -0.093    0.014  -6.427 0.000 -0.121 -0.065
ITSystem_log_w_x_R                  0.004    0.002   2.086 0.037  0.000  0.008
ITSystem_log_b_x_R                 -0.026    0.008  -3.081 0.002 -0.042 -0.009
tr_TotalLabor                       0.266    0.028   9.525 0.000  0.212  0.321
tr_MaintTotalExp                   -0.048    0.019  -2.460 0.014 -0.086 -0.010
tr_UtilTotalExp                    -0.036    0.010  -3.771 0.000 -0.055 -0.017
tr_Insurance                       -0.008    0.006  -1.249 0.212 -0.021  0.005
tr_SandMTotalExpense                0.304    0.017  18.140 0.000  0.271  0.337
tr_MktingTotalExp                  -0.014    0.012  -1.177 0.239 -0.038  0.009
tr_TotalMgmtFee                     0.347    0.010  33.852 0.000  0.327  0.367
tr_PropertyTax                     -0.000    0.006  -0.044 0.965 -0.012  0.011
tr_Rooms                           -0.429    0.012 -35.764 0.000 -0.453 -0.406
age                                -0.001    0.000  -2.725 0.006 -0.001 -0.000
Group Var                           0.092    0.039
==============================================================================


===== REML: Model 2 (RI+RS) =====
                     Mixed Linear Model Regression Results
===============================================================================
Model:                     MixedLM        Dependent Variable:        RevPar_log
No. Observations:          4695           Method:                    REML
No. Groups:                2262           Scale:                     0.0154
Min. group size:           1              Log-Likelihood:            81.4281
Max. group size:           10             Converged:                 Yes
Mean group size:           2.1
-------------------------------------------------------------------------------
                                    Coef.  Std.Err.    z    P>|z| [0.025 0.975]
-------------------------------------------------------------------------------
Intercept                            4.402    0.049  88.986 0.000  4.305  4.499
C(ChainSegment)[T.Luxury]            0.457    0.050   9.051 0.000  0.358  0.556
C(ChainSegment)[T.Midscale]          0.435    0.056   7.808 0.000  0.326  0.544
C(ChainSegment)[T.Upper Midscale]    0.276    0.046   5.988 0.000  0.186  0.367
C(ChainSegment)[T.Upper Upscale]     0.321    0.048   6.720 0.000  0.227  0.415
C(ChainSegment)[T.Upscale]           0.307    0.046   6.707 0.000  0.218  0.397
C(noaa_region9)[T.Midwest]          -0.147    0.024  -6.164 0.000 -0.194 -0.100
C(noaa_region9)[T.Northeast]         0.029    0.023   1.251 0.211 -0.016  0.073
C(noaa_region9)[T.Northern Plains]  -0.216    0.051  -4.201 0.000 -0.317 -0.115
C(noaa_region9)[T.Northwest]        -0.062    0.035  -1.775 0.076 -0.130  0.006
C(noaa_region9)[T.Pacific]           0.261    0.058   4.510 0.000  0.147  0.374
C(noaa_region9)[T.South]            -0.108    0.024  -4.473 0.000 -0.156 -0.061
C(noaa_region9)[T.Southwest]        -0.091    0.031  -2.916 0.004 -0.152 -0.030
C(noaa_region9)[T.West]              0.071    0.027   2.652 0.008  0.018  0.123
C(Year)[T.2016]                      0.011    0.012   0.931 0.352 -0.012  0.035
C(Year)[T.2017]                      0.022    0.013   1.654 0.098 -0.004  0.047
C(Year)[T.2018]                      0.031    0.013   2.348 0.019  0.005  0.058
C(Year)[T.2019]                      0.025    0.014   1.874 0.061 -0.001  0.052
C(Year)[T.2020]                     -0.334    0.017 -19.608 0.000 -0.368 -0.301
C(Year)[T.2021]                      0.010    0.015   0.668 0.504 -0.020  0.041
C(Year)[T.2022]                      0.054    0.014   3.767 0.000  0.026  0.082
C(Year)[T.2023]                      0.064    0.015   4.361 0.000  0.035  0.092
C(Year)[T.2024]                      0.054    0.015   3.605 0.000  0.025  0.084
Risk_z                               0.009    0.006   1.514 0.130 -0.003  0.021
ITTotalLabor_log_within              0.016    0.004   3.708 0.000  0.008  0.025
ITTotalLabor_log_mean_hotel          0.074    0.010   7.527 0.000  0.055  0.093
ITTotalLabor_log_w_x_R              -0.013    0.004  -3.382 0.001 -0.021 -0.005
ITTotalLabor_log_b_x_R              -0.013    0.008  -1.665 0.096 -0.027  0.002
ITService_log_within                -0.000    0.002  -0.117 0.907 -0.004  0.004
ITService_log_mean_hotel            -0.145    0.009 -15.608 0.000 -0.164 -0.127
ITService_log_w_x_R                 -0.004    0.002  -2.007 0.045 -0.008 -0.000
ITService_log_b_x_R                  0.049    0.007   6.854 0.000  0.035  0.063
ITSystem_log_within                  0.005    0.002   2.426 0.015  0.001  0.010
ITSystem_log_mean_hotel             -0.093    0.015  -6.388 0.000 -0.121 -0.064
ITSystem_log_w_x_R                   0.006    0.002   2.781 0.005  0.002  0.010
ITSystem_log_b_x_R                  -0.023    0.008  -2.736 0.006 -0.039 -0.006
tr_TotalLabor                        0.254    0.028   9.026 0.000  0.199  0.310
tr_MaintTotalExp                    -0.045    0.019  -2.373 0.018 -0.083 -0.008
tr_UtilTotalExp                     -0.034    0.009  -3.663 0.000 -0.052 -0.016
tr_Insurance                        -0.011    0.006  -1.691 0.091 -0.023  0.002
tr_SandMTotalExpense                 0.292    0.017  17.245 0.000  0.259  0.325
tr_MktingTotalExp                   -0.006    0.012  -0.482 0.630 -0.030  0.018
tr_TotalMgmtFee                      0.354    0.010  34.450 0.000  0.334  0.374
tr_PropertyTax                       0.002    0.006   0.288 0.773 -0.010  0.013
tr_Rooms                            -0.428    0.012 -35.356 0.000 -0.451 -0.404
age                                 -0.001    0.000  -2.719 0.007 -0.001 -0.000
Group Var                            0.094    0.051
Group x ITTotalLabor_log_within Cov  0.002    0.015
ITTotalLabor_log_within Var          0.003    0.011
===============================================================================

/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)

===== MODEL COMPARISON (ML) =====
LogLik RI     : 234.11
LogLik RI+RS  : 253.68
AIC   RI      : -372.22
AIC   RI+RS   : -407.36
LRT statistic : 39.15 (df=2), p=3.16e-09

--- Diagnostics: Model 1 (RI, REML) ---
R² (Nakagawa, pred-based):
{'R2_marginal': np.float64(0.8047), 'R2_conditional': np.float64(0.9557), 'var_fixed': np.float64(0.3308), 'var_random': np.float64(0.0621), 'var_residual': np.float64(0.0182)}

AR(1) by Property:
count    550.000000
mean       0.072547
std        0.705172
min       -1.000000
25%       -0.504890
50%        0.139762
75%        0.734669
max        1.000000
dtype: float64

Ljung–Box (pooled residuals):
      lb_stat     lb_pvalue
1    8.096283  4.435613e-03
2  131.336842  3.023897e-29
3  204.238297  5.120790e-44
4  226.744844  6.626803e-48

--- Diagnostics: Model 2 (RI+RS, REML) ---
R² (Nakagawa, pred-based):
{'R2_marginal': np.float64(0.8039), 'R2_conditional': np.float64(0.9623), 'var_fixed': np.float64(0.3292), 'var_random': np.float64(0.0649), 'var_residual': np.float64(0.0154)}

AR(1) by Property:
count    550.000000
mean       0.030526
std        0.704363
min       -1.000000
25%       -0.563856
50%        0.042549
75%        0.683645
max        1.000000
dtype: float64

Ljung–Box (pooled residuals):
      lb_stat     lb_pvalue
1   10.481766  1.205584e-03
2  139.227591  5.849419e-31
3  211.371607  1.471439e-45
4  234.056015  1.767531e-49

/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1334/365632791.py:38: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return tmp.groupby(id_col).apply(ar1_group)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1334/365632791.py:38: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return tmp.groupby(id_col).apply(ar1_group)

In [ ]:
# 1️⃣ log return 생성
df["RevPar_return"] = df.groupby(ID)["RevPar_log"].diff()

# 2️⃣ 5년 rolling std
df["RevPar_vol_5y"] = (
    df.groupby(ID)["RevPar_return"]
      .rolling(window=5, min_periods=3)
      .std()
      .reset_index(level=0, drop=True)
)

In [47]:
#Robustness check

import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.stats.diagnostic import acorr_ljungbox

try:
    from linearmodels.panel import PanelOLS
    PANEL_OK = True
except ImportError:
    PANEL_OK = False
    print("linearmodels is not installed. Panel FE robustness will be skipped.")

# -------------------------------------------------
# BASIC SETTINGS
# -------------------------------------------------
df = df.reset_index(drop=True)

ID     = "PropertyID"
REGION = "noaa_region9"
SEG    = "ChainSegment"

if "Year of Data" in df.columns and "Year" not in df.columns:
    df = df.rename(columns={"Year of Data": "Year"})
YEAR = "Year"

Y = "RevPar_log"

CONTROLS = [
    "TotalLabor", "MaintTotalExp", "UtilTotalExp",
    "Insurance", "SandMTotalExpense", "MktingTotalExp",
    "TotalMgmtFee", "PropertyTax", "Rooms", "age"
]

money_vars = [
    "ITTotalExpense", "ITTotalLabor", "ITService", "ITSystem",
    "TotalLabor", "MaintTotalExp", "UtilTotalExp",
    "Insurance", "SandMTotalExpense", "MktingTotalExp",
    "TotalMgmtFee", "PropertyTax", "Rooms"
]

def safe_transform(series, use_asinh_if_negative=True):
    s = pd.to_numeric(series, errors="coerce")
    if use_asinh_if_negative and (s.dropna() < 0).any():
        return np.arcsinh(s)
    else:
        return np.log1p(s.clip(lower=0))

def zscore_safe(series):
    s = pd.to_numeric(series, errors="coerce")
    sd = s.std(skipna=True, ddof=0)
    if pd.notnull(sd) and sd > 0:
        return (s - s.mean()) / sd
    return s

# transformed vars
for col in money_vars:
    if col in df.columns and f"tr_{col}" not in df.columns:
        df[f"tr_{col}"] = safe_transform(df[col], use_asinh_if_negative=True)

CONTROLS_term = []
for c in CONTROLS:
    if c == "age":
        CONTROLS_term.append("age")
    else:
        CONTROLS_term.append(f"tr_{c}")

def make_pca_risk(df, event_col, damage_col, out_col):
    tmp = df[[event_col, damage_col]].dropna().copy()
    X_std = StandardScaler().fit_transform(tmp[[event_col, damage_col]].values)

    pca = PCA(n_components=1, random_state=0)
    pc1 = pca.fit_transform(X_std).ravel()

    if np.corrcoef(pc1, tmp[event_col].values)[0, 1] < 0:
        pc1 = -pc1
        pca.components_ = -pca.components_

    df[out_col] = np.nan
    df.loc[tmp.index, out_col] = pc1
    df[out_col] = zscore_safe(df[out_col])

    print(f"\n{out_col}")
    print("PCA weights:", pca.components_)
    print("Explained variance ratio:", pca.explained_variance_ratio_)
    return df

if "Tropical_events_log" in df.columns and "Tropical_damage_log" in df.columns and "Tropical_Risk_z" not in df.columns:
    df = make_pca_risk(df, "Tropical_events_log", "Tropical_damage_log", "Tropical_Risk_z")

if "Fire_events_log" in df.columns and "Fire_damage_log" in df.columns and "Fire_Risk_z" not in df.columns:
    df = make_pca_risk(df, "Fire_events_log", "Fire_damage_log", "Fire_Risk_z")

def prepare_panel(df):
    d = df.copy()

    # defensive rename
    if "Year" not in d.columns and "Year of Data" in d.columns:
        d = d.rename(columns={"Year of Data": "Year"})

    if "Year" not in d.columns:
        raise KeyError(
            f"'Year' column not found. Available columns similar to year: "
            f"{[c for c in d.columns if 'year' in c.lower()]}"
        )

    d["Year"] = pd.to_numeric(d["Year"], errors="coerce")
    d = d.dropna(subset=[ID, "Year"])
    d["Year"] = d["Year"].astype(int)
    return d

def add_lagged_structure(df, it_col, risk_col, lag=1, standardize=True):
    d = df.copy().sort_values([ID, YEAR])

    lag_col = f"lag_{it_col}"
    d[lag_col] = d.groupby(ID)[it_col].shift(lag)

    mean_col = f"{lag_col}_mean_hotel"
    d[mean_col] = d.groupby(ID)[lag_col].transform("mean")

    within_col = f"{lag_col}_within"
    d[within_col] = d[lag_col] - d[mean_col]

    risk_mean_col = f"{risk_col}_mean_hotel"
    risk_within_col = f"{risk_col}_within_hotel"
    d[risk_mean_col] = d.groupby(ID)[risk_col].transform("mean")
    d[risk_within_col] = d[risk_col] - d[risk_mean_col]

    if standardize:
        for c in [lag_col, mean_col, within_col, risk_col, risk_mean_col, risk_within_col]:
            if c in d.columns:
                d[c] = zscore_safe(d[c])

    w_int = f"{lag_col}_w_x_R"
    b_int = f"{lag_col}_b_x_Rw"
    d[w_int] = d[within_col] * d[risk_col]
    d[b_int] = d[mean_col] * d[risk_within_col]

    names = {
        "lag_col": lag_col,
        "mean_col": mean_col,
        "within_col": within_col,
        "risk_mean_col": risk_mean_col,
        "risk_within_col": risk_within_col,
        "w_int": w_int,
        "b_int": b_int
    }
    return d, names

def fit_mixedlm_model(df, it_col, risk_col, exclude_2020=False, random_slope=True):
    d = prepare_panel(df)
    if exclude_2020:
        d = d[d[YEAR] != 2020].copy()

    d, names = add_lagged_structure(d, it_col, risk_col, lag=1, standardize=True)

    needed = [
        Y, ID, REGION, SEG, YEAR, risk_col,
        names["mean_col"], names["within_col"],
        names["risk_within_col"], names["w_int"], names["b_int"]
    ] + CONTROLS_term
    d = d.dropna(subset=needed).copy()

    d[SEG] = d[SEG].astype("category")
    d[REGION] = d[REGION].astype("category")
    d[YEAR] = d[YEAR].astype("category")

    rhs = " + ".join(
        [risk_col, names["within_col"], names["mean_col"], names["w_int"], names["b_int"]]
        + CONTROLS_term
        + [f"C({SEG})", f"C({REGION})", f"C({YEAR})"]
    )

    re_formula = "1"
    if random_slope:
        re_formula = f"1 + {names['within_col']}"

    model = smf.mixedlm(f"{Y} ~ {rhs}", data=d, groups=d[ID], re_formula=re_formula)

    try:
        res = model.fit(method="lbfgs", reml=True)
    except Exception:
        res = model.fit(method="powell", reml=True)

    return res, d, names

def fit_panel_fe_cluster(df, it_col, risk_col, exclude_2020=False):
    if not PANEL_OK:
        return None, None, None

    d = prepare_panel(df)
    if exclude_2020:
        d = d[d[YEAR] != 2020].copy()

    d, names = add_lagged_structure(d, it_col, risk_col, lag=1, standardize=True)

    needed = [
        Y, ID, YEAR, risk_col,
        names["mean_col"], names["within_col"],
        names["risk_within_col"], names["w_int"], names["b_int"]
    ] + CONTROLS_term
    d = d.dropna(subset=needed).copy()

    d = pd.get_dummies(d, columns=[REGION, SEG], drop_first=True)
    exog_cols = [risk_col, names["within_col"], names["mean_col"], names["w_int"], names["b_int"]] + CONTROLS_term
    exog_cols += [c for c in d.columns if c.startswith(REGION + "_") or c.startswith(SEG + "_")]

    d = d.set_index([ID, YEAR])

    mod = PanelOLS(
        dependent=d[Y],
        exog=d[exog_cols],
        entity_effects=True,
        time_effects=True,
        drop_absorbed=True
    )
    res = mod.fit(cov_type="clustered", cluster_entity=True)
    return res, d, names

def extract_full_mixed_results(res):
    return pd.DataFrame({
        "term": res.params.index,
        "coef": res.params.values,
        "se": res.bse.values,
        "p": res.pvalues.values
    })

def extract_full_panel_results(res):
    if res is None:
        return pd.DataFrame()
    return pd.DataFrame({
        "term": res.params.index,
        "coef": res.params.values,
        "se": res.std_errors.values,
        "p": res.pvalues.values
    })

def extract_key_terms_mixed(res, names, risk_col, label):
    terms = [risk_col, names["within_col"], names["mean_col"], names["w_int"], names["b_int"]]
    out = []
    for t in terms:
        if t in res.params.index:
            out.append({
                "model": label,
                "term": t,
                "coef": res.params[t],
                "se": res.bse[t],
                "p": res.pvalues[t]
            })
    return pd.DataFrame(out)

def extract_key_terms_panel(res, names, risk_col, label):
    if res is None:
        return pd.DataFrame()
    terms = [risk_col, names["within_col"], names["mean_col"], names["w_int"], names["b_int"]]
    out = []
    for t in terms:
        if t in res.params.index:
            out.append({
                "model": label,
                "term": t,
                "coef": res.params[t],
                "se": res.std_errors[t],
                "p": res.pvalues[t]
            })
    return pd.DataFrame(out)

def pretty_compare(df_coef):
    if df_coef.empty:
        return df_coef
    tmp = df_coef.copy()
    tmp["coef_se"] = tmp.apply(lambda x: f"{x['coef']:.3f} ({x['se']:.3f}), p={x['p']:.3f}", axis=1)
    return tmp.pivot(index="term", columns="model", values="coef_se")

def compute_vif_from_mixedlm_result(res):
    X = pd.DataFrame(res.model.exog, columns=res.model.exog_names)
    rows = []
    for i, col in enumerate(X.columns):
        try:
            vif = variance_inflation_factor(X.values, i)
        except Exception:
            vif = np.nan
        rows.append({"variable": col, "VIF": vif})
    return pd.DataFrame(rows).sort_values("VIF", ascending=False)

def mixedlm_r2_pred(res):
    m = res.model
    yhat_fix = m.exog @ res.fe_params.values
    yhat_full = np.asarray(res.fittedvalues)
    Zu = yhat_full - yhat_fix

    var_fix = np.var(yhat_fix, ddof=1)
    var_re = np.var(Zu, ddof=1)
    var_resid = res.scale
    denom = var_fix + var_re + var_resid

    return pd.DataFrame([{
        "R2_marginal": var_fix / denom,
        "R2_conditional": (var_fix + var_re) / denom,
        "var_fixed": var_fix,
        "var_random": var_re,
        "var_residual": var_resid
    }])

def residual_autocorr_diagnostics(res, data_used):
    dtmp = data_used.copy()
    dtmp["_resid"] = res.resid

    def ar1_group(g):
        g = g.sort_values(YEAR)
        if len(g) > 2:
            return g["_resid"].autocorr(lag=1)
        return np.nan

    ar1_vals = dtmp.groupby(ID).apply(ar1_group).dropna()
    ar1_desc = ar1_vals.describe().to_frame("AR1")

    lb = acorr_ljungbox(dtmp["_resid"].dropna(), lags=[1,2,3,4], return_df=True)
    return ar1_desc, lb

def panel_r2_table(res):
    if res is None:
        return pd.DataFrame()
    return pd.DataFrame([{
        "R2_within": res.rsquared_within,
        "R2_between": res.rsquared_between,
        "R2_overall": res.rsquared_overall
    }])

def build_full_comparison_table(mixed_full_res, mixed_no20_res, panel_res):
    """
    모든 계수를 wide table로 정리
    """
    mf = extract_full_mixed_results(mixed_full_res).copy()
    mf["model"] = "MixedLM_full"

    mn = extract_full_mixed_results(mixed_no20_res).copy()
    mn["model"] = "MixedLM_no2020"

    if panel_res is not None:
        pf = extract_full_panel_results(panel_res).copy()
        pf["model"] = "PanelFE_cluster"
        full_long = pd.concat([mf, mn, pf], ignore_index=True)
    else:
        full_long = pd.concat([mf, mn], ignore_index=True)

    full_long["coef_se_p"] = full_long.apply(
        lambda x: f"{x['coef']:.3f} ({x['se']:.3f}), p={x['p']:.3f}",
        axis=1
    )

    full_wide = full_long.pivot_table(
        index="term",
        columns="model",
        values="coef_se_p",
        aggfunc="first"
    )

    return full_long, full_wide

def build_fit_statistics_table(mixed_full_res, mixed_no20_res, panel_res=None):
    rows = []

    rows.append({
        "model": "MixedLM_full",
        "nobs": getattr(mixed_full_res, "nobs", np.nan),
        "llf": getattr(mixed_full_res, "llf", np.nan),
        "aic": getattr(mixed_full_res, "aic", np.nan),
        "bic": getattr(mixed_full_res, "bic", np.nan)
    })

    rows.append({
        "model": "MixedLM_no2020",
        "nobs": getattr(mixed_no20_res, "nobs", np.nan),
        "llf": getattr(mixed_no20_res, "llf", np.nan),
        "aic": getattr(mixed_no20_res, "aic", np.nan),
        "bic": getattr(mixed_no20_res, "bic", np.nan)
    })

    if panel_res is not None:
        rows.append({
            "model": "PanelFE_cluster",
            "nobs": getattr(panel_res, "nobs", np.nan),
            "llf": np.nan,
            "aic": np.nan,
            "bic": np.nan
        })

    return pd.DataFrame(rows)

def fit_mixedlm_model_ldv(df, it_col, risk_col, exclude_2020=False, random_slope=True):

    d = prepare_panel(df)

    if exclude_2020:
        d = d[d[YEAR] != 2020].copy()

    # lagged dependent variable
    d = d.sort_values([ID, YEAR])
    d["lag_RevPar_log"] = d.groupby(ID)[Y].shift(1)

    d, names = add_lagged_structure(
        d,
        it_col,
        risk_col,
        lag=1,
        standardize=True
    )

    needed = [
        Y,
        "lag_RevPar_log",
        ID,
        REGION,
        SEG,
        YEAR,
        risk_col,
        names["mean_col"],
        names["within_col"],
        names["risk_within_col"],
        names["w_int"],
        names["b_int"]
    ] + CONTROLS_term

    d = d.dropna(subset=needed).copy()

    d[SEG] = d[SEG].astype("category")
    d[REGION] = d[REGION].astype("category")
    d[YEAR] = d[YEAR].astype("category")

    rhs = " + ".join(
        [
            "lag_RevPar_log",
            risk_col,
            names["within_col"],
            names["mean_col"],
            names["w_int"],
            names["b_int"]
        ]
        + CONTROLS_term
        + [
            f"C({SEG})",
            f"C({REGION})",
            f"C({YEAR})"
        ]
    )

    re_formula = "1"

    if random_slope:
        re_formula = f"1 + {names['within_col']}"

    model = smf.mixedlm(
        f"{Y} ~ {rhs}",
        data=d,
        groups=d[ID],
        re_formula=re_formula
    )

    try:
        res = model.fit(method="lbfgs", reml=True)
    except Exception:
        res = model.fit(method="powell", reml=True)

    return res, d, names


def fit_panel_fe_cluster_ldv(df, it_col, risk_col, exclude_2020=False):
    if not PANEL_OK:
        return None, None, None

    # 반드시 먼저 panel data 준비
    d = prepare_panel(df)

    if exclude_2020:
        d = d[d[YEAR] != 2020].copy()

    # lagged dependent variable
    d = d.sort_values([ID, YEAR])
    d["lag_RevPar_log"] = d.groupby(ID)[Y].shift(1)

    # lagged IT structure
    d, names = add_lagged_structure(d, it_col, risk_col, lag=1, standardize=True)

    needed = [
        Y, "lag_RevPar_log", ID, YEAR, risk_col,
        names["mean_col"], names["within_col"],
        names["risk_within_col"], names["w_int"], names["b_int"]
    ] + CONTROLS_term

    d = d.dropna(subset=needed).copy()

    # region / segment 더미화
    d = pd.get_dummies(d, columns=[REGION, SEG], drop_first=True)

    exog_cols = [
        "lag_RevPar_log",
        risk_col,
        names["within_col"],
        names["mean_col"],
        names["w_int"],
        names["b_int"]
    ] + CONTROLS_term

    exog_cols += [
        c for c in d.columns
        if c.startswith(REGION + "_") or c.startswith(SEG + "_")
    ]

    d = d.set_index([ID, YEAR])

    mod = PanelOLS(
        dependent=d[Y],
        exog=d[exog_cols],
        entity_effects=True,
        time_effects=True,
        drop_absorbed=True
    )

    res = mod.fit(cov_type="clustered", cluster_entity=True)

    return res, d, names

def extract_key_terms_mixed_ldv(res, names, risk_col, label):
    terms = [
        "lag_RevPar_log",
        risk_col,
        names["within_col"],
        names["mean_col"],
        names["w_int"],
        names["b_int"]
    ]
    out = []
    for t in terms:
        if t in res.params.index:
            out.append({
                "model": label,
                "term": t,
                "coef": res.params[t],
                "se": res.bse[t],
                "p": res.pvalues[t]
            })
    return pd.DataFrame(out)


def extract_key_terms_panel_ldv(res, names, risk_col, label):
    if res is None:
        return pd.DataFrame()

    terms = [
        "lag_RevPar_log",
        risk_col,
        names["within_col"],
        names["mean_col"],
        names["w_int"],
        names["b_int"]
    ]
    out = []
    for t in terms:
        if t in res.params.index:
            out.append({
                "model": label,
                "term": t,
                "coef": res.params[t],
                "se": res.std_errors[t],
                "p": res.pvalues[t]
            })
    return pd.DataFrame(out)

def add_lagged_structure_multi(df, it_cols, risk_col, lag=1, standardize=True):
    d = df.copy().sort_values([ID, YEAR])

    names = {
        "risk": risk_col,
        "risk_mean": f"{risk_col}_mean_hotel",
        "risk_within": f"{risk_col}_within_hotel",
        "it": {}
    }

    # risk decomposition
    d[names["risk_mean"]] = d.groupby(ID)[risk_col].transform("mean")
    d[names["risk_within"]] = d[risk_col] - d[names["risk_mean"]]

    if standardize:
        d[risk_col] = zscore_safe(d[risk_col])
        d[names["risk_mean"]] = zscore_safe(d[names["risk_mean"]])
        d[names["risk_within"]] = zscore_safe(d[names["risk_within"]])

    # each IT component
    for it_col in it_cols:
        lag_col = f"lag_{it_col}"
        mean_col = f"{lag_col}_mean_hotel"
        within_col = f"{lag_col}_within"
        w_int = f"{lag_col}_w_x_R"
        b_int = f"{lag_col}_b_x_Rw"

        d[lag_col] = d.groupby(ID)[it_col].shift(lag)
        d[mean_col] = d.groupby(ID)[lag_col].transform("mean")
        d[within_col] = d[lag_col] - d[mean_col]

        if standardize:
            d[lag_col] = zscore_safe(d[lag_col])
            d[mean_col] = zscore_safe(d[mean_col])
            d[within_col] = zscore_safe(d[within_col])

        d[w_int] = d[within_col] * d[risk_col]
        d[b_int] = d[mean_col] * d[names["risk_within"]]

        names["it"][it_col] = {
            "lag": lag_col,
            "mean": mean_col,
            "within": within_col,
            "w_int": w_int,
            "b_int": b_int
        }

    return d, names

def fit_mixedlm_joint(df, it_cols, risk_col, exclude_2020=False, random_slope_col=None, add_ldv=False):
    d = prepare_panel(df)

    if exclude_2020:
        d = d[d[YEAR] != 2020].copy()

    if add_ldv:
        d = d.sort_values([ID, YEAR])
        d["lag_RevPar_log"] = d.groupby(ID)[Y].shift(1)

    d, names = add_lagged_structure_multi(d, it_cols, risk_col, lag=1, standardize=True)

    rhs_terms = []
    needed = [Y, ID, REGION, SEG, YEAR, risk_col]

    if add_ldv:
        rhs_terms.append("lag_RevPar_log")
        needed.append("lag_RevPar_log")

    rhs_terms.append(risk_col)

    for it_col in it_cols:
        block = names["it"][it_col]
        rhs_terms += [block["within"], block["mean"], block["w_int"], block["b_int"]]
        needed += [block["within"], block["mean"], block["w_int"], block["b_int"]]

    needed += CONTROLS_term
    rhs_terms += CONTROLS_term
    rhs_terms += [f"C({SEG})", f"C({REGION})", f"C({YEAR})"]

    d = d.dropna(subset=needed).copy()

    d[SEG] = d[SEG].astype("category")
    d[REGION] = d[REGION].astype("category")
    d[YEAR] = d[YEAR].astype("category")

    formula = f"{Y} ~ " + " + ".join(rhs_terms)

    re_formula = "1"
    if random_slope_col is not None:
        re_formula = f"1 + {names['it'][random_slope_col]['within']}"

    model = smf.mixedlm(formula, data=d, groups=d[ID], re_formula=re_formula)

    try:
        res = model.fit(method="lbfgs", reml=True)
    except Exception:
        res = model.fit(method="powell", reml=True)

    return res, d, names


def fit_panel_fe_cluster_joint(df, it_cols, risk_col, exclude_2020=False, add_ldv=False):
    if not PANEL_OK:
        return None, None, None

    d = prepare_panel(df)

    if exclude_2020:
        d = d[d[YEAR] != 2020].copy()

    if add_ldv:
        d = d.sort_values([ID, YEAR])
        d["lag_RevPar_log"] = d.groupby(ID)[Y].shift(1)

    d, names = add_lagged_structure_multi(d, it_cols, risk_col, lag=1, standardize=True)

    needed = [Y, ID, YEAR, risk_col]
    exog_cols = []

    if add_ldv:
        needed.append("lag_RevPar_log")
        exog_cols.append("lag_RevPar_log")

    exog_cols.append(risk_col)

    for it_col in it_cols:
        block = names["it"][it_col]
        exog_cols += [block["within"], block["mean"], block["w_int"], block["b_int"]]
        needed += [block["within"], block["mean"], block["w_int"], block["b_int"]]

    needed += CONTROLS_term
    exog_cols += CONTROLS_term

    d = d.dropna(subset=needed).copy()

    d = pd.get_dummies(d, columns=[REGION, SEG], drop_first=True)
    exog_cols += [c for c in d.columns if c.startswith(REGION + "_") or c.startswith(SEG + "_")]

    d = d.set_index([ID, YEAR])

    mod = PanelOLS(
        dependent=d[Y],
        exog=d[exog_cols],
        entity_effects=True,
        time_effects=True,
        drop_absorbed=True
    )

    res = mod.fit(cov_type="clustered", cluster_entity=True)
    return res, d, names

def extract_key_terms_joint_mixed(res, names, risk_col, label, it_cols, add_ldv=False):
    terms = [risk_col]
    if add_ldv:
        terms.append("lag_RevPar_log")

    for it_col in it_cols:
        block = names["it"][it_col]
        terms += [block["within"], block["mean"], block["w_int"], block["b_int"]]

    out = []
    for t in terms:
        if t in res.params.index:
            out.append({
                "model": label,
                "term": t,
                "coef": res.params[t],
                "se": res.bse[t],
                "p": res.pvalues[t]
            })
    return pd.DataFrame(out)


def extract_key_terms_joint_panel(res, names, risk_col, label, it_cols, add_ldv=False):
    if res is None:
        return pd.DataFrame()

    terms = [risk_col]
    if add_ldv:
        terms.append("lag_RevPar_log")

    for it_col in it_cols:
        block = names["it"][it_col]
        terms += [block["within"], block["mean"], block["w_int"], block["b_int"]]

    out = []
    for t in terms:
        if t in res.params.index:
            out.append({
                "model": label,
                "term": t,
                "coef": res.params[t],
                "se": res.std_errors[t],
                "p": res.pvalues[t]
            })
    return pd.DataFrame(out)

In [44]:
#Tropical + IT total

risk_col = "Tropical_Risk_z"
it_col = "tr_ITTotalExpense"

# -----------------------------
# 기존 3개
# -----------------------------
res_full, d_full, names_full = fit_mixedlm_model(df, it_col, risk_col, exclude_2020=False, random_slope=True)
res_no20, d_no20, names_no20 = fit_mixedlm_model(df, it_col, risk_col, exclude_2020=True, random_slope=True)
res_fe, d_fe, names_fe = fit_panel_fe_cluster(df, it_col, risk_col, exclude_2020=False)

# -----------------------------
# LDV 포함 2개 추가
# -----------------------------
res_full_ldv, d_full_ldv, names_full_ldv = fit_mixedlm_model_ldv(df, it_col, risk_col, exclude_2020=False, random_slope=True)
res_fe_ldv, d_fe_ldv, names_fe_ldv = fit_panel_fe_cluster_ldv(df, it_col, risk_col, exclude_2020=False)

# -----------------------------
# 전체 계수표
# -----------------------------
full_mixed = extract_full_mixed_results(res_full)
full_mixed["model"] = "MixedLM_full"

full_mixed_no20 = extract_full_mixed_results(res_no20)
full_mixed_no20["model"] = "MixedLM_no2020"

full_panel = extract_full_panel_results(res_fe)
full_panel["model"] = "PanelFE_cluster"

full_mixed_ldv = extract_full_mixed_results(res_full_ldv)
full_mixed_ldv["model"] = "MixedLM_full_LDV"

full_panel_ldv = extract_full_panel_results(res_fe_ldv)
full_panel_ldv["model"] = "PanelFE_cluster_LDV"

full_long = pd.concat([
    full_mixed,
    full_mixed_no20,
    full_panel,
    full_mixed_ldv,
    full_panel_ldv
], ignore_index=True)

full_long["coef_se_p"] = full_long.apply(
    lambda x: f"{x['coef']:.3f} ({x['se']:.3f}), p={x['p']:.3f}",
    axis=1
)

full_wide = full_long.pivot_table(
    index="term",
    columns="model",
    values="coef_se_p",
    aggfunc="first"
)

# -----------------------------
# 핵심 계수표
# -----------------------------
key_coef = pd.concat([
    extract_key_terms_mixed(res_full, names_full, risk_col, "MixedLM_full"),
    extract_key_terms_mixed(res_no20, names_no20, risk_col, "MixedLM_no2020"),
    extract_key_terms_panel(res_fe, names_fe, risk_col, "PanelFE_cluster"),
    extract_key_terms_mixed_ldv(res_full_ldv, names_full_ldv, risk_col, "MixedLM_full_LDV"),
    extract_key_terms_panel_ldv(res_fe_ldv, names_fe_ldv, risk_col, "PanelFE_cluster_LDV")
], ignore_index=True)

pretty_key = pretty_compare(key_coef)

# -----------------------------
# 진단
# -----------------------------
vif = compute_vif_from_mixedlm_result(res_full)
vif_ldv = compute_vif_from_mixedlm_result(res_full_ldv)

r2_mixed = mixedlm_r2_pred(res_full)
r2_mixed_no20 = mixedlm_r2_pred(res_no20)
r2_mixed_ldv = mixedlm_r2_pred(res_full_ldv)

r2_panel = panel_r2_table(res_fe)
r2_panel_ldv = panel_r2_table(res_fe_ldv)

ar1_desc, lb_table = residual_autocorr_diagnostics(res_full, d_full)
ar1_desc_ldv, lb_table_ldv = residual_autocorr_diagnostics(res_full_ldv, d_full_ldv)

fit_stats = pd.DataFrame([
    {"model": "MixedLM_full", "nobs": res_full.nobs, "llf": res_full.llf, "aic": res_full.aic, "bic": res_full.bic},
    {"model": "MixedLM_no2020", "nobs": res_no20.nobs, "llf": res_no20.llf, "aic": res_no20.aic, "bic": res_no20.bic},
    {"model": "MixedLM_full_LDV", "nobs": res_full_ldv.nobs, "llf": res_full_ldv.llf, "aic": res_full_ldv.aic, "bic": res_full_ldv.bic},
    {"model": "PanelFE_cluster", "nobs": getattr(res_fe, "nobs", np.nan), "llf": np.nan, "aic": np.nan, "bic": np.nan},
    {"model": "PanelFE_cluster_LDV", "nobs": getattr(res_fe_ldv, "nobs", np.nan), "llf": np.nan, "aic": np.nan, "bic": np.nan},
])

print("\n================ KEY COEFFICIENTS ================")
print(pretty_key)

print("\n================ FIT STATS ================")
print(fit_stats)

print("\n================ VIF (BASE) ================")
print(vif.head(30))

print("\n================ VIF (LDV) ================")
print(vif_ldv.head(30))

print("\n================ R2 BASE ================")
print(r2_mixed)

print("\n================ R2 LDV ================")
print(r2_mixed_ldv)

print("\n================ AR1 BASE ================")
print(ar1_desc)
print(lb_table)

print("\n================ AR1 LDV ================")
print(ar1_desc_ldv)
print(lb_table_ldv)

with pd.ExcelWriter("scenario1_tropical_totalIT_with_LDV.xlsx") as writer:
    full_long.to_excel(writer, sheet_name="full_coef_long", index=False)
    full_wide.to_excel(writer, sheet_name="full_coef_wide")
    key_coef.to_excel(writer, sheet_name="key_coef", index=False)
    pretty_key.to_excel(writer, sheet_name="pretty_key")
    fit_stats.to_excel(writer, sheet_name="fit_stats", index=False)
    vif.to_excel(writer, sheet_name="vif_base", index=False)
    vif_ldv.to_excel(writer, sheet_name="vif_ldv", index=False)
    r2_mixed.to_excel(writer, sheet_name="r2_mixed_base", index=False)
    r2_mixed_no20.to_excel(writer, sheet_name="r2_mixed_no2020", index=False)
    r2_mixed_ldv.to_excel(writer, sheet_name="r2_mixed_ldv", index=False)
    r2_panel.to_excel(writer, sheet_name="r2_panel_base", index=False)
    r2_panel_ldv.to_excel(writer, sheet_name="r2_panel_ldv", index=False)
    ar1_desc.to_excel(writer, sheet_name="ar1_base")
    lb_table.to_excel(writer, sheet_name="ljung_box_base")
    ar1_desc_ldv.to_excel(writer, sheet_name="ar1_ldv")
    lb_table_ldv.to_excel(writer, sheet_name="ljung_box_ldv")

/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/2419301966.py:221: AbsorbingEffectWarning:
Variables have been fully absorbed and have removed from the regression:

lag_tr_ITTotalExpense_mean_hotel, noaa_region9_Midwest, noaa_region9_Northeast, noaa_region9_Northern Plains, noaa_region9_Northwest, noaa_region9_Pacific, noaa_region9_South, noaa_region9_Southwest, noaa_region9_West

  res = mod.fit(cov_type="clustered", cluster_entity=True)
/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/2419301966.py:524: AbsorbingEffectWarning:
Variables have been fully absorbed and have removed from the regression:

lag_tr_ITTotalExpense_mean_hotel, noaa_region9_Midwest, noaa_region9_Northeast, noaa_region9_Northern Plains, noaa_region9_Northwest, noaa_region9_Pacific, noaa_region9_South, noaa_region9_Southwest, noaa_region9_West

  res = mod.fit(cov_type="clustered", cluster_entity=True)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/2419301966.py:319: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ar1_vals = dtmp.groupby(ID).apply(ar1_group).dropna()
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/2419301966.py:319: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ar1_vals = dtmp.groupby(ID).apply(ar1_group).dropna()

================ KEY COEFFICIENTS ================
model                                        MixedLM_full  \
term
Tropical_Risk_z                    0.004 (0.001), p=0.000
lag_RevPar_log                                        NaN
lag_tr_ITTotalExpense_b_x_Rw      -0.002 (0.001), p=0.000
lag_tr_ITTotalExpense_mean_hotel  -0.004 (0.004), p=0.237
lag_tr_ITTotalExpense_w_x_R        0.002 (0.001), p=0.003
lag_tr_ITTotalExpense_within       0.006 (0.001), p=0.000

model                                    MixedLM_full_LDV  \
term
Tropical_Risk_z                    0.004 (0.001), p=0.000
lag_RevPar_log                     0.205 (0.003), p=0.000
lag_tr_ITTotalExpense_b_x_Rw      -0.003 (0.001), p=0.000
lag_tr_ITTotalExpense_mean_hotel  -0.018 (0.003), p=0.000
lag_tr_ITTotalExpense_w_x_R        0.001 (0.001), p=0.065
lag_tr_ITTotalExpense_within      -0.000 (0.001), p=0.705

model                                     MixedLM_no2020  \
term
Tropical_Risk_z                   0.002 (0.001), p=0.001
lag_RevPar_log                                       NaN
lag_tr_ITTotalExpense_b_x_Rw      0.002 (0.000), p=0.000
lag_tr_ITTotalExpense_mean_hotel  0.019 (0.004), p=0.000
lag_tr_ITTotalExpense_w_x_R       0.002 (0.001), p=0.001
lag_tr_ITTotalExpense_within      0.007 (0.001), p=0.000

model                                     PanelFE_cluster  \
term
Tropical_Risk_z                    0.003 (0.001), p=0.000
lag_RevPar_log                                        NaN
lag_tr_ITTotalExpense_b_x_Rw      -0.001 (0.001), p=0.292
lag_tr_ITTotalExpense_mean_hotel                      NaN
lag_tr_ITTotalExpense_w_x_R        0.003 (0.001), p=0.000
lag_tr_ITTotalExpense_within       0.006 (0.001), p=0.000

model                                 PanelFE_cluster_LDV
term
Tropical_Risk_z                    0.003 (0.001), p=0.001
lag_RevPar_log                     0.151 (0.008), p=0.000
lag_tr_ITTotalExpense_b_x_Rw      -0.002 (0.001), p=0.009
lag_tr_ITTotalExpense_mean_hotel                      NaN
lag_tr_ITTotalExpense_w_x_R        0.002 (0.001), p=0.002
lag_tr_ITTotalExpense_within       0.003 (0.001), p=0.002

================ FIT STATS ================
                 model   nobs           llf  aic  bic
0         MixedLM_full  62127  29414.834268  NaN  NaN
1       MixedLM_no2020  57949  32424.439683  NaN  NaN
2     MixedLM_full_LDV  62127  32043.527836  NaN  NaN
3      PanelFE_cluster  62239           NaN  NaN  NaN
4  PanelFE_cluster_LDV  62239           NaN  NaN  NaN

================ VIF (BASE) ================
                             variable          VIF
0                           Intercept  1252.283542
35                      tr_TotalLabor    32.250715
5          C(ChainSegment)[T.Upscale]    25.053266
4    C(ChainSegment)[T.Upper Upscale]    20.155906
3   C(ChainSegment)[T.Upper Midscale]    19.610172
36                   tr_MaintTotalExp    18.973883
1           C(ChainSegment)[T.Luxury]     8.896514
39               tr_SandMTotalExpense     7.544265
43                           tr_Rooms     6.163002
32   lag_tr_ITTotalExpense_mean_hotel     5.455018
37                    tr_UtilTotalExp     5.440007
41                    tr_TotalMgmtFee     5.303656
2         C(ChainSegment)[T.Midscale]     4.493065
40                  tr_MktingTotalExp     4.369821
22                    C(Year)[T.2017]     3.218532
28                    C(Year)[T.2023]     3.081277
23                    C(Year)[T.2018]     3.048792
25                    C(Year)[T.2020]     3.002098
26                    C(Year)[T.2021]     3.000817
21                    C(Year)[T.2016]     2.982361
29                    C(Year)[T.2024]     2.978748
24                    C(Year)[T.2019]     2.977369
27                    C(Year)[T.2022]     2.911233
38                       tr_Insurance     2.873325
20                    C(Year)[T.2015]     2.860647
18                    C(Year)[T.2013]     2.701299
17                    C(Year)[T.2012]     2.642854
19                    C(Year)[T.2014]     2.549455
16                    C(Year)[T.2011]     2.394946
15                    C(Year)[T.2010]     2.256066

================ VIF (LDV) ================
                             variable          VIF
0                           Intercept  1252.855176
36                      tr_TotalLabor    32.465881
5          C(ChainSegment)[T.Upscale]    25.158442
4    C(ChainSegment)[T.Upper Upscale]    20.203842
3   C(ChainSegment)[T.Upper Midscale]    19.657514
37                   tr_MaintTotalExp    19.183701
44                           tr_Rooms     9.255690
1           C(ChainSegment)[T.Luxury]     8.962682
40               tr_SandMTotalExpense     8.454659
42                    tr_TotalMgmtFee     6.038299
33   lag_tr_ITTotalExpense_mean_hotel     5.481355
38                    tr_UtilTotalExp     5.444520
2         C(ChainSegment)[T.Midscale]     4.496938
41                  tr_MktingTotalExp     4.380819
30                     lag_RevPar_log     4.102334
26                    C(Year)[T.2021]     3.222156
22                    C(Year)[T.2017]     3.219685
25                    C(Year)[T.2020]     3.160028
28                    C(Year)[T.2023]     3.084200
23                    C(Year)[T.2018]     3.049378
27                    C(Year)[T.2022]     2.995823
21                    C(Year)[T.2016]     2.983056
29                    C(Year)[T.2024]     2.978775
24                    C(Year)[T.2019]     2.978216
39                       tr_Insurance     2.877432
20                    C(Year)[T.2015]     2.860683
18                    C(Year)[T.2013]     2.701816
17                    C(Year)[T.2012]     2.646778
19                    C(Year)[T.2014]     2.549907
16                    C(Year)[T.2011]     2.401460

================ R2 BASE ================
   R2_marginal  R2_conditional  var_fixed  var_random  var_residual
0     0.849596        0.953388   0.262275    0.032041       0.01439

================ R2 LDV ================
   R2_marginal  R2_conditional  var_fixed  var_random  var_residual
0     0.886513        0.952383   0.266882     0.01983      0.014335

================ AR1 BASE ================
               AR1
count  6992.000000
mean      0.197999
std       0.544179
min      -1.000000
25%      -0.111792
50%       0.280202
75%       0.604696
max       1.000000
       lb_stat  lb_pvalue
1  4248.138801        0.0
2  4250.973632        0.0
3  4771.562177        0.0
4  5923.405601        0.0

================ AR1 LDV ================
               AR1
count  6992.000000
mean      0.081353
std       0.542284
min      -1.000000
25%      -0.255933
50%       0.121753
75%       0.469338
max       1.000000
       lb_stat      lb_pvalue
1   859.385064  6.625927e-189
2   885.226569  5.963386e-193
3  1164.566187  3.573224e-252
4  1760.524639   0.000000e+00

In [45]:
#Fire + IT total

risk_col = "Fire_Risk_z"
it_col   = "tr_ITTotalExpense"

# -----------------------------
# 기존 3개
# -----------------------------
res_full, d_full, names_full = fit_mixedlm_model(df, it_col, risk_col, exclude_2020=False, random_slope=True)
res_no20, d_no20, names_no20 = fit_mixedlm_model(df, it_col, risk_col, exclude_2020=True, random_slope=True)
res_fe, d_fe, names_fe = fit_panel_fe_cluster(df, it_col, risk_col, exclude_2020=False)

# -----------------------------
# LDV 포함 2개 추가
# -----------------------------
res_full_ldv, d_full_ldv, names_full_ldv = fit_mixedlm_model_ldv(df, it_col, risk_col, exclude_2020=False, random_slope=True)
res_fe_ldv, d_fe_ldv, names_fe_ldv = fit_panel_fe_cluster_ldv(df, it_col, risk_col, exclude_2020=False)

# -----------------------------
# 전체 계수표
# -----------------------------
full_mixed = extract_full_mixed_results(res_full)
full_mixed["model"] = "MixedLM_full"

full_mixed_no20 = extract_full_mixed_results(res_no20)
full_mixed_no20["model"] = "MixedLM_no2020"

full_panel = extract_full_panel_results(res_fe)
full_panel["model"] = "PanelFE_cluster"

full_mixed_ldv = extract_full_mixed_results(res_full_ldv)
full_mixed_ldv["model"] = "MixedLM_full_LDV"

full_panel_ldv = extract_full_panel_results(res_fe_ldv)
full_panel_ldv["model"] = "PanelFE_cluster_LDV"

full_long = pd.concat([
    full_mixed,
    full_mixed_no20,
    full_panel,
    full_mixed_ldv,
    full_panel_ldv
], ignore_index=True)

full_long["coef_se_p"] = full_long.apply(
    lambda x: f"{x['coef']:.3f} ({x['se']:.3f}), p={x['p']:.3f}",
    axis=1
)

full_wide = full_long.pivot_table(
    index="term",
    columns="model",
    values="coef_se_p",
    aggfunc="first"
)

# -----------------------------
# 핵심 계수표
# -----------------------------
key_coef = pd.concat([
    extract_key_terms_mixed(res_full, names_full, risk_col, "MixedLM_full"),
    extract_key_terms_mixed(res_no20, names_no20, risk_col, "MixedLM_no2020"),
    extract_key_terms_panel(res_fe, names_fe, risk_col, "PanelFE_cluster"),
    extract_key_terms_mixed_ldv(res_full_ldv, names_full_ldv, risk_col, "MixedLM_full_LDV"),
    extract_key_terms_panel_ldv(res_fe_ldv, names_fe_ldv, risk_col, "PanelFE_cluster_LDV")
], ignore_index=True)

pretty_key = pretty_compare(key_coef)

# -----------------------------
# 진단
# -----------------------------
vif = compute_vif_from_mixedlm_result(res_full)
vif_ldv = compute_vif_from_mixedlm_result(res_full_ldv)

r2_mixed = mixedlm_r2_pred(res_full)
r2_mixed_no20 = mixedlm_r2_pred(res_no20)
r2_mixed_ldv = mixedlm_r2_pred(res_full_ldv)

r2_panel = panel_r2_table(res_fe)
r2_panel_ldv = panel_r2_table(res_fe_ldv)

ar1_desc, lb_table = residual_autocorr_diagnostics(res_full, d_full)
ar1_desc_ldv, lb_table_ldv = residual_autocorr_diagnostics(res_full_ldv, d_full_ldv)

fit_stats = pd.DataFrame([
    {"model": "MixedLM_full", "nobs": res_full.nobs, "llf": res_full.llf, "aic": res_full.aic, "bic": res_full.bic},
    {"model": "MixedLM_no2020", "nobs": res_no20.nobs, "llf": res_no20.llf, "aic": res_no20.aic, "bic": res_no20.bic},
    {"model": "MixedLM_full_LDV", "nobs": res_full_ldv.nobs, "llf": res_full_ldv.llf, "aic": res_full_ldv.aic, "bic": res_full_ldv.bic},
    {"model": "PanelFE_cluster", "nobs": getattr(res_fe, "nobs", np.nan), "llf": np.nan, "aic": np.nan, "bic": np.nan},
    {"model": "PanelFE_cluster_LDV", "nobs": getattr(res_fe_ldv, "nobs", np.nan), "llf": np.nan, "aic": np.nan, "bic": np.nan},
])

print("\n================ KEY COEFFICIENTS ================")
print(pretty_key)

print("\n================ FIT STATS ================")
print(fit_stats)

print("\n================ VIF (BASE) ================")
print(vif.head(30))

print("\n================ VIF (LDV) ================")
print(vif_ldv.head(30))

print("\n================ R2 BASE ================")
print(r2_mixed)

print("\n================ R2 LDV ================")
print(r2_mixed_ldv)

print("\n================ AR1 BASE ================")
print(ar1_desc)
print(lb_table)

print("\n================ AR1 LDV ================")
print(ar1_desc_ldv)
print(lb_table_ldv)

with pd.ExcelWriter("scenario1_tropical_totalIT_with_LDV.xlsx") as writer:
    full_long.to_excel(writer, sheet_name="full_coef_long", index=False)
    full_wide.to_excel(writer, sheet_name="full_coef_wide")
    key_coef.to_excel(writer, sheet_name="key_coef", index=False)
    pretty_key.to_excel(writer, sheet_name="pretty_key")
    fit_stats.to_excel(writer, sheet_name="fit_stats", index=False)
    vif.to_excel(writer, sheet_name="vif_base", index=False)
    vif_ldv.to_excel(writer, sheet_name="vif_ldv", index=False)
    r2_mixed.to_excel(writer, sheet_name="r2_mixed_base", index=False)
    r2_mixed_no20.to_excel(writer, sheet_name="r2_mixed_no2020", index=False)
    r2_mixed_ldv.to_excel(writer, sheet_name="r2_mixed_ldv", index=False)
    r2_panel.to_excel(writer, sheet_name="r2_panel_base", index=False)
    r2_panel_ldv.to_excel(writer, sheet_name="r2_panel_ldv", index=False)
    ar1_desc.to_excel(writer, sheet_name="ar1_base")
    lb_table.to_excel(writer, sheet_name="ljung_box_base")
    ar1_desc_ldv.to_excel(writer, sheet_name="ar1_ldv")
    lb_table_ldv.to_excel(writer, sheet_name="ljung_box_ldv")

/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/2419301966.py:221: AbsorbingEffectWarning:
Variables have been fully absorbed and have removed from the regression:

lag_tr_ITTotalExpense_mean_hotel, noaa_region9_Midwest, noaa_region9_Northeast, noaa_region9_Northern Plains, noaa_region9_Northwest, noaa_region9_Pacific, noaa_region9_South, noaa_region9_Southwest, noaa_region9_West

  res = mod.fit(cov_type="clustered", cluster_entity=True)
/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/2419301966.py:524: AbsorbingEffectWarning:
Variables have been fully absorbed and have removed from the regression:

lag_tr_ITTotalExpense_mean_hotel, noaa_region9_Midwest, noaa_region9_Northeast, noaa_region9_Northern Plains, noaa_region9_Northwest, noaa_region9_Pacific, noaa_region9_South, noaa_region9_Southwest, noaa_region9_West

  res = mod.fit(cov_type="clustered", cluster_entity=True)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/2419301966.py:319: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ar1_vals = dtmp.groupby(ID).apply(ar1_group).dropna()
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/2419301966.py:319: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ar1_vals = dtmp.groupby(ID).apply(ar1_group).dropna()

================ KEY COEFFICIENTS ================
model                                        MixedLM_full  \
term
Fire_Risk_z                        0.000 (0.001), p=0.993
lag_RevPar_log                                        NaN
lag_tr_ITTotalExpense_b_x_Rw      -0.003 (0.001), p=0.000
lag_tr_ITTotalExpense_mean_hotel  -0.005 (0.004), p=0.215
lag_tr_ITTotalExpense_w_x_R        0.002 (0.001), p=0.001
lag_tr_ITTotalExpense_within       0.007 (0.001), p=0.000

model                                    MixedLM_full_LDV  \
term
Fire_Risk_z                        0.001 (0.001), p=0.478
lag_RevPar_log                     0.204 (0.003), p=0.000
lag_tr_ITTotalExpense_b_x_Rw      -0.003 (0.001), p=0.000
lag_tr_ITTotalExpense_mean_hotel  -0.019 (0.003), p=0.000
lag_tr_ITTotalExpense_w_x_R        0.001 (0.001), p=0.306
lag_tr_ITTotalExpense_within      -0.000 (0.001), p=0.874

model                                      MixedLM_no2020  \
term
Fire_Risk_z                        0.001 (0.001), p=0.561
lag_RevPar_log                                        NaN
lag_tr_ITTotalExpense_b_x_Rw      -0.000 (0.000), p=0.779
lag_tr_ITTotalExpense_mean_hotel   0.019 (0.004), p=0.000
lag_tr_ITTotalExpense_w_x_R        0.002 (0.001), p=0.001
lag_tr_ITTotalExpense_within       0.007 (0.001), p=0.000

model                                     PanelFE_cluster  \
term
Fire_Risk_z                       -0.001 (0.001), p=0.375
lag_RevPar_log                                        NaN
lag_tr_ITTotalExpense_b_x_Rw      -0.002 (0.001), p=0.003
lag_tr_ITTotalExpense_mean_hotel                      NaN
lag_tr_ITTotalExpense_w_x_R        0.001 (0.001), p=0.176
lag_tr_ITTotalExpense_within       0.006 (0.001), p=0.000

model                                 PanelFE_cluster_LDV
term
Fire_Risk_z                       -0.001 (0.001), p=0.297
lag_RevPar_log                     0.151 (0.008), p=0.000
lag_tr_ITTotalExpense_b_x_Rw      -0.002 (0.001), p=0.002
lag_tr_ITTotalExpense_mean_hotel                      NaN
lag_tr_ITTotalExpense_w_x_R       -0.000 (0.001), p=0.757
lag_tr_ITTotalExpense_within       0.003 (0.001), p=0.002

================ FIT STATS ================
                 model   nobs           llf  aic  bic
0         MixedLM_full  62127  29414.209983  NaN  NaN
1       MixedLM_no2020  57949  32406.029315  NaN  NaN
2     MixedLM_full_LDV  62127  32024.583835  NaN  NaN
3      PanelFE_cluster  62239           NaN  NaN  NaN
4  PanelFE_cluster_LDV  62239           NaN  NaN  NaN

================ VIF (BASE) ================
                             variable          VIF
0                           Intercept  1253.464759
35                      tr_TotalLabor    32.185853
5          C(ChainSegment)[T.Upscale]    25.057038
4    C(ChainSegment)[T.Upper Upscale]    20.160282
3   C(ChainSegment)[T.Upper Midscale]    19.613178
36                   tr_MaintTotalExp    18.923993
1           C(ChainSegment)[T.Luxury]     8.898385
39               tr_SandMTotalExpense     7.543718
43                           tr_Rooms     6.157795
32   lag_tr_ITTotalExpense_mean_hotel     5.449391
37                    tr_UtilTotalExp     5.441256
41                    tr_TotalMgmtFee     5.285911
2         C(ChainSegment)[T.Midscale]     4.493365
40                  tr_MktingTotalExp     4.369503
22                    C(Year)[T.2017]     3.183197
28                    C(Year)[T.2023]     3.031124
23                    C(Year)[T.2018]     2.975181
25                    C(Year)[T.2020]     2.967807
26                    C(Year)[T.2021]     2.960786
21                    C(Year)[T.2016]     2.934667
29                    C(Year)[T.2024]     2.932999
24                    C(Year)[T.2019]     2.919236
30                        Fire_Risk_z     2.846212
38                       tr_Insurance     2.843843
27                    C(Year)[T.2022]     2.835148
20                    C(Year)[T.2015]     2.754753
18                    C(Year)[T.2013]     2.600282
17                    C(Year)[T.2012]     2.589698
19                    C(Year)[T.2014]     2.426196
16                    C(Year)[T.2011]     2.370249

================ VIF (LDV) ================
                             variable          VIF
0                           Intercept  1253.946126
36                      tr_TotalLabor    32.396230
5          C(ChainSegment)[T.Upscale]    25.163832
4    C(ChainSegment)[T.Upper Upscale]    20.209356
3   C(ChainSegment)[T.Upper Midscale]    19.661243
37                   tr_MaintTotalExp    19.137889
44                           tr_Rooms     9.239093
1           C(ChainSegment)[T.Luxury]     8.965678
40               tr_SandMTotalExpense     8.451014
42                    tr_TotalMgmtFee     6.019780
33   lag_tr_ITTotalExpense_mean_hotel     5.475266
38                    tr_UtilTotalExp     5.446144
2         C(ChainSegment)[T.Midscale]     4.497271
41                  tr_MktingTotalExp     4.380617
30                     lag_RevPar_log     4.099509
22                    C(Year)[T.2017]     3.184410
26                    C(Year)[T.2021]     3.181958
25                    C(Year)[T.2020]     3.128924
28                    C(Year)[T.2023]     3.033915
23                    C(Year)[T.2018]     2.975608
21                    C(Year)[T.2016]     2.935333
29                    C(Year)[T.2024]     2.933042
27                    C(Year)[T.2022]     2.920855
24                    C(Year)[T.2019]     2.920065
39                       tr_Insurance     2.848245
31                        Fire_Risk_z     2.847656
20                    C(Year)[T.2015]     2.754832
18                    C(Year)[T.2013]     2.600910
17                    C(Year)[T.2012]     2.594026
19                    C(Year)[T.2014]     2.426798

================ R2 BASE ================
   R2_marginal  R2_conditional  var_fixed  var_random  var_residual
0     0.849453        0.953415    0.26224    0.032095      0.014382

================ R2 LDV ================
   R2_marginal  R2_conditional  var_fixed  var_random  var_residual
0     0.886246        0.952438    0.26696    0.019939      0.014327

================ AR1 BASE ================
               AR1
count  6992.000000
mean      0.196589
std       0.544529
min      -1.000000
25%      -0.115074
50%       0.281116
75%       0.607210
max       1.000000
       lb_stat  lb_pvalue
1  4199.760945        0.0
2  4202.080454        0.0
3  4719.152969        0.0
4  5860.034517        0.0

================ AR1 LDV ================
               AR1
count  6992.000000
mean      0.082363
std       0.542413
min      -1.000000
25%      -0.255579
50%       0.121864
75%       0.474706
max       1.000000
       lb_stat      lb_pvalue
1   840.694019  7.668657e-185
2   870.011473  1.200629e-189
3  1147.641939  1.678574e-248
4  1736.333027   0.000000e+00

In [48]:
risk_col = "Tropical_Risk_z"
it_cols = ["tr_ITTotalLabor", "tr_ITService", "tr_ITSystem"]

# random slope는 labor within에만
random_slope_col = "tr_ITTotalLabor"

# -------------------------------------------------
# 1. Base models
# -------------------------------------------------
res_full, d_full, names_full = fit_mixedlm_joint(
    df, it_cols, risk_col,
    exclude_2020=False,
    random_slope_col=random_slope_col,
    add_ldv=False
)

res_no20, d_no20, names_no20 = fit_mixedlm_joint(
    df, it_cols, risk_col,
    exclude_2020=True,
    random_slope_col=random_slope_col,
    add_ldv=False
)

res_fe, d_fe, names_fe = fit_panel_fe_cluster_joint(
    df, it_cols, risk_col,
    exclude_2020=False,
    add_ldv=False
)

# -------------------------------------------------
# 2. LDV models
# -------------------------------------------------
res_full_ldv, d_full_ldv, names_full_ldv = fit_mixedlm_joint(
    df, it_cols, risk_col,
    exclude_2020=False,
    random_slope_col=random_slope_col,
    add_ldv=True
)

res_fe_ldv, d_fe_ldv, names_fe_ldv = fit_panel_fe_cluster_joint(
    df, it_cols, risk_col,
    exclude_2020=False,
    add_ldv=True
)

# -------------------------------------------------
# 3. Full coefficient tables
# -------------------------------------------------
full_mixed = extract_full_mixed_results(res_full)
full_mixed["model"] = "MixedLM_full"

full_mixed_no20 = extract_full_mixed_results(res_no20)
full_mixed_no20["model"] = "MixedLM_no2020"

full_panel = extract_full_panel_results(res_fe)
full_panel["model"] = "PanelFE_cluster"

full_mixed_ldv = extract_full_mixed_results(res_full_ldv)
full_mixed_ldv["model"] = "MixedLM_full_LDV"

full_panel_ldv = extract_full_panel_results(res_fe_ldv)
full_panel_ldv["model"] = "PanelFE_cluster_LDV"

full_long = pd.concat([
    full_mixed, full_mixed_no20, full_panel, full_mixed_ldv, full_panel_ldv
], ignore_index=True)

full_long["coef_se_p"] = full_long.apply(
    lambda x: f"{x['coef']:.3f} ({x['se']:.3f}), p={x['p']:.3f}",
    axis=1
)

full_wide = full_long.pivot_table(
    index="term",
    columns="model",
    values="coef_se_p",
    aggfunc="first"
)

# -------------------------------------------------
# 4. Key coefficient tables
# -------------------------------------------------
key_coef = pd.concat([
    extract_key_terms_joint_mixed(res_full, names_full, risk_col, "MixedLM_full", it_cols, add_ldv=False),
    extract_key_terms_joint_mixed(res_no20, names_no20, risk_col, "MixedLM_no2020", it_cols, add_ldv=False),
    extract_key_terms_joint_panel(res_fe, names_fe, risk_col, "PanelFE_cluster", it_cols, add_ldv=False),
    extract_key_terms_joint_mixed(res_full_ldv, names_full_ldv, risk_col, "MixedLM_full_LDV", it_cols, add_ldv=True),
    extract_key_terms_joint_panel(res_fe_ldv, names_fe_ldv, risk_col, "PanelFE_cluster_LDV", it_cols, add_ldv=True)
], ignore_index=True)

pretty_key = pretty_compare(key_coef)

# -------------------------------------------------
# 5. Diagnostics
# -------------------------------------------------
vif_base = compute_vif_from_mixedlm_result(res_full)
vif_ldv = compute_vif_from_mixedlm_result(res_full_ldv)

r2_base = mixedlm_r2_pred(res_full)
r2_no20 = mixedlm_r2_pred(res_no20)
r2_ldv = mixedlm_r2_pred(res_full_ldv)

r2_panel = panel_r2_table(res_fe)
r2_panel_ldv = panel_r2_table(res_fe_ldv)

ar1_desc, lb_table = residual_autocorr_diagnostics(res_full, d_full)
ar1_desc_ldv, lb_table_ldv = residual_autocorr_diagnostics(res_full_ldv, d_full_ldv)

fit_stats = pd.DataFrame([
    {"model": "MixedLM_full", "nobs": res_full.nobs, "llf": res_full.llf, "aic": res_full.aic, "bic": res_full.bic},
    {"model": "MixedLM_no2020", "nobs": res_no20.nobs, "llf": res_no20.llf, "aic": res_no20.aic, "bic": res_no20.bic},
    {"model": "MixedLM_full_LDV", "nobs": res_full_ldv.nobs, "llf": res_full_ldv.llf, "aic": res_full_ldv.aic, "bic": res_full_ldv.bic},
    {"model": "PanelFE_cluster", "nobs": getattr(res_fe, "nobs", np.nan), "llf": np.nan, "aic": np.nan, "bic": np.nan},
    {"model": "PanelFE_cluster_LDV", "nobs": getattr(res_fe_ldv, "nobs", np.nan), "llf": np.nan, "aic": np.nan, "bic": np.nan},
])

print("\n================ KEY COEFFICIENTS ================")
print(pretty_key)

print("\n================ FIT STATS ================")
print(fit_stats)

print("\n================ VIF BASE ================")
print(vif_base.head(40))

print("\n================ VIF LDV ================")
print(vif_ldv.head(40))

print("\n================ R2 BASE ================")
print(r2_base)

print("\n================ R2 LDV ================")
print(r2_ldv)

print("\n================ AR1 BASE ================")
print(ar1_desc)
print(lb_table)

print("\n================ AR1 LDV ================")
print(ar1_desc_ldv)
print(lb_table_ldv)

with pd.ExcelWriter("scenario3_tropical_joint_decomp_with_LDV.xlsx") as writer:
    full_long.to_excel(writer, sheet_name="full_coef_long", index=False)
    full_wide.to_excel(writer, sheet_name="full_coef_wide")
    key_coef.to_excel(writer, sheet_name="key_coef", index=False)
    pretty_key.to_excel(writer, sheet_name="pretty_key")
    fit_stats.to_excel(writer, sheet_name="fit_stats", index=False)
    vif_base.to_excel(writer, sheet_name="vif_base", index=False)
    vif_ldv.to_excel(writer, sheet_name="vif_ldv", index=False)
    r2_base.to_excel(writer, sheet_name="r2_base", index=False)
    r2_no20.to_excel(writer, sheet_name="r2_no2020", index=False)
    r2_ldv.to_excel(writer, sheet_name="r2_ldv", index=False)
    r2_panel.to_excel(writer, sheet_name="r2_panel", index=False)
    r2_panel_ldv.to_excel(writer, sheet_name="r2_panel_ldv", index=False)
    ar1_desc.to_excel(writer, sheet_name="ar1_base")
    lb_table.to_excel(writer, sheet_name="ljung_box_base")
    ar1_desc_ldv.to_excel(writer, sheet_name="ar1_ldv")
    lb_table_ldv.to_excel(writer, sheet_name="ljung_box_ldv")

/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/4245025718.py:722: AbsorbingEffectWarning:
Variables have been fully absorbed and have removed from the regression:

lag_tr_ITTotalLabor_mean_hotel, lag_tr_ITService_mean_hotel, lag_tr_ITSystem_mean_hotel, noaa_region9_Midwest, noaa_region9_Northeast, noaa_region9_Northern Plains, noaa_region9_Northwest, noaa_region9_Pacific, noaa_region9_South, noaa_region9_Southwest, noaa_region9_West

  res = mod.fit(cov_type="clustered", cluster_entity=True)
/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/4245025718.py:722: AbsorbingEffectWarning:
Variables have been fully absorbed and have removed from the regression:

lag_tr_ITTotalLabor_mean_hotel, lag_tr_ITService_mean_hotel, lag_tr_ITSystem_mean_hotel, noaa_region9_Midwest, noaa_region9_Northeast, noaa_region9_Northern Plains, noaa_region9_Northwest, noaa_region9_Pacific, noaa_region9_South, noaa_region9_Southwest, noaa_region9_West

  res = mod.fit(cov_type="clustered", cluster_entity=True)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/4245025718.py:319: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ar1_vals = dtmp.groupby(ID).apply(ar1_group).dropna()
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/4245025718.py:319: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ar1_vals = dtmp.groupby(ID).apply(ar1_group).dropna()

================ KEY COEFFICIENTS ================
model                                      MixedLM_full  \
term
Tropical_Risk_z                  0.006 (0.005), p=0.228
lag_RevPar_log                                      NaN
lag_tr_ITService_b_x_Rw          0.002 (0.004), p=0.615
lag_tr_ITService_mean_hotel     -0.029 (0.006), p=0.000
lag_tr_ITService_w_x_R          -0.000 (0.002), p=0.968
lag_tr_ITService_within         -0.003 (0.002), p=0.173
lag_tr_ITSystem_b_x_Rw          -0.006 (0.005), p=0.165
lag_tr_ITSystem_mean_hotel      -0.062 (0.011), p=0.000
lag_tr_ITSystem_w_x_R           -0.003 (0.002), p=0.231
lag_tr_ITSystem_within           0.000 (0.003), p=0.955
lag_tr_ITTotalLabor_b_x_Rw      -0.004 (0.006), p=0.482
lag_tr_ITTotalLabor_mean_hotel  -0.012 (0.009), p=0.165
lag_tr_ITTotalLabor_w_x_R       -0.001 (0.002), p=0.702
lag_tr_ITTotalLabor_within       0.002 (0.002), p=0.439

model                                  MixedLM_full_LDV  \
term
Tropical_Risk_z                  0.012 (0.004), p=0.007
lag_RevPar_log                   0.136 (0.009), p=0.000
lag_tr_ITService_b_x_Rw          0.002 (0.004), p=0.652
lag_tr_ITService_mean_hotel     -0.031 (0.005), p=0.000
lag_tr_ITService_w_x_R          -0.002 (0.002), p=0.333
lag_tr_ITService_within         -0.006 (0.002), p=0.002
lag_tr_ITSystem_b_x_Rw          -0.009 (0.005), p=0.039
lag_tr_ITSystem_mean_hotel      -0.066 (0.010), p=0.000
lag_tr_ITSystem_w_x_R           -0.003 (0.002), p=0.183
lag_tr_ITSystem_within          -0.008 (0.003), p=0.002
lag_tr_ITTotalLabor_b_x_Rw      -0.005 (0.006), p=0.370
lag_tr_ITTotalLabor_mean_hotel  -0.008 (0.008), p=0.300
lag_tr_ITTotalLabor_w_x_R       -0.001 (0.001), p=0.436
lag_tr_ITTotalLabor_within      -0.002 (0.002), p=0.404

model                                    MixedLM_no2020  \
term
Tropical_Risk_z                 -0.000 (0.005), p=0.986
lag_RevPar_log                                      NaN
lag_tr_ITService_b_x_Rw          0.001 (0.004), p=0.727
lag_tr_ITService_mean_hotel     -0.025 (0.006), p=0.000
lag_tr_ITService_w_x_R           0.000 (0.002), p=0.987
lag_tr_ITService_within         -0.004 (0.002), p=0.042
lag_tr_ITSystem_b_x_Rw           0.002 (0.005), p=0.752
lag_tr_ITSystem_mean_hotel      -0.049 (0.011), p=0.000
lag_tr_ITSystem_w_x_R           -0.003 (0.002), p=0.258
lag_tr_ITSystem_within           0.003 (0.002), p=0.185
lag_tr_ITTotalLabor_b_x_Rw      -0.007 (0.006), p=0.272
lag_tr_ITTotalLabor_mean_hotel  -0.012 (0.009), p=0.159
lag_tr_ITTotalLabor_w_x_R       -0.005 (0.002), p=0.017
lag_tr_ITTotalLabor_within      -0.001 (0.002), p=0.686

model                                   PanelFE_cluster  \
term
Tropical_Risk_z                  0.002 (0.011), p=0.890
lag_RevPar_log                                      NaN
lag_tr_ITService_b_x_Rw          0.005 (0.009), p=0.606
lag_tr_ITService_mean_hotel                         NaN
lag_tr_ITService_w_x_R          -0.000 (0.003), p=0.899
lag_tr_ITService_within         -0.002 (0.004), p=0.652
lag_tr_ITSystem_b_x_Rw          -0.003 (0.008), p=0.721
lag_tr_ITSystem_mean_hotel                          NaN
lag_tr_ITSystem_w_x_R           -0.004 (0.005), p=0.406
lag_tr_ITSystem_within          -0.004 (0.006), p=0.511
lag_tr_ITTotalLabor_b_x_Rw      -0.010 (0.015), p=0.481
lag_tr_ITTotalLabor_mean_hotel                      NaN
lag_tr_ITTotalLabor_w_x_R        0.002 (0.004), p=0.639
lag_tr_ITTotalLabor_within       0.002 (0.003), p=0.533

model                               PanelFE_cluster_LDV
term
Tropical_Risk_z                  0.004 (0.011), p=0.692
lag_RevPar_log                   0.041 (0.019), p=0.026
lag_tr_ITService_b_x_Rw          0.004 (0.009), p=0.628
lag_tr_ITService_mean_hotel                         NaN
lag_tr_ITService_w_x_R          -0.001 (0.003), p=0.839
lag_tr_ITService_within         -0.003 (0.004), p=0.467
lag_tr_ITSystem_b_x_Rw          -0.003 (0.008), p=0.720
lag_tr_ITSystem_mean_hotel                          NaN
lag_tr_ITSystem_w_x_R           -0.004 (0.005), p=0.393
lag_tr_ITSystem_within          -0.006 (0.006), p=0.247
lag_tr_ITTotalLabor_b_x_Rw      -0.012 (0.015), p=0.398
lag_tr_ITTotalLabor_mean_hotel                      NaN
lag_tr_ITTotalLabor_w_x_R        0.002 (0.004), p=0.645
lag_tr_ITTotalLabor_within       0.001 (0.003), p=0.742

================ FIT STATS ================
                 model  nobs          llf  aic  bic
0         MixedLM_full  3731  1143.481910  NaN  NaN
1       MixedLM_no2020  3308  1257.110351  NaN  NaN
2     MixedLM_full_LDV  3731  1266.826404  NaN  NaN
3      PanelFE_cluster  3748          NaN  NaN  NaN
4  PanelFE_cluster_LDV  3748          NaN  NaN  NaN

================ VIF BASE ================
                             variable          VIF
0                           Intercept  1599.367097
35                      tr_TotalLabor    32.211117
4    C(ChainSegment)[T.Upper Upscale]    24.991833
36                   tr_MaintTotalExp    19.754674
5          C(ChainSegment)[T.Upscale]    19.526117
1           C(ChainSegment)[T.Luxury]    16.332661
39               tr_SandMTotalExpense    10.564386
3   C(ChainSegment)[T.Upper Midscale]     9.050394
40                  tr_MktingTotalExp     8.444846
41                    tr_TotalMgmtFee     8.154513
32         lag_tr_ITSystem_mean_hotel     6.761893
43                           tr_Rooms     5.261900
19                    C(Year)[T.2022]     4.921023
24     lag_tr_ITTotalLabor_mean_hotel     4.314965
34             lag_tr_ITSystem_b_x_Rw     3.627473
37                    tr_UtilTotalExp     3.350604
20                    C(Year)[T.2023]     2.923080
18                    C(Year)[T.2021]     2.921332
21                    C(Year)[T.2024]     2.769559
30            lag_tr_ITService_b_x_Rw     2.694674
26         lag_tr_ITTotalLabor_b_x_Rw     2.690397
22                    Tropical_Risk_z     2.624465
38                       tr_Insurance     2.619632
17                    C(Year)[T.2020]     2.612351
28        lag_tr_ITService_mean_hotel     2.413347
13            C(noaa_region9)[T.West]     2.369138
7        C(noaa_region9)[T.Northeast]     2.276762
14                    C(Year)[T.2017]     2.258843
2         C(ChainSegment)[T.Midscale]     2.205699
16                    C(Year)[T.2019]     2.197744
6          C(noaa_region9)[T.Midwest]     2.105242
15                    C(Year)[T.2018]     2.086949
11           C(noaa_region9)[T.South]     1.755095
12       C(noaa_region9)[T.Southwest]     1.609067
42                     tr_PropertyTax     1.591214
9        C(noaa_region9)[T.Northwest]     1.566485
10         C(noaa_region9)[T.Pacific]     1.254907
44                                age     1.201903
23         lag_tr_ITTotalLabor_within     1.191855
31             lag_tr_ITSystem_within     1.179333

================ VIF LDV ================
                             variable          VIF
0                           Intercept  1603.327595
36                      tr_TotalLabor    32.403451
4    C(ChainSegment)[T.Upper Upscale]    24.996429
37                   tr_MaintTotalExp    19.986302
5          C(ChainSegment)[T.Upscale]    19.526974
1           C(ChainSegment)[T.Luxury]    16.333393
40               tr_SandMTotalExpense    10.926350
42                    tr_TotalMgmtFee     9.059859
3   C(ChainSegment)[T.Upper Midscale]     9.050400
41                  tr_MktingTotalExp     8.459732
44                           tr_Rooms     7.708634
33         lag_tr_ITSystem_mean_hotel     6.761893
19                    C(Year)[T.2022]     5.097815
25     lag_tr_ITTotalLabor_mean_hotel     4.318279
22                     lag_RevPar_log     3.699295
35             lag_tr_ITSystem_b_x_Rw     3.631930
38                    tr_UtilTotalExp     3.377081
18                    C(Year)[T.2021]     3.115441
20                    C(Year)[T.2023]     2.950841
17                    C(Year)[T.2020]     2.813524
21                    C(Year)[T.2024]     2.772410
31            lag_tr_ITService_b_x_Rw     2.694783
27         lag_tr_ITTotalLabor_b_x_Rw     2.690756
39                       tr_Insurance     2.628595
23                    Tropical_Risk_z     2.628531
29        lag_tr_ITService_mean_hotel     2.413348
13            C(noaa_region9)[T.West]     2.373385
7        C(noaa_region9)[T.Northeast]     2.276944
14                    C(Year)[T.2017]     2.258945
2         C(ChainSegment)[T.Midscale]     2.206227
16                    C(Year)[T.2019]     2.197832
6          C(noaa_region9)[T.Midwest]     2.114077
15                    C(Year)[T.2018]     2.088115
11           C(noaa_region9)[T.South]     1.759633
12       C(noaa_region9)[T.Southwest]     1.617625
43                     tr_PropertyTax     1.591496
9        C(noaa_region9)[T.Northwest]     1.566694
10         C(noaa_region9)[T.Pacific]     1.260774
45                                age     1.205329
32             lag_tr_ITSystem_within     1.204152

================ R2 BASE ================
   R2_marginal  R2_conditional  var_fixed  var_random  var_residual
0     0.891866        0.967467   0.338562    0.028699       0.01235

================ R2 LDV ================
   R2_marginal  R2_conditional  var_fixed  var_random  var_residual
0     0.911679        0.968588   0.347563    0.021696      0.011975

================ AR1 BASE ================
              AR1
count  451.000000
mean     0.007061
std      0.714111
min     -1.000000
25%     -0.625491
50%     -0.001649
75%      0.638374
max      1.000000
      lb_stat     lb_pvalue
1   14.891144  1.138964e-04
2  111.012001  7.835203e-25
3  151.917463  1.016523e-32
4  153.359607  3.878757e-32

================ AR1 LDV ================
              AR1
count  451.000000
mean    -0.156937
std      0.700806
min     -1.000000
25%     -0.874849
50%     -0.242507
75%      0.317526
max      1.000000
      lb_stat     lb_pvalue
1   55.377988  9.944383e-14
2  122.012265  3.201645e-27
3  149.377858  3.588990e-32
4  150.013634  2.022114e-31

In [49]:
#Fire + IT 3 decompisition

risk_col = "Fire_Risk_z"
it_cols = ["tr_ITTotalLabor", "tr_ITService", "tr_ITSystem"]

# random slope는 labor within에만
random_slope_col = "tr_ITTotalLabor"

# -------------------------------------------------
# 1. Base models
# -------------------------------------------------
res_full, d_full, names_full = fit_mixedlm_joint(
    df, it_cols, risk_col,
    exclude_2020=False,
    random_slope_col=random_slope_col,
    add_ldv=False
)

res_no20, d_no20, names_no20 = fit_mixedlm_joint(
    df, it_cols, risk_col,
    exclude_2020=True,
    random_slope_col=random_slope_col,
    add_ldv=False
)

res_fe, d_fe, names_fe = fit_panel_fe_cluster_joint(
    df, it_cols, risk_col,
    exclude_2020=False,
    add_ldv=False
)

# -------------------------------------------------
# 2. LDV models
# -------------------------------------------------
res_full_ldv, d_full_ldv, names_full_ldv = fit_mixedlm_joint(
    df, it_cols, risk_col,
    exclude_2020=False,
    random_slope_col=random_slope_col,
    add_ldv=True
)

res_fe_ldv, d_fe_ldv, names_fe_ldv = fit_panel_fe_cluster_joint(
    df, it_cols, risk_col,
    exclude_2020=False,
    add_ldv=True
)

# -------------------------------------------------
# 3. Full coefficient tables
# -------------------------------------------------
full_mixed = extract_full_mixed_results(res_full)
full_mixed["model"] = "MixedLM_full"

full_mixed_no20 = extract_full_mixed_results(res_no20)
full_mixed_no20["model"] = "MixedLM_no2020"

full_panel = extract_full_panel_results(res_fe)
full_panel["model"] = "PanelFE_cluster"

full_mixed_ldv = extract_full_mixed_results(res_full_ldv)
full_mixed_ldv["model"] = "MixedLM_full_LDV"

full_panel_ldv = extract_full_panel_results(res_fe_ldv)
full_panel_ldv["model"] = "PanelFE_cluster_LDV"

full_long = pd.concat([
    full_mixed, full_mixed_no20, full_panel, full_mixed_ldv, full_panel_ldv
], ignore_index=True)

full_long["coef_se_p"] = full_long.apply(
    lambda x: f"{x['coef']:.3f} ({x['se']:.3f}), p={x['p']:.3f}",
    axis=1
)

full_wide = full_long.pivot_table(
    index="term",
    columns="model",
    values="coef_se_p",
    aggfunc="first"
)

# -------------------------------------------------
# 4. Key coefficient tables
# -------------------------------------------------
key_coef = pd.concat([
    extract_key_terms_joint_mixed(res_full, names_full, risk_col, "MixedLM_full", it_cols, add_ldv=False),
    extract_key_terms_joint_mixed(res_no20, names_no20, risk_col, "MixedLM_no2020", it_cols, add_ldv=False),
    extract_key_terms_joint_panel(res_fe, names_fe, risk_col, "PanelFE_cluster", it_cols, add_ldv=False),
    extract_key_terms_joint_mixed(res_full_ldv, names_full_ldv, risk_col, "MixedLM_full_LDV", it_cols, add_ldv=True),
    extract_key_terms_joint_panel(res_fe_ldv, names_fe_ldv, risk_col, "PanelFE_cluster_LDV", it_cols, add_ldv=True)
], ignore_index=True)

pretty_key = pretty_compare(key_coef)

# -------------------------------------------------
# 5. Diagnostics
# -------------------------------------------------
vif_base = compute_vif_from_mixedlm_result(res_full)
vif_ldv = compute_vif_from_mixedlm_result(res_full_ldv)

r2_base = mixedlm_r2_pred(res_full)
r2_no20 = mixedlm_r2_pred(res_no20)
r2_ldv = mixedlm_r2_pred(res_full_ldv)

r2_panel = panel_r2_table(res_fe)
r2_panel_ldv = panel_r2_table(res_fe_ldv)

ar1_desc, lb_table = residual_autocorr_diagnostics(res_full, d_full)
ar1_desc_ldv, lb_table_ldv = residual_autocorr_diagnostics(res_full_ldv, d_full_ldv)

fit_stats = pd.DataFrame([
    {"model": "MixedLM_full", "nobs": res_full.nobs, "llf": res_full.llf, "aic": res_full.aic, "bic": res_full.bic},
    {"model": "MixedLM_no2020", "nobs": res_no20.nobs, "llf": res_no20.llf, "aic": res_no20.aic, "bic": res_no20.bic},
    {"model": "MixedLM_full_LDV", "nobs": res_full_ldv.nobs, "llf": res_full_ldv.llf, "aic": res_full_ldv.aic, "bic": res_full_ldv.bic},
    {"model": "PanelFE_cluster", "nobs": getattr(res_fe, "nobs", np.nan), "llf": np.nan, "aic": np.nan, "bic": np.nan},
    {"model": "PanelFE_cluster_LDV", "nobs": getattr(res_fe_ldv, "nobs", np.nan), "llf": np.nan, "aic": np.nan, "bic": np.nan},
])

print("\n================ KEY COEFFICIENTS ================")
print(pretty_key)

print("\n================ FIT STATS ================")
print(fit_stats)

print("\n================ VIF BASE ================")
print(vif_base.head(40))

print("\n================ VIF LDV ================")
print(vif_ldv.head(40))

print("\n================ R2 BASE ================")
print(r2_base)

print("\n================ R2 LDV ================")
print(r2_ldv)

print("\n================ AR1 BASE ================")
print(ar1_desc)
print(lb_table)

print("\n================ AR1 LDV ================")
print(ar1_desc_ldv)
print(lb_table_ldv)

with pd.ExcelWriter("scenario3_tropical_joint_decomp_with_LDV.xlsx") as writer:
    full_long.to_excel(writer, sheet_name="full_coef_long", index=False)
    full_wide.to_excel(writer, sheet_name="full_coef_wide")
    key_coef.to_excel(writer, sheet_name="key_coef", index=False)
    pretty_key.to_excel(writer, sheet_name="pretty_key")
    fit_stats.to_excel(writer, sheet_name="fit_stats", index=False)
    vif_base.to_excel(writer, sheet_name="vif_base", index=False)
    vif_ldv.to_excel(writer, sheet_name="vif_ldv", index=False)
    r2_base.to_excel(writer, sheet_name="r2_base", index=False)
    r2_no20.to_excel(writer, sheet_name="r2_no2020", index=False)
    r2_ldv.to_excel(writer, sheet_name="r2_ldv", index=False)
    r2_panel.to_excel(writer, sheet_name="r2_panel", index=False)
    r2_panel_ldv.to_excel(writer, sheet_name="r2_panel_ldv", index=False)
    ar1_desc.to_excel(writer, sheet_name="ar1_base")
    lb_table.to_excel(writer, sheet_name="ljung_box_base")
    ar1_desc_ldv.to_excel(writer, sheet_name="ar1_ldv")
    lb_table_ldv.to_excel(writer, sheet_name="ljung_box_ldv")

/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2261: ConvergenceWarning: The Hessian matrix at the estimated parameter values is not positive definite.
  warnings.warn(msg, ConvergenceWarning)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/4245025718.py:722: AbsorbingEffectWarning:
Variables have been fully absorbed and have removed from the regression:

lag_tr_ITTotalLabor_mean_hotel, lag_tr_ITService_mean_hotel, lag_tr_ITSystem_mean_hotel, noaa_region9_Midwest, noaa_region9_Northeast, noaa_region9_Northern Plains, noaa_region9_Northwest, noaa_region9_Pacific, noaa_region9_South, noaa_region9_Southwest, noaa_region9_West

  res = mod.fit(cov_type="clustered", cluster_entity=True)
/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2206: ConvergenceWarning: MixedLM optimization failed, trying a different optimizer may help.
  warnings.warn(msg, ConvergenceWarning)
/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2218: ConvergenceWarning: Gradient optimization failed, |grad| = 142.197964
  warnings.warn(msg, ConvergenceWarning)
/Users/jheo/opt/anaconda3/lib/python3.13/site-packages/statsmodels/regression/mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/4245025718.py:722: AbsorbingEffectWarning:
Variables have been fully absorbed and have removed from the regression:

lag_tr_ITTotalLabor_mean_hotel, lag_tr_ITService_mean_hotel, lag_tr_ITSystem_mean_hotel, noaa_region9_Midwest, noaa_region9_Northeast, noaa_region9_Northern Plains, noaa_region9_Northwest, noaa_region9_Pacific, noaa_region9_South, noaa_region9_Southwest, noaa_region9_West

  res = mod.fit(cov_type="clustered", cluster_entity=True)
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/4245025718.py:319: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ar1_vals = dtmp.groupby(ID).apply(ar1_group).dropna()
/var/folders/9q/rg7dh5cj2mx7xmtkv28d6jm80000gn/T/ipykernel_1919/4245025718.py:319: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ar1_vals = dtmp.groupby(ID).apply(ar1_group).dropna()

================ KEY COEFFICIENTS ================
model                                      MixedLM_full  \
term
Fire_Risk_z                      0.005 (0.006), p=0.392
lag_RevPar_log                                      NaN
lag_tr_ITService_b_x_Rw          0.004 (0.003), p=0.289
lag_tr_ITService_mean_hotel     -0.027 (0.006), p=0.000
lag_tr_ITService_w_x_R          -0.004 (0.001), p=0.003
lag_tr_ITService_within         -0.003 (0.002), p=0.187
lag_tr_ITSystem_b_x_Rw          -0.008 (0.005), p=0.072
lag_tr_ITSystem_mean_hotel      -0.064 (0.011), p=0.000
lag_tr_ITSystem_w_x_R            0.008 (0.002), p=0.000
lag_tr_ITSystem_within          -0.001 (0.003), p=0.817
lag_tr_ITTotalLabor_b_x_Rw       0.007 (0.006), p=0.231
lag_tr_ITTotalLabor_mean_hotel  -0.010 (0.009), p=0.226
lag_tr_ITTotalLabor_w_x_R       -0.001 (0.002), p=0.502
lag_tr_ITTotalLabor_within       0.002 (0.002), p=0.418

model                                  MixedLM_full_LDV  \
term
Fire_Risk_z                      0.008 (0.007), p=0.219
lag_RevPar_log                   0.132 (0.009), p=0.000
lag_tr_ITService_b_x_Rw          0.001 (0.004), p=0.880
lag_tr_ITService_mean_hotel     -0.031 (0.006), p=0.000
lag_tr_ITService_w_x_R          -0.003 (0.002), p=0.227
lag_tr_ITService_within         -0.006 (0.002), p=0.005
lag_tr_ITSystem_b_x_Rw          -0.008 (0.005), p=0.095
lag_tr_ITSystem_mean_hotel      -0.067 (0.010), p=0.000
lag_tr_ITSystem_w_x_R            0.006 (0.002), p=0.013
lag_tr_ITSystem_within          -0.008 (0.003), p=0.001
lag_tr_ITTotalLabor_b_x_Rw       0.009 (0.006), p=0.117
lag_tr_ITTotalLabor_mean_hotel  -0.005 (0.008), p=0.509
lag_tr_ITTotalLabor_w_x_R        0.001 (0.002), p=0.577
lag_tr_ITTotalLabor_within      -0.002 (0.002), p=0.480

model                                    MixedLM_no2020  \
term
Fire_Risk_z                     -0.002 (0.006), p=0.731
lag_RevPar_log                                      NaN
lag_tr_ITService_b_x_Rw          0.003 (0.003), p=0.353
lag_tr_ITService_mean_hotel     -0.025 (0.007), p=0.000
lag_tr_ITService_w_x_R          -0.003 (0.002), p=0.093
lag_tr_ITService_within         -0.003 (0.002), p=0.087
lag_tr_ITSystem_b_x_Rw          -0.004 (0.004), p=0.390
lag_tr_ITSystem_mean_hotel      -0.050 (0.011), p=0.000
lag_tr_ITSystem_w_x_R            0.000 (0.002), p=0.957
lag_tr_ITSystem_within           0.003 (0.002), p=0.216
lag_tr_ITTotalLabor_b_x_Rw       0.007 (0.006), p=0.214
lag_tr_ITTotalLabor_mean_hotel  -0.011 (0.009), p=0.212
lag_tr_ITTotalLabor_w_x_R       -0.002 (0.002), p=0.232
lag_tr_ITTotalLabor_within       0.001 (0.002), p=0.755

model                                   PanelFE_cluster  \
term
Fire_Risk_z                      0.006 (0.015), p=0.667
lag_RevPar_log                                      NaN
lag_tr_ITService_b_x_Rw          0.004 (0.008), p=0.564
lag_tr_ITService_mean_hotel                         NaN
lag_tr_ITService_w_x_R          -0.005 (0.004), p=0.307
lag_tr_ITService_within         -0.002 (0.004), p=0.625
lag_tr_ITSystem_b_x_Rw          -0.010 (0.010), p=0.311
lag_tr_ITSystem_mean_hotel                          NaN
lag_tr_ITSystem_w_x_R            0.008 (0.005), p=0.097
lag_tr_ITSystem_within          -0.004 (0.005), p=0.389
lag_tr_ITTotalLabor_b_x_Rw       0.005 (0.019), p=0.792
lag_tr_ITTotalLabor_mean_hotel                      NaN
lag_tr_ITTotalLabor_w_x_R       -0.001 (0.002), p=0.630
lag_tr_ITTotalLabor_within       0.002 (0.003), p=0.508

model                               PanelFE_cluster_LDV
term
Fire_Risk_z                      0.007 (0.015), p=0.661
lag_RevPar_log                   0.038 (0.018), p=0.037
lag_tr_ITService_b_x_Rw          0.004 (0.008), p=0.581
lag_tr_ITService_mean_hotel                         NaN
lag_tr_ITService_w_x_R          -0.004 (0.004), p=0.367
lag_tr_ITService_within         -0.003 (0.004), p=0.439
lag_tr_ITSystem_b_x_Rw          -0.010 (0.009), p=0.290
lag_tr_ITSystem_mean_hotel                          NaN
lag_tr_ITSystem_w_x_R            0.007 (0.005), p=0.118
lag_tr_ITSystem_within          -0.007 (0.005), p=0.160
lag_tr_ITTotalLabor_b_x_Rw       0.005 (0.019), p=0.773
lag_tr_ITTotalLabor_mean_hotel                      NaN
lag_tr_ITTotalLabor_w_x_R       -0.000 (0.002), p=0.880
lag_tr_ITTotalLabor_within       0.001 (0.003), p=0.743

================ FIT STATS ================
                 model  nobs          llf  aic  bic
0         MixedLM_full  3731  1142.022181  NaN  NaN
1       MixedLM_no2020  3308  1253.265303  NaN  NaN
2     MixedLM_full_LDV  3731  1264.074016  NaN  NaN
3      PanelFE_cluster  3748          NaN  NaN  NaN
4  PanelFE_cluster_LDV  3748          NaN  NaN  NaN

================ VIF BASE ================
                             variable          VIF
0                           Intercept  1601.601287
35                      tr_TotalLabor    32.133737
4    C(ChainSegment)[T.Upper Upscale]    24.700558
36                   tr_MaintTotalExp    19.747332
5          C(ChainSegment)[T.Upscale]    19.256966
1           C(ChainSegment)[T.Luxury]    16.270646
39               tr_SandMTotalExpense    10.551072
3   C(ChainSegment)[T.Upper Midscale]     8.922726
40                  tr_MktingTotalExp     8.397831
41                    tr_TotalMgmtFee     8.138153
32         lag_tr_ITSystem_mean_hotel     6.717575
43                           tr_Rooms     5.252960
19                    C(Year)[T.2022]     4.885186
22                        Fire_Risk_z     4.215092
24     lag_tr_ITTotalLabor_mean_hotel     4.202348
34             lag_tr_ITSystem_b_x_Rw     4.027769
37                    tr_UtilTotalExp     3.351126
13            C(noaa_region9)[T.West]     2.964538
20                    C(Year)[T.2023]     2.921509
18                    C(Year)[T.2021]     2.894610
21                    C(Year)[T.2024]     2.771107
30            lag_tr_ITService_b_x_Rw     2.755665
26         lag_tr_ITTotalLabor_b_x_Rw     2.733335
38                       tr_Insurance     2.586226
17                    C(Year)[T.2020]     2.550062
11           C(noaa_region9)[T.South]     2.437660
28        lag_tr_ITService_mean_hotel     2.431072
14                    C(Year)[T.2017]     2.258594
16                    C(Year)[T.2019]     2.185044
2         C(ChainSegment)[T.Midscale]     2.167298
15                    C(Year)[T.2018]     2.078447
7        C(noaa_region9)[T.Northeast]     1.774491
42                     tr_PropertyTax     1.594686
6          C(noaa_region9)[T.Midwest]     1.550060
12       C(noaa_region9)[T.Southwest]     1.544282
9        C(noaa_region9)[T.Northwest]     1.480105
44                                age     1.200890
23         lag_tr_ITTotalLabor_within     1.198808
31             lag_tr_ITSystem_within     1.175967
27            lag_tr_ITService_within     1.174846

================ VIF LDV ================
                             variable          VIF
0                           Intercept  1605.096349
36                      tr_TotalLabor    32.342382
4    C(ChainSegment)[T.Upper Upscale]    24.710560
37                   tr_MaintTotalExp    19.986027
5          C(ChainSegment)[T.Upscale]    19.261074
1           C(ChainSegment)[T.Luxury]    16.270670
40               tr_SandMTotalExpense    10.897761
42                    tr_TotalMgmtFee     9.031556
3   C(ChainSegment)[T.Upper Midscale]     8.923328
41                  tr_MktingTotalExp     8.417377
44                           tr_Rooms     7.680310
33         lag_tr_ITSystem_mean_hotel     6.717623
19                    C(Year)[T.2022]     5.062242
23                        Fire_Risk_z     4.215743
25     lag_tr_ITTotalLabor_mean_hotel     4.208255
35             lag_tr_ITSystem_b_x_Rw     4.030416
22                     lag_RevPar_log     3.703330
38                    tr_UtilTotalExp     3.379110
18                    C(Year)[T.2021]     3.098932
13            C(noaa_region9)[T.West]     2.975514
20                    C(Year)[T.2023]     2.950056
21                    C(Year)[T.2024]     2.774234
31            lag_tr_ITService_b_x_Rw     2.765184
17                    C(Year)[T.2020]     2.743648
27         lag_tr_ITTotalLabor_b_x_Rw     2.733795
39                       tr_Insurance     2.594483
11           C(noaa_region9)[T.South]     2.439096
29        lag_tr_ITService_mean_hotel     2.431200
14                    C(Year)[T.2017]     2.258698
16                    C(Year)[T.2019]     2.185188
2         C(ChainSegment)[T.Midscale]     2.168498
15                    C(Year)[T.2018]     2.079996
7        C(noaa_region9)[T.Northeast]     1.775434
43                     tr_PropertyTax     1.594776
6          C(noaa_region9)[T.Midwest]     1.556247
12       C(noaa_region9)[T.Southwest]     1.548997
9        C(noaa_region9)[T.Northwest]     1.480138
24         lag_tr_ITTotalLabor_within     1.209948
45                                age     1.204201
32             lag_tr_ITSystem_within     1.199541

================ R2 BASE ================
   R2_marginal  R2_conditional  var_fixed  var_random  var_residual
0     0.891769        0.968793   0.339839    0.029352      0.011893

================ R2 LDV ================
   R2_marginal  R2_conditional  var_fixed  var_random  var_residual
0     0.911274        0.968629   0.348495    0.021934      0.011997

================ AR1 BASE ================
              AR1
count  451.000000
mean    -0.016991
std      0.710339
min     -1.000000
25%     -0.616686
50%     -0.008599
75%      0.597320
max      1.000000
      lb_stat     lb_pvalue
1   17.292609  3.204308e-05
2  117.695393  2.771853e-26
3  158.278332  4.311873e-34
4  159.567471  1.810039e-33

================ AR1 LDV ================
              AR1
count  451.000000
mean    -0.152853
std      0.699033
min     -1.000000
25%     -0.848949
50%     -0.234571
75%      0.335644
max      1.000000
      lb_stat     lb_pvalue
1   53.065713  3.225742e-13
2  121.021854  5.253374e-27
3  148.603109  5.273422e-32
4  149.013250  3.312599e-31